flat_stancer.Rmd:
  path: dev/flat_stancer.Rmd
  state: active
  R:
  - R/utils.R
  - R/methods.R
  - R/agents.R
  - R/localisation.R
  - R/llm_stance.R
  - R/prompting.R
  - R/stages.R
  - R/verbose.R
  - R/scales.R
  - R/validate.R
  tests:
  - tests/testthat/test-utils.R
  - tests/testthat/test-validate.R
  - tests/testthat/test-verbose.R
  - tests/testthat/test-localisation.R
  - tests/testthat/test-scales.R
  - tests/testthat/test-prompting.R
  - tests/testthat/test-agents.R
  - tests/testthat/test-stages.R
  - tests/testthat/test-llm_stance.R
  - tests/testthat/test-methods.R
  vignettes: vignettes/get-started.Rmd
  inflate:
    flat_file: dev/flat_stancer.Rmd
    vignette_name: Get started
    open_vignette: false
    check: true
    document: true
    overwrite: ask
    clean: true
    codecov: true
