# WARNING - Generated by {fusen} from dev/flat_stancer.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("validate_fields returns invisible TRUE when all fields are present", {
  inputs <- list(texts = "some text", language = "en", targets = "target")
  required <- c("texts", "language")

  expect_true(validate_fields(inputs, required, "test_input"))
  expect_invisible(validate_fields(inputs, required, "test_input"))
})

test_that("validate_fields throws error when input is NULL", {
  expect_error(
    validate_fields(NULL, c("field1"), "expert data"),
    regexp = "Input for expert data is empty",
    fixed = TRUE
  )
})

test_that("validate_fields identifies missing fields", {
  inputs <- list(a = 1, b = 2)
  required <- c("a", "b", "c", "d")

  # The error message should list the missing fields: c, d
  expect_error(
    validate_fields(inputs, required, "content analysis results"),
    regexp = "Input for content analysis results misses required fields: `c`",
    fixed = TRUE
  )
})

test_that("validate_fields handles empty required_fields list", {
  # If nothing is required, any list (or even an empty one) should pass
  expect_true(validate_fields(list(a = 1), character(0)))
  expect_true(validate_fields(list(), character(0)))
})

test_that("validate_fields validates its own arguments", {
  expect_error(
    validate_fields(list(a = 1), "a", input_name = 123),
    regexp = "must be a character scalar.",
    fixed = TRUE
  )
})

test_that("validate_fields works with named vectors", {
  inputs <- c(field1 = "val1", field2 = "val2")
  expect_true(validate_fields(inputs, "field1"))

  expect_error(
    validate_fields(inputs, "field3", "input"),
    regexp = "Input for input misses required fields: `field3`",
    fixed = TRUE
  )
})

# Test 1: validate_inputs returns TRUE invisibly for valid inputs
test_that('validate_inputs returns TRUE invisibly for valid inputs', {
  result <- validate_inputs(c(1, 2, 3), expected_length = 3)
  expect_true(result)
  expect_invisible(validate_inputs(c(1, 2, 3), expected_length = 3))
})

# Test 2: validate_inputs with matching length
test_that('validate_inputs accepts inputs with matching length', {
  expect_invisible(validate_inputs(list(a = 1, b = 2), expected_length = 2))
})

# Test 3: validate_inputs rejects NULL inputs
test_that('validate_inputs rejects NULL inputs', {
  expect_error(
    validate_inputs(NULL, expected_length = 1),
    "returned unexpected results",
    fixed = TRUE
  )
})

# Test 4: validate_inputs rejects mismatched length
test_that('validate_inputs rejects mismatched length', {
  expect_error(
    validate_inputs(c(1, 2, 3), expected_length = 2),
    "returned unexpected results",
    fixed = TRUE
  )
})

# Test 5: validate_inputs with custom input_name in error message
test_that('validate_inputs includes custom input_name in error', {
  expect_error(
    validate_inputs(c(1, 2), expected_length = 3, input_name = "Results"),
    "Results returned unexpected results",
    fixed = TRUE
  )
})

# Test 6: validate_inputs rejects non-character input_name
test_that('validate_inputs rejects non-character input_name', {
  expect_error(
    validate_inputs(c(1, 2, 3), expected_length = 3, input_name = 123),
    "must be a character scalar",
    fixed = TRUE
  )
})

# Test 7: validate_inputs rejects non-scalar character input_name
test_that('validate_inputs rejects non-scalar character input_name', {
  expect_error(
    validate_inputs(c(1, 2, 3), expected_length = 3, input_name = c("a", "b")),
    "must be a character scalar",
    fixed = TRUE
  )
})

# Test 8: validate_inputs with empty vector
test_that('validate_inputs rejects empty vector when expecting non-zero length', {
  expect_error(
    validate_inputs(c(), expected_length = 1),
    "returned unexpected results",
    fixed = TRUE
  )
})

# Test 1: validate_character accepts valid character vector
test_that('validate_character accepts valid character vector', {
  result <- validate_character(c("text1", "text2"))
  expect_true(result)
  expect_invisible(validate_character(c("text1", "text2")))
})

# Test 2: validate_character accepts single character string
test_that('validate_character accepts single character string', {
  expect_invisible(validate_character("single text"))
})

# Test 3: validate_character rejects non-character input
test_that('validate_character rejects numeric input', {
  expect_error(
    validate_character(123),
    "must be a character vector",
    fixed = TRUE
  )
})

# Test 4: validate_character rejects logical input
test_that('validate_character rejects logical input', {
  expect_error(
    validate_character(TRUE),
    "must be a character vector",
    fixed = TRUE
  )
})

# Test 5: validate_character rejects list input
test_that('validate_character rejects list input', {
  expect_error(
    validate_character(list("a", "b")),
    "must be a character vector",
    fixed = TRUE
  )
})

# Test 6: validate_character rejects empty character vector
test_that('validate_character rejects empty vector', {
  expect_error(
    validate_character(character()),
    "cannot be empty",
    fixed = TRUE
  )
})

# Test 7: validate_character rejects vector with NA values
test_that('validate_character rejects vector with NA', {
  expect_error(
    validate_character(c("text", NA, "more")),
    "contains empty strings",
    fixed = TRUE
  )
})

# Test 8: validate_character rejects vector with empty strings
test_that('validate_character rejects vector with empty strings', {
  expect_error(
    validate_character(c("text", "", "more")),
    "contains empty strings",
    fixed = TRUE
  )
})

# Test 9: validate_character rejects vector with whitespace-only strings
test_that('validate_character rejects whitespace-only strings', {
  expect_error(
    validate_character(c("text", "   ", "more")),
    "contains empty strings",
    fixed = TRUE
  )
})

# Test 10: validate_character includes argument name in error message
test_that('validate_character includes arg name in error', {
  my_text <- 123
  expect_error(
    validate_character(my_text),
    "my_text",
    fixed = TRUE
  )
})

# Test 11: validate_character with mixed whitespace and empty
test_that('validate_character rejects mixed empty and whitespace', {
  expect_error(
    validate_character(c("valid", "\t", "\n")),
    "contains empty strings",
    fixed = TRUE
  )
})

# Test 12: validate_character accepts vector with special characters
test_that('validate_character accepts special characters', {
  expect_invisible(
    validate_character(c("text@123", "привіт", "\U1F680 emoji"))
  )
})

# Test 13: validate_character error message includes info about removal
test_that('validate_character error includes removal suggestion', {
  expect_error(
    validate_character(c("text", NA)),
    "consider removing them",
    fixed = TRUE
  )
})

# Test 1: validate_stage returns input unchanged when not NULL
test_that('validate_stage returns input unchanged', {
  input <- list(a = 1, b = 2)
  result <- validate_stage(input, stage_name = "Processing")
  expect_identical(result, input)
})

# Test 2: validate_stage rejects NULL input
test_that('validate_stage rejects NULL input', {
  expect_error(
    validate_stage(NULL, stage_name = "MyStage"),
    "MyStage returned NULL",
    fixed = TRUE
  )
})
