# WARNING - Generated by {fusen} from dev/flat_stancer.Rmd: do not edit by hand # nolint: line_length_linter.

# Reusing and slightly enhancing the MockChat
MockChat <- R6::R6Class(
  "MockChat",
  public = list(
    system_prompt = NULL,
    set_system_prompt = function(prompt) {
      self$system_prompt <- prompt
    }
  )
)

# Set-up common paths for tests
prompts_dir <- system.file('prompts', 'en', package = 'stancer')
if (!dir.exists(prompts_dir)) prompts_dir <- here::here('inst', 'prompts', 'en')

test_that("prepare_expert_chats successfully prepares linguist chats", {
  # 1. Prepare inputs list
  inputs <- list(
    texts = c("Statement 1", "Statement 2"),
    targets = c("Target A", "Target B"),
    target_types = c("statement", "statement"),
    language = "en",
    domain_roles = "linguistic expert",
    prompt_templates = list(
      `system-linguist` = file.path(prompts_dir, 'system-linguist.md'),
      `user-linguist` = file.path(prompts_dir, 'user-linguist.md')
    )
  )

  # Skip if files don't exist in the environment
  skip_if_not(all(file.exists(unlist(inputs$prompt_templates))))

  chat_base <- MockChat$new()

  # 2. Execute
  result <- prepare_expert_chats(inputs, chat_base, "linguist")

  # 3. Verify
  expect_type(result, "list")
  expect_named(result, c("chats", "tasks"))
  expect_length(result$tasks, 2)
  expect_length(result$chats, 1) # Single system prompt case
  expect_match(result$tasks[1], "Statement 1", fixed = TRUE)
  expect_is(result$chats[[1]]$system_prompt, 'character')
})

test_that("prepare_expert_chats successfully prepares domain chats", {
  inputs <- list(
    texts = "Statement about AI",
    targets = "AI",
    target_types = "object",
    language = "en",
    domain_roles = "AI ethics expert",
    prompt_templates = list(
      `system-domain` = file.path(prompts_dir, 'system-domain.md'),
      `user-domain` = file.path(prompts_dir, 'user-domain.md')
    )
  )

  skip_if_not(all(file.exists(unlist(inputs$prompt_templates))))

  chat_base <- MockChat$new()
  result <- prepare_expert_chats(inputs, chat_base, "domain")

  expect_length(result$tasks, 1)
  # Check if domain variable was correctly interpolated in system prompt
  # (Assuming the template uses {domain} placeholder)
  expect_match(result$chats[[1]]$system_prompt, "AI ethics expert", fixed = TRUE)
})

test_that("prepare_expert_chats throws error for invalid role", {
  inputs <- list(texts = "test")
  chat_base <- MockChat$new()

  expect_error(
    prepare_expert_chats(inputs, chat_base, "invalid_role"),
    regexp = "must be one of",
    fixed = TRUE
  )
})

test_that("prepare_expert_chats fails if inputs list is missing required elements", {
  # Missing 'texts' which is used in length(inputs$texts)
  inputs <- list(
    language = "en",
    prompt_templates = list()
  )
  chat_base <- MockChat$new()

  expect_error(prepare_expert_chats(inputs, chat_base, "linguist"))
})

test_that("prepare_expert_chats handles multiple system prompts (if prompts_prepare returns them)", {
  # This tests the logic flow through to tasks_prepare
  inputs <- list(
    texts = c("T1", "T2"),
    targets = c("A", "B"),
    target_types = c("object", "statement"),
    language = "en",
    domain_roles = c("Content analysis expert", "Statistician"), # Multiple roles
    prompt_templates = list(
      `system-domain` = file.path(prompts_dir, 'system-domain.md'),
      `user-domain` = file.path(prompts_dir, 'user-domain.md')
    )
  )

  skip_if_not(all(file.exists(unlist(inputs$prompt_templates))))

  chat_base <- MockChat$new()
  result <- prepare_expert_chats(inputs, chat_base, "domain")

  # If prompts_prepare returns 2 system prompts, tasks_prepare should return 2 chats
  # Note: This depends on how prompts_prepare handles vectorised 'domain'
  expect_named(result, c("chats", "tasks"))
  expect_type(result$chats, "list")
  expect_length(result$tasks, 2)
  expect_length(result$chats, 2)
  expect_is(result$chats[[1]]$system_prompt, 'character')
  expect_is(result$chats[[2]]$system_prompt, 'character')
  expect_match(
    result$chats[[1]]$system_prompt,
    "Content analysis expert",
    fixed = TRUE
  )
  expect_match(
    result$chats[[2]]$system_prompt,
    "Statistician",
    fixed = TRUE
  )
})
