# WARNING - Generated by {fusen} from dev/flat_stancer.Rmd: do not edit by hand # nolint: line_length_linter.

# Helper to stub all internal stages of llm_stance.character
stub_llm_stages <- function() {
  testthat::local_mocked_bindings(
    validate_character = TRUE,
    templates_collect = list(),
    validate_stage = function(x, ...) x,
    stage_1_parallel_analysis = function(x, ...) x,
    stage_2_parallel_debates = function(x, ...) x,
    stage_3_parallel_judgement = function(x, ...) {
      x$judgement_results <- data.frame(
        stance = "Neutral",
        explanation = "Mocked text mining result"
      )
      x
    }
  )
}

test_that('llm_stance.character is a function', {
  expect_true(inherits(llm_stance.character, 'function'))
})

test_that("llm_stance.character handles chat list and cloning", {
  # Mocking all internal stages to avoid API calls
  # stub_llm_stages()
  mockery::stub(llm_stance.character, "validate_character", TRUE)
  mockery::stub(llm_stance.character, "rlang::is_installed", TRUE)
  mockery::stub(llm_stance.character, "cld2::detect_language", "en")
  mockery::stub(llm_stance.character, "templates_collect", list())
  mockery::stub(
    llm_stance.character,
    "stage_1_parallel_analysis",
    function(x, ...) x
  )
  mockery::stub(
    llm_stance.character,
    "stage_2_parallel_debates",
    function(x, ...) x
  )
  mockery::stub(
    llm_stance.character,
    "stage_3_parallel_judgement",
    function(x, ...) {
      x$judgement_results <- data.frame(
        stance = "Negative", explanation = "Content analysis results")
      x
    }
  )
  mockery::stub(llm_stance.character, "validate_stage", function(x, ...) x)

  # Use an empty Chat object
  chat <- ellmer::chat_mistral(echo = "none")

  # Test with single chat
  res <- llm_stance(
    "Text mining is fun", "Text mining", type = "object",
    chat_base = chat, verbose = FALSE, language = "en"
  )

  expect_named(
    res, c("summary", "analysis", "debates", "judgements", "metadata")
  )
  expect_equal(res$metadata$n_total, 1)
  expect_s3_class(res, "stance_result")

  # Test with list of 1 chat
  chat_list <- list(chat)
  res_list <- llm_stance(
    "Text mining is fun", "Text mining", type = "object",
    chat_base = chat_list, verbose = FALSE, language = "en"
  )
  expect_named(
    res_list, c("summary", "analysis", "debates", "judgements", "metadata")
  )
  expect_equal(res_list$metadata$n_total, 1)
  expect_s3_class(res_list, "stance_result")

  # Test with list of 2 chats (Stage 1&2 use chat 1, Stage 3 uses chat 2)
  chat_list <- list(chat, chat)
  res_list <- llm_stance(
    "Text mining is fun", "Text mining", type = "object",
    chat_base = chat_list, verbose = FALSE, language = "en"
  )
  expect_named(
    res_list, c("summary", "analysis", "debates", "judgements", "metadata")
  )
  expect_equal(res_list$metadata$n_total, 1)
  expect_s3_class(res_list, "stance_result")

  # Test with list of 3 chats (Stage 1&2 use chat 1, Stage 3 uses chat 2)
  chat_list <- list(chat, chat, chat)
  res_list <- llm_stance(
    "Text mining is fun", "Text mining", type = "object",
    chat_base = chat_list, verbose = FALSE, language = "en"
  )
  expect_named(
    res_list, c("summary", "analysis", "debates", "judgements", "metadata")
  )
  expect_equal(res_list$metadata$n_total, 1)
  expect_s3_class(res_list, "stance_result")
})

test_that("llm_stance.character aborts on invalid language", {
  mockery::stub(llm_stance.character, "stancer_available_languages", c("en", "ru"))

  expect_error(
    llm_stance("text", "target", chat_base = list(), language = "fr"),
    regexp = "not available",
    fixed = FALSE
  )
})

test_that("llm_stance.character: language auto-detection and validation", {
  # stub_llm_stages()
  mockery::stub(llm_stance.character, "validate_character", TRUE)
  mockery::stub(llm_stance.character, "rlang::is_installed", TRUE)
  mockery::stub(llm_stance.character, "cld2::detect_language", "en")
  mockery::stub(llm_stance.character, "templates_collect", list())
  mockery::stub(
    llm_stance.character,
    "stage_1_parallel_analysis",
    function(x, ...) x
  )
  mockery::stub(
    llm_stance.character,
    "stage_2_parallel_debates",
    function(x, ...) x
  )
  mockery::stub(
    llm_stance.character,
    "stage_3_parallel_judgement",
    function(x, ...) {
      x$judgement_results <- data.frame(
        stance = "Negative", explanation = "Content analysis results")
      x
    }
  )
  mockery::stub(llm_stance.character, "validate_stage", function(x, ...) x)

  # 1. Test auto-detection warning
  expect_warning(
    llm_stance(
      "Some English text",
      "Target",
      type = "object",
      chat_base = ellmer::chat_anthropic(echo = "none"),
      language = NULL,
      verbose = FALSE
    ),
    "automatically detected", fixed = TRUE
  )

  # 2. Test error for non-character language input (e.g. numeric)
  expect_error(
    llm_stance("T", "T", chat_base = MockChat$new(), language = 123),
    "must be a character scalar", fixed = TRUE
  )
})

test_that("llm_stance.character: chat_base list length validation", {
  # stub_llm_stages()
  mockery::stub(llm_stance.character, "validate_character", TRUE)
  mockery::stub(llm_stance.character, "rlang::is_installed", TRUE)
  mockery::stub(llm_stance.character, "cld2::detect_language", "en")
  mockery::stub(llm_stance.character, "templates_collect", list())
  mockery::stub(
    llm_stance.character,
    "stage_1_parallel_analysis",
    function(x, ...) x
  )
  mockery::stub(
    llm_stance.character,
    "stage_2_parallel_debates",
    function(x, ...) x
  )
  mockery::stub(
    llm_stance.character,
    "stage_3_parallel_judgement",
    function(x, ...) {
      x$judgement_results <- data.frame(
        stance = "Positive", explanation = "Text mining results")
      x
    }
  )
  mockery::stub(llm_stance.character, "validate_stage", function(x, ...) x)
  chat <- ellmer::chat_mistral(echo = "none")

  # Error for 4 chats
  expect_error(
    llm_stance(
      text = "T",
      target = "T",
      language = "en",
      chat_base = list(chat, chat, chat, chat),
      verbose = FALSE
    ),
    "must have 1, 2, or 3 elements",
    fixed = TRUE
  )

  # Error for invalid object type
  expect_error(
    llm_stance(
      text = "T",
      target = "T",
      chat_base = "not a chat",
      language = "en",
      verbose = FALSE
    ),
    "object or a list of 1-3",
    fixed = TRUE
  )
})

test_that("llm_stance.character: domain_role length validation", {
  # stub_llm_stages()
  mockery::stub(llm_stance.character, "validate_character", TRUE)
  mockery::stub(llm_stance.character, "rlang::is_installed", TRUE)
  mockery::stub(llm_stance.character, "cld2::detect_language", "en")
  mockery::stub(llm_stance.character, "templates_collect", list())
  mockery::stub(
    llm_stance.character,
    "stage_1_parallel_analysis",
    function(x, ...) x
  )
  mockery::stub(
    llm_stance.character,
    "stage_2_parallel_debates",
    function(x, ...) x
  )
  mockery::stub(
    llm_stance.character,
    "stage_3_parallel_judgement",
    function(x, ...) {
      x$judgement_results <- data.frame(
        stance = "Positive", explanation = "Text analysis results")
      x
    }
  )
  mockery::stub(llm_stance.character, "validate_stage", function(x, ...) x)

  # n = 2, but domain_role = 3
  expect_error(
    llm_stance(
      text = c("T1", "T2"),
      target = "Target",
      chat_base = ellmer::chat_mistral(echo = "none"),
      language = "en",
      domain_role = c("R1", "R2", "R3"),
      verbose = FALSE
    ),
    "must have length 1 or 2",
    fixed = TRUE
  )
})

test_that("llm_stance.character: likert scale post-processing", {
  # Custom stub for stage 3 to return a specific Likert value
  mockery::stub(llm_stance.character, "validate_character", TRUE)
  mockery::stub(llm_stance.character, "templates_collect", list())
  mockery::stub(llm_stance.character, "validate_stage", function(x, ...) x)
  mockery::stub(
    llm_stance.character,
    "stage_1_parallel_analysis",
    function(x, ...) x
  )
  mockery::stub(
    llm_stance.character,
    "stage_2_parallel_debates",
    function(x, ...) x
  )
  mockery::stub(
    llm_stance.character,
    "stage_3_parallel_judgement",
    function(x, ...) {
      x$judgement_results <- data.frame(
        stance = "Strongly Agree",
        explanation = "Likert scale result"
      )
      x
    })

  res <- llm_stance(
    text = "T",
    target = "T",
    type = "statement",
    chat_base = ellmer::chat_mistral(echo = "none"),
    language = "uk",
    scale = "likert",
    verbose = FALSE
  )

  expect_s3_class(res$summary$stance, "factor")
  expect_true(is.ordered(res$summary$stance))
  expect_equal(as.character(res$summary$stance), "Strongly Agree")
})

test_that('llm_stance.data.frame is a function', {
  expect_true(inherits(llm_stance.data.frame, 'function'))
})

test_that('llm_stance.data.frame rejects wrong `data` argument', {
  expect_error(llm_stance(data = list()), "no applicable method", fixed = TRUE)
})

test_that("llm_stance.data.frame works with tidy evaluation", {
  df <- data.frame(my_text = "R is smart and tidy", my_target = "R language")

  # Mock the character method to return a dummy result
  mock_res <- list(
    summary = data.frame(
      stance = "Positive",
      explanation = "Text mining result"
    ),
    metadata = list(status = "ok")
  )
  mockery::stub(llm_stance.data.frame, "llm_stance", mock_res)

  res_df <- llm_stance(
    df, my_text, my_target, chat_base = list(), .output_col = ".stance",
    language = "en"
  )

  expect_true(".stance" %in% names(res_df))
  expect_equal(res_df$.stance, "Positive")
  expect_equal(attr(res_df, "llm_stance_metadata")$status, "ok")
})

test_that("llm_stance.data.frame: missing column and row mismatch", {
  df <- data.frame(band = "Kamelot")

  # 1. Missing column error
  expect_error(
    llm_stance(
      data = df,
      text = non_existent,
      target = band,
      type = "object",
      chat_base = list()
    ),
    "in data or environment",
    fixed = TRUE
  )

  # 2. Row mismatch warning
  mock_res <- list(
    summary = data.frame(
      stance = "Positive",
      explanation = "Text mining result"
    ),
    metadata = list(status = "ok")
  )
  mockery::stub(llm_stance.data.frame, "llm_stance", mock_res)

  df_long <- data.frame(
    txt = c("T1", "T2"),
    trg = c("A", "B")
  ) # 2 rows input

  expect_warning(
    df_stance <- llm_stance(
      data = df_long,
      text = txt,
      target = trg,
      language = "uk",
      chat_base = list(),
      verbose = FALSE
    ),
    "Result has 1 rows, but data has 2 rows",
    fixed = TRUE
  )
  expect_true(is.na(df_stance[[".stance"]][2]))
})
