# WARNING - Generated by {fusen} from dev/flat_stancer.Rmd: do not edit by hand # nolint: line_length_linter.

test_that('llm_stance.data.frame is a function', {
  expect_true(inherits(llm_stance.data.frame, 'function'))
})

test_that('llm_stance.data.frame rejects wrong `data` argument', {
  expect_error(
    llm_stance(x = list()),
    "no applicable method",
    fixed = TRUE
  )
})

test_that("llm_stance.data.frame works with tidy evaluation", {
  df <- data.frame(my_text = "R is smart and tidy", my_target = "R language")

  # Mock the character method to return a dummy result
  mock_res <- list(
    summary = data.frame(
      stance = "Positive",
      explanation = "Text mining result"
    ),
    metadata = list(status = "ok")
  )
  mockery::stub(llm_stance.data.frame, "llm_stance", mock_res)

  res_df <- llm_stance(
    df, my_text, my_target, chat_base = list(),
    .output_col = ".stance",
    language = "en",
    verbose = TRUE
  )

  expect_true(".stance" %in% names(res_df))
  expect_equal(res_df$.stance, "Positive")
  expect_equal(attr(res_df, "llm_stance_metadata")$status, "ok")
})

test_that("llm_stance.data.frame: missing column and row mismatch", {
  df <- data.frame(band = "Kamelot")

  # 1. Missing column error
  expect_error(
    llm_stance(
      df,
      text = non_existent,
      target = band,
      type = "object",
      chat_base = list()
    ),
    "in data or environment",
    fixed = TRUE
  )

  # 2. Row mismatch warning
  mock_res <- list(
    summary = data.frame(
      stance = "Positive",
      explanation = "Text mining result"
    ),
    metadata = list(status = "ok")
  )
  mockery::stub(llm_stance.data.frame, "llm_stance", mock_res)

  df_long <- data.frame(
    txt = c("T1", "T2"),
    trg = c("A", "B")
  ) # 2 rows input

  expect_warning(
    df_stance <- llm_stance(
      df_long,
      text = txt,
      target = trg,
      language = "uk",
      chat_base = list(),
      verbose = TRUE
    ),
    "Result has 1 rows, but data has 2 rows",
    fixed = TRUE
  )
  expect_true(is.na(df_stance[[".stance"]][2]))
})

test_that("llm_stance.data.frame: `language` evaluates to NULL", {
  df <- data.frame(band = "Kamelot", text = "Kamelot is great")

  mock_res <- list(
    summary = data.frame(
      stance = "Strongly Agree",
      explanation = "Likert scale result"
    ),
    metadata = list(status = "ok")
  )
  mockery::stub(llm_stance.data.frame, "llm_stance", mock_res)
  
  expect_warning(
    llm_stance(
      df,
      text = text,
      target = band,
      type = "object",
      language = NULL,
      chat_base = list()
    ),
    "in data or environment",
    fixed = TRUE
  )
})

# Set-up Mock Object
mock_res <- structure(
  list(
    summary = data.frame(
      text = "Julia is fast & beautiful",
      target = "Julia programming language",
      target_type = "object",
      language = "en",
      stance = "Positive",
      explanation = "Content analysis results"
    ),
    metadata = list(
      n_total = 1,
      n_processed = 1,
      n_failed = 0,
      language = "en",
      types = "object",
      domain_role = "sociologist",
      model = "gpt-4o",
      elapsed = 12.3456,
      timestamp = as.POSIXct("2026-04-30 15:30:00", tz = "GMT")
    )
  ),
  class = c("stance_result", "list")
)

test_that("print.stance_result outputs correct metadata and table", {
  # Verify Output
  # We check for key elements in the printed output
  expect_output(print(mock_res), "Stance Analysis Result", fixed = TRUE)
  expect_output(print(mock_res), "Processed: 1/1 items", fixed = TRUE)
  expect_output(print(mock_res), "Language: en", fixed = TRUE)
  expect_output(print(mock_res), "Model(s) used: gpt-4o", fixed = TRUE)
  expect_output(print(mock_res), "Time elapsed: 12.35 sec", fixed = TRUE) # Rounded
  expect_output(print(mock_res), "Summary Table:", fixed = TRUE)

  # 3. Verify Invisible Return
  # Using capture.output to suppress printing during the check
  expect_invisible(val <- print(mock_res))
  expect_equal(val, mock_res)
  expect_s3_class(print(mock_res), "stance_result")
})

test_that("print.stance_result handles multiple models and roles", {
  mock_res <- structure(
    list(
      summary = data.frame(
        text = c("Контент-анализ это важно", "Text mining это интересно")
      ),
      metadata = list(
        n_total = 2,
        n_processed = 2,
        n_failed = 0,
        language = "ru",
        types = c("object", "statement"),
        domain_role = c("социолог", "лингвист"),
        model = c("claude-3", "gpt-4o"),
        elapsed = 5.111,
        timestamp = as.POSIXct("2026-04-30 15:30:00", tz = "GMT")
      )
    ),
    class = c("stance_result", "list")
  )

  # Check collapsed strings
  expect_output(print(mock_res), "Types: object, statement", fixed = TRUE)
  expect_output(print(mock_res), "Domain role(s): социолог, лингв", fixed = TRUE)
  expect_output(print(mock_res), "Model(s) used: claude-3, gpt-4o", fixed = TRUE)
})

test_that('summary.stance_result is a function', {
  expect_true(inherits(summary.stance_result, 'function'))
})

test_that("summary.stance_result outputs distribution tables", {
  # 1. Set-up Mock Object with multiple items
  mock_res <- structure(
    list(
      summary = data.frame(
        text = c("T1", "T2", "T3"),
        target = c("Target A", "Target A", "Target B"),
        stance = factor(
          c("Negative", "Neutral", "Negative"),
          levels = c("Positive", "Neutral", "Negative")
        )
      )
    ),
    class = c("stance_result", "list")
  )

  # 2. Verify Output Headers
  expect_output(summary(mock_res), "Stance Distribution:", fixed = TRUE)
  expect_output(summary(mock_res), "By Target:", fixed = TRUE)

  # 3. Verify Table Content
  # Check for stance counts in the distribution table
  expect_output(summary(mock_res), "Positive Neutral", fixed = TRUE)
  expect_output(summary(mock_res), "0        1        2", fixed = TRUE)

  # Check for target-based cross-tabulation
  expect_output(summary(mock_res), "Target A", fixed = TRUE)
  expect_output(summary(mock_res), "Target B", fixed = TRUE)

  # 4. Verify Invisible Return
  expect_invisible(val <- summary(mock_res))
  expect_equal(val, mock_res)
})

test_that("summary.stance_result handles empty or NA results", {
  mock_res <- structure(
    list(
      summary = data.frame(
        target = "Target A",
        stance = factor(
          NA_character_,
          levels = c("Positive", "Neutral", "Negative")
        )
      )
    ),
    class = c("stance_result", "list")
  )

  # table() by default excludes NA, so we expect 0 counts but the headers should remain
  expect_output(summary(mock_res), "Stance Distribution:", fixed = TRUE)
  expect_output(summary(mock_res), "Positive Neutral", fixed = TRUE)
  expect_output(summary(mock_res), "0        0        0", fixed = TRUE)
})

test_that('as.data.frame.stance_result is a function', {
  expect_true(inherits(as.data.frame.stance_result, 'function'))
})

test_that("as.data.frame.stance_result extracts summary correctly", {
  # 1. Set-up Mock Object
  mock_summary <- data.frame(
    text = "R is smart and tidy",
    target = "R is good",
    type = "statement",
    stance = "Positive",
    explanation = "AI Content Analysis Reasoning",
    stringsAsFactors = FALSE
  )

  mock_res <- structure(
    list(
      summary = mock_summary,
      metadata = list(n_total = 1)
    ),
    class = c("stance_result", "list")
  )

  # 2. Test conversion
  df_result <- as.data.frame(mock_res)

  expect_s3_class(df_result, "data.frame")
  expect_equal(nrow(df_result), 1)
  expect_equal(df_result$stance, "Positive")
  expect_equal(df_result, mock_summary)
})

test_that("as.data.frame.stance_result works with pipes", {
  # This is a common use case for users
  mock_res <- structure(
    list(
      summary = data.frame(a = 1:3, b = 4:6)
    ),
    class = c("stance_result", "list")
  )

  # Check if it behaves correctly in a functional chain
  res <- mock_res |>
    as.data.frame() |>
    nrow()

  expect_equal(res, 3)
})

test_that("as.data.frame.stance_result ignores additional arguments gracefully", {
  # Since our implementation just returns x$summary, we check it doesn't crash
  # if standard as.data.frame arguments are passed
  mock_res <- structure(
    list(summary = data.frame(a = 1)),
    class = c("stance_result", "list")
  )

  expect_no_error(as.data.frame(mock_res, row.names = "1", optional = TRUE))
})

test_that('inspect.stance_result is a function', {
  expect_true(inherits(inspect.stance_result, 'function'))
})

mock_res <- structure(
  list(
    summary = data.frame(
      text = c("Julia is fast & beautiful", "R is smart and tidy"),
      target = c("Julia programming language", "R programming language"),
      target_type = "object",
      language = "en",
      stance = factor(
        'Positive',
        levels = c('Positive', 'Negative', 'Neutral')
      ),
      explanation = c(
        "The explicit statement 'Julia is fast & beautiful'",
        "The explicit statement 'R is smart and tidy'"
      )
    ),
    analysis = list(linguistic = c("L1", "L2"), domain = c("D1", "D2")),
    debates = list(positive = c("P1", "P2"), negative = c("N1", "N2")),
    metadata = list(
      n_total = 2L,
      n_processed = 2L,
      n_failed = 0L,
      language = "en",
      types = "object",
      domain_role = c("Python coder", "computer scientist"),
      model = "claude 3",
      elapsed = 11.111,
      timestamp = as.POSIXct("2026-04-30 15:30:00", tz = "GMT")
    )
  ),
  class = c("stance_result", "list")
)

test_that("inspect.stance_result: metadata and basic structure", {
  # 1. Metadata
  expect_output(inspect(mock_res, what = "metadata"), "METADATA", fixed = TRUE)
  expect_output(inspect(mock_res, what = "metadata"), "model:", fixed = TRUE)

  # 2. Analysis sections list (within = NULL)
  expect_output(
    inspect(mock_res, what = "analysis"),
    "ANALYSIS - Available sections",
    fixed = TRUE
  )
  expect_output(inspect(mock_res, what = "analysis"), "linguistic", fixed = TRUE)

  # 3. Specific analysis content
  expect_output(
    inspect(mock_res, what = "analysis", within = "linguistic", index = 1),
    "ANALYSIS: linguistic [row 1]",
    fixed = TRUE
  )
  expect_output(
    inspect(mock_res, what = "analysis", within = "linguistic", index = 1),
    "L1",
    fixed = TRUE
  )

  expect_output(
    inspect(mock_res, what = "debates"),
    "DEBATES - Available sections",
    fixed = TRUE
  )

  expect_output(
    inspect(mock_res, what = "debates", within = "positive", index = 1),
    "DEBATES: positive [row 1]",
    fixed = TRUE
  )
  expect_output(
    inspect(mock_res, what = "debates", within = "negative", index = 2),
    "N2",
    fixed = TRUE
  )
})

test_that("inspect.stance_result: debates and empty content", {
  mock_res <- structure(
    list(
      debates = list(positive = c("P1", NA_character_))
    ),
    class = c("stance_result", "list")
  )

  # 1. Debates sections list
  expect_output(
    inspect(mock_res, what = "debates"),
    "DEBATES - Available sections",
    fixed = TRUE
  )

  # 2. Empty content (NA)
  expect_error(
    inspect(mock_res,what = "debates", within = "positive", index = 2),
    "out of bounds",
    fixed = TRUE
  )
})

test_that("inspect.stance_result: explanation and warnings", {
  # 1. Explanation content
  expect_output(
    inspect(mock_res, what = "explanation"),
    "EXPLANATION: [row 1]",
    fixed = TRUE
  )
  expect_output(
    inspect(mock_res, what = "explanation"),
    "The explicit statement",
    fixed = TRUE
  )

  # 2. Warning when 'within' is provided for explanation
  expect_warning(
    inspect(mock_res, what = "explanation", within = "ignored"),
    "has no sections"
  )
})

test_that("inspect.stance_result: error handling (out of bounds and missing sections)", {
  # 1. Invalid 'within' section
  expect_error(
    inspect(mock_res, what = "analysis", within = "wrong"),
    "not found in analysis",
    fixed = TRUE
  )
  expect_error(
    inspect(mock_res, what = "debates", within = "wrong"),
    "not found in debates",
    fixed = TRUE
  )

  # 2. Index out of bounds
  expect_error(
    inspect(mock_res, what = "analysis", within = "linguistic", index = 99),
    "out of bounds"
  )
  expect_error(
    inspect(mock_res, what = "explanation", index = 99),
    "out of bounds"
  )
  expect_error(
    inspect(mock_res, what = "debates", within = "positive", index = 99),
    "out of bounds"
  )

  # 3. Invalid index type
  expect_error(inspect(mock_res, index = 0), "must be a whole number")
  
  # 4. Empty
  mock_res_empty <- mock_res
  mock_res_empty$analysis$linguistic[1] <- NA_character_
  expect_output(
    inspect(mock_res_empty, "analysis", "linguistic", 1),
    "(empty)",
    fixed = TRUE
  )
  mock_res_empty <- mock_res
  mock_res_empty$debates$negative[2] <- NA_character_
  expect_output(
    inspect(mock_res_empty, "debates", "negative", 2),
    "(empty)",
    fixed = TRUE
  )
  mock_res_empty <- mock_res
  mock_res_empty$summary$explanation[1] <- NA_character_
  expect_output(
    inspect(mock_res_empty, "explanation", index = 1),
    "(empty)",
    fixed = TRUE
  )
})
