# WARNING - Generated by {fusen} from dev/flat_stancer.Rmd: do not edit by hand # nolint: line_length_linter.

test_that('inspect.stance_result is a function', {
  expect_true(inherits(inspect.stance_result, 'function'))
})

mock_res <- structure(
  list(
    summary = data.frame(
      text = c("Julia is fast & beautiful", "R is smart and tidy"),
      target = c("Julia programming language", "R programming language"),
      target_type = "object",
      language = "en",
      stance = factor(
        'Positive',
        levels = c('Positive', 'Negative', 'Neutral')
      ),
      explanation = c(
        "The explicit statement 'Julia is fast & beautiful'",
        "The explicit statement 'R is smart and tidy'"
      )
    ),
    analysis = list(linguistic = c("L1", "L2"), domain = c("D1", "D2")),
    debates = list(positive = c("P1", "P2"), negative = c("N1", "N2")),
    metadata = list(
      n_total = 2L,
      n_processed = 2L,
      n_failed = 0L,
      language = "en",
      types = "object",
      domain_role = c("Python coder", "computer scientist"),
      model = "claude 3",
      elapsed = 11.111,
      timestamp = as.POSIXct("2026-04-30 15:30:00", tz = "GMT")
    )
  ),
  class = c("stance_result", "list")
)

test_that("inspect.stance_result: metadata and basic structure", {
  # 1. Metadata
  expect_output(inspect(mock_res, what = "metadata"), "METADATA", fixed = TRUE)
  expect_output(inspect(mock_res, what = "metadata"), "model:", fixed = TRUE)

  # 2. Analysis sections list (within = NULL)
  expect_output(
    inspect(mock_res, what = "analysis"),
    "ANALYSIS - Available sections",
    fixed = TRUE
  )
  expect_output(inspect(mock_res, what = "analysis"), "linguistic", fixed = TRUE)

  # 3. Specific analysis content
  expect_output(
    inspect(mock_res, what = "analysis", within = "linguistic", index = 1),
    "ANALYSIS: linguistic [row 1]",
    fixed = TRUE
  )
  expect_output(
    inspect(mock_res, what = "analysis", within = "linguistic", index = 1),
    "L1",
    fixed = TRUE
  )

  expect_output(
    inspect(mock_res, what = "debates"),
    "DEBATES - Available sections",
    fixed = TRUE
  )

  expect_output(
    inspect(mock_res, what = "debates", within = "positive", index = 1),
    "DEBATES: positive [row 1]",
    fixed = TRUE
  )
  expect_output(
    inspect(mock_res, what = "debates", within = "negative", index = 2),
    "N2",
    fixed = TRUE
  )
})

test_that("inspect.stance_result: debates and empty content", {
  mock_res <- structure(
    list(
      debates = list(positive = c("P1", NA_character_))
    ),
    class = c("stance_result", "list")
  )

  # 1. Debates sections list
  expect_output(
    inspect(mock_res, what = "debates"),
    "DEBATES - Available sections",
    fixed = TRUE
  )

  # 2. Empty content (NA)
  expect_error(
    inspect(mock_res,what = "debates", within = "positive", index = 2),
    "out of bounds",
    fixed = TRUE
  )
})

test_that("inspect.stance_result: explanation and warnings", {
  # 1. Explanation content
  expect_output(
    inspect(mock_res, what = "explanation"),
    "EXPLANATION: [row 1]",
    fixed = TRUE
  )
  expect_output(
    inspect(mock_res, what = "explanation"),
    "The explicit statement",
    fixed = TRUE
  )

  # 2. Warning when 'within' is provided for explanation
  expect_warning(
    inspect(mock_res, what = "explanation", within = "ignored"),
    "has no sections"
  )
})

test_that("inspect.stance_result: error handling (out of bounds and missing sections)", {
  # 1. Invalid 'within' section
  expect_error(
    inspect(mock_res, what = "analysis", within = "wrong"),
    "not found in analysis",
    fixed = TRUE
  )
  expect_error(
    inspect(mock_res, what = "debates", within = "wrong"),
    "not found in debates",
    fixed = TRUE
  )

  # 2. Index out of bounds
  expect_error(
    inspect(mock_res, what = "analysis", within = "linguistic", index = 99),
    "out of bounds"
  )
  expect_error(
    inspect(mock_res, what = "explanation", index = 99),
    "out of bounds"
  )
  expect_error(
    inspect(mock_res, what = "debates", within = "positive", index = 99),
    "out of bounds"
  )

  # 3. Invalid index type
  expect_error(inspect(mock_res, index = 0), "must be a whole number")
})
