# WARNING - Generated by {fusen} from dev/flat_stancer.Rmd: do not edit by hand # nolint: line_length_linter.

# Reusing the MockChat
MockChat <- R6::R6Class(
  "MockChat",
  public = list(
    system_prompt = NULL,
    set_system_prompt = function(prompt) {
      self$system_prompt <- prompt
    }
  )
)

test_that("stage_1_parallel_analysis validates inputs and returns results", {
  # 1. Set-up Data
  inputs <- list(
    texts = c("T1", "T2"),
    targets = c("A", "B"),
    target_types = c("statement", "statement"),
    language = "en",
    domain_roles = "AI Expert",
    prompt_templates = list(a = 1)
  )

  # 2. Set-up Mocks
  # Mock validate_fields to just pass
  mockery::stub(stage_1_parallel_analysis, "validate_fields", TRUE)

  # Mock execute_role to return role-specific strings
  mock_execute <- mockery::mock(
    c("L1", "L2"), # First call: linguist
    c("D1", "D2"), # Second call: domain
    c("S1", "S2")  # Third call: interpreter
  )
  mockery::stub(stage_1_parallel_analysis, "execute_role", mock_execute)

  # Mock tictoc to avoid console noise/errors
  mockery::stub(stage_1_parallel_analysis, "tictoc::tic", NULL)
  mockery::stub(stage_1_parallel_analysis, "tictoc::toc", NULL)

  # 3. Execute
  result <- stage_1_parallel_analysis(
    inputs,
    chat_base = MockChat$new(),
    verbose = FALSE
  )

  # 4. Verify
  expect_true("analysis_results" %in% names(result))
  expect_named(result$analysis_results, c("linguistic", "domain", "social_media"))
  expect_equal(result$analysis_results$linguistic, c("L1", "L2"))
  expect_equal(result$analysis_results$domain, c("D1", "D2"))
  expect_equal(result$analysis_results$social_media, c("S1", "S2"))

  # Verify execute_role was called exactly 3 times
  mockery::expect_called(mock_execute, 3)
})

test_that("stage_1_parallel_analysis fails if required fields are missing", {
  # Missing domain_roles
  incomplete_inputs <- list(
    texts = "T1",
    targets = "X",
    target_types = "statement",
    language = "en",
    prompt_templates = list()
  )

  # We don't stub validate_fields here because we want to test that it's actually called
  # and catches the error as expected.
  mockery::stub(stage_1_parallel_analysis, "validate_fields", validate_fields)
  expect_error(
    stage_1_parallel_analysis(incomplete_inputs, MockChat$new(), verbose = FALSE),
    regexp = "misses required fields: `domain_roles`"
  )
})

test_that("stage_1_parallel_analysis respects verbose flag", {
  inputs <- list(
    texts = "T1", targets = "A", target_types = "statement",
    language = "en", domain_roles = "AI Expert", prompt_templates = list()
  )

  mockery::stub(stage_1_parallel_analysis, "validate_fields", TRUE)
  mockery::stub(stage_1_parallel_analysis, "execute_role", list("Result"))
  mockery::stub(stage_1_parallel_analysis, "tictoc::tic", NULL)
  mockery::stub(stage_1_parallel_analysis, "tictoc::toc", NULL)

  expect_output(
    stage_1_parallel_analysis(inputs, MockChat$new(), verbose = TRUE),
    regexp = "Stage 1: Expert analysis"
  )

  expect_silent(
    stage_1_parallel_analysis(inputs, MockChat$new(), verbose = FALSE)
  )
})

# Reusing the MockChat
MockChat <- R6::R6Class(
  "MockChat",
  public = list(
    system_prompt = NULL,
    set_system_prompt = function(prompt) {
      self$system_prompt <- prompt
    },
    chat = function(..., echo = NULL) paste("Response", seq_along(list(...)))
  )
)

test_that("stage_2_parallel_debates executes three debate branches", {
  # 1. Set-up Data
  inputs <- list(
    texts = c("T1", "T2"),
    targets = c("A", "B"),
    target_types = c("statement", "statement"),
    language = "en",
    scale = 'likert',
    prompt_templates = list(t = 1),
    analysis_results = list(
      linguistic = c("L1", "L2"),
      domain = c("D1", "D2"),
      social_media = c("S1", "S2")
    )
  )

  # 2. Set-up Mocks
  # mockery::stub(stage_2_parallel_debates, "validate_fields", TRUE)
  # mockery::stub(stage_2_parallel_debates, "validate_inputs", TRUE)
  mockery::stub(stage_2_parallel_debates, "tictoc::tic", NULL)
  mockery::stub(stage_2_parallel_debates, "tictoc::toc", NULL)

  # Mock l() localization helper
  mockery::stub(stage_2_parallel_debates, "l", function(lang, key, scale) key)

  # Mock prepare_debater_chats
  # We return a dummy chat and tasks
  mockery::stub(
    stage_2_parallel_debates,
    "prepare_debater_chats",
    function(stance, ...) {
      list(chats = list(MockChat$new()), tasks = paste(stance, "task"))
    }
  )

  # Mock parallel_chat_text to return stance-specific results
  mock_parallel <- mockery::mock(
    "Pos Result", # first call (positive)
    "Neg Result", # second call (negative)
    "Neu Result"  # third call (neutral)
  )
  mockery::stub(stage_2_parallel_debates, "ellmer::parallel_chat_text", mock_parallel)

  # 3. Execute
  result <- stage_2_parallel_debates(
    inputs,
    MockChat$new(),
    verbose = TRUE
  )

  # 4. Verify
  expect_named(result$debate_results, c("positive", "negative", "neutral"))
  expect_equal(result$debate_results$positive, "Pos Result")
  expect_equal(result$debate_results$negative, "Neg Result")
  expect_equal(result$debate_results$neutral, "Neu Result")

  # Verify it was called 3 times (once for each stance)
  mockery::expect_called(mock_parallel, 3)
})

test_that("stage_2_parallel_debates validates Stage 1 results before proceeding", {
  inputs <- list(
    texts = c("T1", "T2"),
    analysis_results = list(
      linguistic = "Too Short", # Should be length 2
      domain = c("D1", "D2"),
      social_media = c("S1", "S2")
    )
  )

  # Mock validate_fields but let validate_inputs run
  mockery::stub(stage_2_parallel_debates, "validate_fields", TRUE)

  # validate_inputs should throw error because linguistic length (1) != n (2)
  expect_error(
    stage_2_parallel_debates(inputs, MockChat$new(), verbose = FALSE),
    "Linguistic analysis returned unexpected results",
    fixed = TRUE
  )
})

test_that("stage_2_parallel_debates passes the correct RPM to parallel_chat_text", {
  # Set-up minimal valid inputs
  inputs <- list(
    texts = "T1", targets = "A", target_types = "statement",
    language = "en", scale = "likert",
    prompt_templates = list(t = 1),
    analysis_results = list(
      linguistic = "L1", domain = "D1", social_media = "S1"
    )
  )

  # Mock dependencies
  # mockery::stub(stage_2_parallel_debates, "validate_fields", TRUE)
  # mockery::stub(stage_2_parallel_debates, "validate_inputs", TRUE)
  mockery::stub(stage_2_parallel_debates, "l", "mock stance")
  mockery::stub(
    stage_2_parallel_debates,
    "prepare_debater_chats",
    list(chats = list(MockChat$new()), tasks = "task")
  )

  mock_parallel <- mockery::mock("Pos Result", "Neg Result", "Neu Result")
  mockery::stub(stage_2_parallel_debates, "ellmer::parallel_chat_text", mock_parallel)

  # Execute with custom RPM
  stage_2_parallel_debates(inputs, MockChat$new(), rpm = 42, verbose = FALSE)

  # Verify RPM in the first call to parallel_chat_text
  args <- mockery::mock_args(mock_parallel)[[1]]
  expect_equal(args$rpm, 42)
  expect_equal(args$prompts, "task")
})

test_that("stage_2_parallel_debates correctly localises stances for each branch", {
  # 1. Set-up data
  inputs <- list(
    texts = "T1", targets = "A", target_types = "statement",
    language = "en", scale = "likert",
    prompt_templates = list(t = "file"),
    analysis_results = list(
      linguistic = "L1", domain = "D1", social_media = "S1"
    )
  )

  # 2. Set-up Mocks
  # mockery::stub(stage_2_parallel_debates, "validate_fields", TRUE)
  # mockery::stub(stage_2_parallel_debates, "validate_inputs", TRUE)
  mockery::stub(stage_2_parallel_debates, "tictoc::tic", NULL)
  mockery::stub(stage_2_parallel_debates, "tictoc::toc", NULL)

  # Mocking l(), so that it returns a recognisable marker
  mockery::stub(stage_2_parallel_debates, "l", function(lang, key, scale) {
    paste0("loc_", key)
  })

  # Мокаем prepare_debater_chats, чтобы отследить, какой stance в неё пришел
  mock_prepare <- mockery::mock(
    list(chats = list(MockChat$new()), tasks = "task"), # для positive
    list(chats = list(MockChat$new()), tasks = "task"), # для negative
    list(chats = list(MockChat$new()), tasks = "task")  # для neutral
  )
  mockery::stub(stage_2_parallel_debates, "prepare_debater_chats", mock_prepare)

  # Mock parallel_chat_text to return stance-specific results
  mock_parallel <- mockery::mock(
    "Pos Result", # first call (positive)
    "Neg Result", # second call (negative)
    "Neu Result"  # third call (neutral)
  )
  mockery::stub(stage_2_parallel_debates, "ellmer::parallel_chat_text", mock_parallel)

  # 3. Execute
  stage_2_parallel_debates(inputs, MockChat$new(), verbose = FALSE)

  # 4. Verify
  # Достаем аргументы всех трех вызовов prepare_debater_chats
  mockery::expect_called(mock_prepare, 3)

  prep_args <- mockery::mock_args(mock_prepare)

  # Проверяем, что в каждом вызове аргумент stance был локализован правильно
  expect_equal(prep_args[[1]]$stance, "loc_stance_positive")
  expect_equal(prep_args[[2]]$stance, "loc_stance_negative")
  expect_equal(prep_args[[3]]$stance, "loc_stance_neutral")

  # Также можно проверить, что inputs и chat_base передаются без изменений
  expect_equal(prep_args[[1]]$inputs$language, "en")

  expect_equal(prep_args[[1]]$inputs$scale, "likert")
})

test_that("stage_2_parallel_debates handles empty input texts gracefully", {
  # If n=0, the loops should still work but return empty lists
  inputs <- list(
    texts = character(0), targets = character(0), target_types = character(0),
    language = "en", scale = "likert",
    prompt_templates = list(t = "file"),
    analysis_results = list(
      linguistic = character(0), domain = character(0), social_media = character(0)
    )
  )

  # mockery::stub(stage_2_parallel_debates, "validate_fields", TRUE)
  # mockery::stub(stage_2_parallel_debates, "validate_inputs", TRUE)
  mockery::stub(
    stage_2_parallel_debates,
    "prepare_debater_chats",
    list(chats = list(MockChat$new()), tasks = character(0))
  )
  # Mock parallel_chat_text to return stance-specific results
  mock_parallel <- mockery::mock(character(0), character(0), character(0))
  mockery::stub(stage_2_parallel_debates, "ellmer::parallel_chat_text", mock_parallel)

  result <- stage_2_parallel_debates(inputs, MockChat$new(), verbose = FALSE)

  expect_length(result$debate_results$positive, 0)
  expect_named(result$debate_results, c("positive", "negative", "neutral"))
})

# Reusing the MockChat
MockChat <- R6::R6Class(
  "MockChat",
  public = list(
    system_prompt = NULL,
    set_system_prompt = function(prompt) {
      self$system_prompt <- prompt
    },
    chat = function(..., echo = NULL) paste("Response", seq_along(list(...)))
  )
)

test_that("stage_3_parallel_judgement executes structured chat with correct schema", {
  # 1. Setup Data
  inputs <- list(
    texts = c("T1", "T2"),
    targets = c("A", "B"),
    types = c("statement", "statement"),
    target_types = c("statement", "statement"),
    language = "en",
    scale = "likert",
    prompt_templates = list(scale_description = "Desc"),
    debate_results = list(
      positive = c("P1", "P2"),
      negative = c("N1", "N2"),
      neutral = c("Neu1", "Neu2")
    )
  )

  # 2. Setup Mocks
  # mockery::stub(stage_3_parallel_judgement, "validate_fields", TRUE)
  # mockery::stub(stage_3_parallel_judgement, "validate_inputs", TRUE)
  mockery::stub(stage_3_parallel_judgement, "tictoc::tic", NULL)
  mockery::stub(stage_3_parallel_judgement, "tictoc::toc", NULL)

  # Mock schema generator
  mockery::stub(stage_3_parallel_judgement, "type_stance_analysis", "mock_schema")

  # Mock prepare_judger_chats
  mockery::stub(stage_3_parallel_judgement, "prepare_judger_chats", list(
    chats = list(MockChat$new()),
    tasks = c("Task 1", "Task 2")
  ))

  # Mock parallel_chat_structured
  mock_results <- data.frame(
    stance = c("Strongly Disagree", "Agree"),
    reasoning = c("R1", "R2")
  )
  mock_parallel <- mockery::mock(mock_results)
  mockery::stub(
    stage_3_parallel_judgement,
    "ellmer::parallel_chat_structured",
    mock_parallel
  )

  # 3. Execute
  result <- stage_3_parallel_judgement(
    inputs,
    MockChat$new(),
    verbose = TRUE
  )

  # 4. Verify
  mockery::expect_called(mock_parallel, 1)
  expect_equal(result$judgement_results, mock_results)

  # Verify arguments passed to parallel_chat_structured
  args <- mockery::mock_args(mock_parallel)[[1]]
  expect_equal(args$type, "mock_schema")
  expect_true(args$convert)
})

test_that("stage_3_parallel_judgement warns when NA stances are returned", {
  inputs <- list(
    texts = "T1", targets = "A", types = "statement", target_types = "statement",
    language = "en", scale = "likert", prompt_templates = list(),
    debate_results = list(positive = "P", negative = "N", neutral = "Neu")
  )

  # mockery::stub(stage_3_parallel_judgement, "validate_fields", TRUE)
  # mockery::stub(stage_3_parallel_judgement, "validate_inputs", TRUE)
  mockery::stub(
    stage_3_parallel_judgement,
    "prepare_judger_chats",
    list(chats = list(1), tasks = "T")
  )
  mockery::stub(stage_3_parallel_judgement, "type_stance_analysis", "likert schema")

  # Return a result with NA stance
  mock_results <- data.frame(stance = NA_real_, explanation = "AI has failed")
  mockery::stub(
    stage_3_parallel_judgement,
    "ellmer::parallel_chat_structured",
    mock_results
  )

  # Expect warning from cli::cli_warn
  expect_warning(
    stage_3_parallel_judgement(inputs, MockChat$new(), verbose = FALSE),
    regexp = "1 item returned NA stance",
    fixed = TRUE
  )
})

test_that("stage_3_parallel_judgement passes additional arguments (...) to parallel call", {
  inputs <- list(
    texts = "T1", targets = "A", types = "statement", target_types = "statement",
    language = "en", scale = "likert", prompt_templates = list(),
    debate_results = list(positive = "P", negative = "N", neutral = "Neu")
  )

  # mockery::stub(stage_3_parallel_judgement, "validate_fields", TRUE)
  # mockery::stub(stage_3_parallel_judgement, "validate_inputs", TRUE)
  mockery::stub(stage_3_parallel_judgement, "type_stance_analysis", "likert schema")
  mockery::stub(
    stage_3_parallel_judgement,
    "prepare_judger_chats",
    list(chats = list(1), tasks = "T")
  )

  mock_parallel <- mockery::mock(
    data.frame(stance = "Strongly Agree", explanation = "AI Content Analysis")
  )
  mockery::stub(
    stage_3_parallel_judgement,
    "ellmer::parallel_chat_structured",
    mock_parallel
  )

  # Pass a custom argument like 'max_tokens'
  stage_3_parallel_judgement(
    inputs,
    MockChat$new(),
    verbose = FALSE,
    rpm = 111,
    max_active = 12,
    on_error = "stop"
  )

  args <- mockery::mock_args(mock_parallel)[[1]]
  expect_equal(args$max_active, 12)
  expect_equal(args$on_error, "stop")
  expect_equal(args$rpm, 111)
})
