# WARNING - Generated by {fusen} from dev/flat_stancer.Rmd: do not edit by hand # nolint: line_length_linter.

# Test 1: type_to_term returns correct term for object type
test_that('type_to_term returns object term in English', {
  result <- type_to_term(type = "object", language = "en")
  expect_equal(result, "the object")
})

# Test 2: type_to_term returns correct term for statement type
test_that('type_to_term returns statement term in English', {
  result <- type_to_term(type = "statement", language = "en")
  expect_equal(result, "the following statement:")
})

# Test 3: type_to_term works with Ukrainian language
test_that('type_to_term works with Ukrainian', {
  result <- type_to_term(type = "object", language = "uk")
  expect_equal(result, "об'єкту")
})

# Test 4: type_to_term works with Russian language
test_that('type_to_term works with Russian', {
  result <- type_to_term(type = "statement", language = "ru")
  expect_equal(result, "суждению")
})

# Test 5: type_to_term rejects invalid type
test_that('type_to_term rejects invalid type', {
  expect_error(
    type_to_term(type = "invalid", language = "en"),
    "must be one of",
    fixed = TRUE
  )
})

# Test 6: type_to_term rejects invalid language
test_that('type_to_term rejects invalid language', {
  expect_error(
    type_to_term(type = "object", language = "fr"),
    "must be one of",
    fixed = TRUE
  )
})

# Test 7: type_to_term uses dative case (dat) for all terms
test_that('type_to_term uses dative case', {
  # Проверяем, что используется именно дательный падеж (dat), а не именительный (gen)
  object_dat <- type_to_term(type = "object", language = "en")
  # Для английского "the object" одинаков, но проверяем логику
  expect_type(object_dat, "character")
  expect_length(object_dat, 1)
})

# Test 8: type_to_term returns character string
test_that('type_to_term returns character string', {
  result <- type_to_term(type = "object", language = "en")
  expect_type(result, "character")
  expect_length(result, 1)
})

# Test 9: type_to_term works with all available languages
test_that('type_to_term works with all available languages', {
  available_langs <- stancer_available_languages()

  for (lang in available_langs) {
    result_obj <- type_to_term(type = "object", language = lang)
    result_stmt <- type_to_term(type = "statement", language = lang)

    expect_type(result_obj, "character")
    expect_type(result_stmt, "character")
    expect_length(result_obj, 1)
    expect_length(result_stmt, 1)
  }
})

# Test 10: type_to_term returns different terms for different types
test_that('type_to_term returns different terms for different types', {
  object_term <- type_to_term(type = "object", language = "en")
  statement_term <- type_to_term(type = "statement", language = "en")

  expect_false(object_term == statement_term)
})
