# WARNING - Generated by {fusen} from dev/flat_stancer.Rmd: do not edit by hand # nolint: line_length_linter.

# Reusing and slightly enhancing the MockChat
MockChat <- R6::R6Class(
  "MockChat",
  public = list(
    system_prompt = NULL,
    set_system_prompt = function(prompt) {
      self$system_prompt <- prompt
    }
  )
)

# Set-up common paths for tests
prompts_dir <- system.file('prompts', 'en', package = 'stancer')
if (!dir.exists(prompts_dir)) prompts_dir <- here::here('inst', 'prompts', 'en')

test_that("prepare_expert_chats successfully prepares linguist chats", {
  # 1. Prepare inputs list
  inputs <- list(
    texts = c("Statement 1", "Statement 2"),
    targets = c("Target A", "Target B"),
    target_types = c("statement", "statement"),
    language = "en",
    domain_roles = "linguistic expert",
    prompt_templates = list(
      `system-linguist` = file.path(prompts_dir, 'system-linguist.md'),
      `user-linguist` = file.path(prompts_dir, 'user-linguist.md')
    )
  )

  # Skip if files don't exist in the environment
  skip_if_not(all(file.exists(unlist(inputs$prompt_templates))))

  chat_base <- MockChat$new()

  # 2. Execute
  result <- prepare_expert_chats(inputs, chat_base, "linguist")

  # 3. Verify
  expect_type(result, "list")
  expect_named(result, c("chats", "tasks"))
  expect_length(result$tasks, 2)
  expect_length(result$chats, 1) # Single system prompt case
  expect_match(result$tasks[1], "Statement 1", fixed = TRUE)
  expect_is(result$chats[[1]]$system_prompt, 'character')
})

test_that("prepare_expert_chats successfully prepares domain chats", {
  inputs <- list(
    texts = "Statement about AI",
    targets = "AI",
    target_types = "object",
    language = "en",
    domain_roles = "AI ethics expert",
    prompt_templates = list(
      `system-domain` = file.path(prompts_dir, 'system-domain.md'),
      `user-domain` = file.path(prompts_dir, 'user-domain.md')
    )
  )

  skip_if_not(all(file.exists(unlist(inputs$prompt_templates))))

  chat_base <- MockChat$new()
  result <- prepare_expert_chats(inputs, chat_base, "domain")

  expect_length(result$tasks, 1)
  # Check if domain variable was correctly interpolated in system prompt
  # (Assuming the template uses {domain} placeholder)
  expect_match(result$chats[[1]]$system_prompt, "AI ethics expert", fixed = TRUE)
})

test_that("prepare_expert_chats throws error for invalid role", {
  inputs <- list(texts = "test")
  chat_base <- MockChat$new()

  expect_error(
    prepare_expert_chats(inputs, chat_base, "invalid_role"),
    regexp = "must be one of",
    fixed = TRUE
  )
})

test_that("prepare_expert_chats fails if inputs list is missing required elements", {
  # Missing 'texts' which is used in length(inputs$texts)
  inputs <- list(
    language = "en",
    prompt_templates = list()
  )
  chat_base <- MockChat$new()

  expect_error(prepare_expert_chats(inputs, chat_base, "linguist"))
})

test_that("prepare_expert_chats handles multiple system prompts (if prompts_prepare returns them)", {
  # This tests the logic flow through to tasks_prepare
  inputs <- list(
    texts = c("T1", "T2"),
    targets = c("A", "B"),
    target_types = c("object", "statement"),
    language = "en",
    domain_roles = c("Content analysis expert", "Statistician"), # Multiple roles
    prompt_templates = list(
      `system-domain` = file.path(prompts_dir, 'system-domain.md'),
      `user-domain` = file.path(prompts_dir, 'user-domain.md')
    )
  )

  skip_if_not(all(file.exists(unlist(inputs$prompt_templates))))

  chat_base <- MockChat$new()
  result <- prepare_expert_chats(inputs, chat_base, "domain")

  # If prompts_prepare returns 2 system prompts, tasks_prepare should return 2 chats
  # Note: This depends on how prompts_prepare handles vectorised 'domain'
  expect_named(result, c("chats", "tasks"))
  expect_type(result$chats, "list")
  expect_length(result$tasks, 2)
  expect_length(result$chats, 2)
  expect_is(result$chats[[1]]$system_prompt, 'character')
  expect_is(result$chats[[2]]$system_prompt, 'character')
  expect_match(
    result$chats[[1]]$system_prompt,
    "Content analysis expert",
    fixed = TRUE
  )
  expect_match(
    result$chats[[2]]$system_prompt,
    "Statistician",
    fixed = TRUE
  )
})

# Reusing the MockChat
MockChat <- R6::R6Class(
  "MockChat",
  public = list(
    system_prompt = NULL,
    set_system_prompt = function(prompt) {
      self$system_prompt <- prompt
    },
    chat = function(..., echo = NULL) paste("Response", seq_along(list(...)))
  )
)

test_that("execute_role uses parallel execution when there is one chat object", {
  # 1. Set-up Mocks
  mockery::stub(
    execute_role,
    "prepare_expert_chats",
    list(
      chats = list(MockChat$new()), # Only 1 chat -> parallel
      tasks = c("Content Analysis Prompt 1", "Content Analysis Prompt 2")
    )
  )

  mock_parallel <- mockery::mock(c("Response A", "Response B"))
  mockery::stub(execute_role, "ellmer::parallel_chat_text", mock_parallel)

  inputs <- list(texts = c("T1", "T2"))

  # 2. Execute
  res <- execute_role(
    "linguist", inputs, MockChat$new(), "Testing Parallel", verbose = FALSE
  )

  # 3. Verify
  expect_equal(res, c("Response A", "Response B"))
  mockery::expect_called(mock_parallel, 1)
  # Check arguments passed to parallel_chat_text
  args <- mockery::mock_args(mock_parallel)[[1]]
  expect_equal(
    args$prompts,
    c("Content Analysis Prompt 1", "Content Analysis Prompt 2")
  )
})

test_that("execute_role uses sequential execution when there are multiple chats", {
  # 1. Set-up Mocks
  chat1 <- MockChat$new()
  chat2 <- MockChat$new()

  mockery::stub(
    execute_role,
    "prepare_expert_chats",
    list(
      chats = list(chat1, chat2), # 2 chats -> sequential
      tasks = c("Task 1", "Task 2")
    )
  )

  inputs <- list(texts = c("T1", "T2"))

  # 2. Execute
  res <- execute_role(
    "domain", inputs, MockChat$new(), "Testing Sequential", verbose = FALSE
  )

  # 3. Verify
  expect_equal(res, c("Response 1", "Response 1"))
  # For every Chat, there is only one response
})

test_that("execute_role throws error if output length is mismatched", {
  mockery::stub(
    execute_role,
    "prepare_expert_chats",
    list(chats = list(MockChat$new()), tasks = c("P1", "P2"))
  )

  # Parallel returns only 1 response for 2 inputs
  mockery::stub(execute_role, "ellmer::parallel_chat_text", "Single Response")

  inputs <- list(texts = c("T1", "T2"))

  expect_error(
    execute_role("linguist", inputs, MockChat$new(), "Error Test", verbose = FALSE),
    regexp = "Input and output lengths differ",
    fixed = TRUE
  )
})

test_that("execute_role prints progress message when verbose is TRUE", {
  mockery::stub(
    execute_role,
    "prepare_expert_chats",
    list(chats = list(MockChat$new()), tasks = "P1")
  )
  mockery::stub(execute_role, "ellmer::parallel_chat_text", "Result A")

  expect_output(
    execute_role(
      "linguist", list(texts = "T1"), MockChat$new(), "MyInfo", verbose = TRUE
    ),
    regexp = "MyInfo..."
  )
})

test_that("execute_role throws error on unexpected chat response", {
  # 1. Set-up Mocks
  # MockChat, but it returns wrong values
  MockChatNumeric <- R6::R6Class(
    "MockChatNumeric",
    public = list(
      system_prompt = NULL,
      set_system_prompt = function(prompt) {
        self$system_prompt <- prompt
      },
      chat = function(..., echo = NULL) seq_along(list(...))
    )
  )
  
  mockery::stub(
    execute_role,
    "prepare_expert_chats",
    list(
      # Multiple chats - sequential execution
      chats = list(MockChatNumeric$new(), MockChatNumeric$new()),
      tasks = c("Content Analysis 1", "Content Analysis 2")
    )
  )
  inputs <- list(texts = c("T1", "T2"))
  
  # 2. Execute and Expect Error
  execute_role(
    "linguist",
    inputs,
    MockChat$new(),
    "Testing Chat Output",
    verbose = TRUE
  ) |>
    expect_error(
      "Unexpected results in",
      fixed = TRUE
    )
})

# Reusing the MockChat
MockChat <- R6::R6Class(
  "MockChat",
  public = list(
    system_prompt = NULL,
    set_system_prompt = function(prompt) {
      self$system_prompt <- prompt
    },
    chat = function(..., echo = NULL) paste("Response", seq_along(list(...)))
  )
)

test_that("prepare_debater_chats correctly passes Stage 1 results to prompts_prepare", {
  # 1. Set-up Data
  inputs <- list(
    texts = "Text 1",
    targets = "Target 1",
    target_types = "statement",
    language = "en",
    prompt_templates = list(t = "inst/prompts"),
    analysis_results = list(
      linguistic = "Linguistic Analysis",
      domain = "Domain Expert Analysis",
      social_media = "Social Media Analysis"
    )
  )

  # 2. Mock prompts_prepare to verify arguments
  mock_prompts <- mockery::mock(list(
    system = "System Prompt",
    user = "User Prompt"
  ))
  mockery::stub(prepare_debater_chats, "prompts_prepare", mock_prompts)

  # Mock tasks_prepare to return a standard structure
  mockery::stub(prepare_debater_chats, "tasks_prepare", list(chats = list(1), tasks = "T"))

  # 3. Execute
  prepare_debater_chats("negative", inputs, MockChat$new())

  # 4. Verify arguments passed to prompts_prepare
  args <- mockery::mock_args(mock_prompts)[[1]]
  expect_equal(args[[1]], "debater")
  expect_equal(args$stance, "negative")
  expect_equal(args$LingResponse, "Linguistic Analysis")
  expect_equal(args$ExpertResponse, "Domain Expert Analysis")
  expect_equal(args$UserResponse, "Social Media Analysis")
})

test_that("prepare_debater_chats aborts if multiple system prompts are generated", {
  # Mock prompts_prepare to return 2 system prompts
  mockery::stub(prepare_debater_chats, "prompts_prepare", list(
    system = c("System 1", "System 2"),
    user = c("User 1", "User 2")
  ))

  inputs <- list(texts = c("T1", "T2"), analysis_results = list())

  # Check for our custom abort message
  expect_error(
    prepare_debater_chats("con", inputs, MockChat$new()),
    regexp = "Multiple system prompts are not allowed at stage 2"
  )
})

test_that("prepare_debater_chats returns tasks_prepare output on success", {
  mockery::stub(prepare_debater_chats, "prompts_prepare", list(
    system = "Single System",
    user = "User Prompt"
  ))

  expected_output <- list(chats = list("MockChatObject"), tasks = "Final Prompt")
  mockery::stub(prepare_debater_chats, "tasks_prepare", expected_output)

  res <- prepare_debater_chats("neutral", list(texts = "T1"), MockChat$new())
  expect_equal(res, expected_output)
})

test_that("prepare_debater_chats fails with multiple system prompts", {
  mockery::stub(prepare_debater_chats, "prompts_prepare", list(
    system = c("System Prompt 1", "System Prompt 2"),
    user = "User Prompt"
  ))

  expect_error(
    prepare_debater_chats("positive", list(texts = "T1"), MockChat$new()),
    "Multiple system prompts are not allowed at stage 2",
    fixed = TRUE
  )
})

# Reusing the MockChat
MockChat <- R6::R6Class(
  "MockChat",
  public = list(
    system_prompt = NULL,
    set_system_prompt = function(prompt) {
      self$system_prompt <- prompt
    },
    chat = function(..., echo = NULL) paste("Response", seq_along(list(...)))
  )
)

test_that("prepare_judger_chats correctly passes Stage 2 results and flags", {
  # 1. Set-up Data
  inputs <- list(
    texts = "Text 1",
    targets = "Target 1",
    target_types = "statement",
    language = "en",
    types = c("statement"), # Should trigger add_reference_resolution
    prompt_templates = list(t = "file"),
    debate_results = list(
      positive = "Pos Debate",
      negative = "Neg Debate",
      neutral = "Neu Debate"
    )
  )

  # 2. Mock prompts_prepare to verify arguments
  mock_prompts <- mockery::mock(
    list(
      system = "System Prompt",
      user = "User Prompt"
    )
  )
  mockery::stub(prepare_judger_chats, "prompts_prepare", mock_prompts)
  mockery::stub(
    prepare_judger_chats,
    "tasks_prepare",
    list(chats = list(1), tasks = "T")
  )

  # 3. Execute
  prepare_judger_chats(inputs, MockChat$new())

  # 4. Verify arguments passed to prompts_prepare
  mockery::expect_called(mock_prompts, 1)
  args <- mockery::mock_args(mock_prompts)[[1]]
  expect_equal(args[[1]], "judger")
  expect_equal(args$target_type, "statement")
  expect_equal(args$FavourResponse, "Pos Debate")
  expect_equal(args$AgainstResponse, "Neg Debate")
  expect_equal(args$NeutralResponse, "Neu Debate")

  # Verify conditional flags
  expect_false(args$add_reference_resolution)
  expect_true(args$add_statement_resolution)
})

test_that("prepare_judger_chats aborts if multiple system prompts are generated", {
  mockery::stub(prepare_judger_chats, "prompts_prepare", list(
    system = c("Sys 1", "Sys 2"),
    user = c("User 1", "User 2")
  ))

  inputs <- list(texts = c("T1", "T2"), types = "statement", debate_results = list())

  expect_error(
    prepare_judger_chats(inputs, MockChat$new()),
    regexp = "Multiple system prompts are not allowed at stage 3",
    fixed = TRUE
  )
})

test_that("prepare_judger_chats correctly handles statement resolution flag", {
  inputs <- list(
    texts = "T1", targets = "A", target_types = "statement", language = "en",
    types = "statement", # Should trigger add_statement_resolution
    prompt_templates = list(),
    debate_results = list(positive = "P", negative = "N", neutral = "Neu")
  )

  mock_prompts <- mockery::mock(list(system = "S", user = "U"))
  mockery::stub(prepare_judger_chats, "prompts_prepare", mock_prompts)
  mockery::stub(prepare_judger_chats, "tasks_prepare", list())

  prepare_judger_chats(inputs, MockChat$new())

  mockery::expect_called(mock_prompts, 1)
  args <- mockery::mock_args(mock_prompts)[[1]]
  expect_false(args$add_reference_resolution)
  expect_true(args$add_statement_resolution)
})
