# WARNING - Generated by {fusen} from dev/flat_stancer.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("templates_collect handles different scale types correctly", {
  sys_dir <- withr::local_tempdir()

  # Create files for a 'likert' scale
  file.create(file.path(sys_dir, "description-likert.md"))
  file.create(file.path(sys_dir, "guide-likert.md"))
  file.create(file.path(sys_dir, "reference-resolution.md"))
  file.create(file.path(sys_dir, "statement-resolution.md"))

  # Create all other required role files
  roles <- c("system-linguist", "user-linguist", "system-domain", "user-domain",
             "system-interpreter", "user-interpreter", "system-debater",
             "user-debater", "system-judger", "user-judger")
  for (r in roles) file.create(file.path(sys_dir, paste0(r, ".md")))

  mockery::stub(templates_collect, "system.file", sys_dir)
  mockery::stub(templates_collect, "dir.exists", TRUE)

  # Test Likert
  res_likert <- templates_collect(NULL, "en", "likert")
  expect_match(res_likert$scale_description, "description-likert.md", fixed = TRUE)
  expect_match(res_likert$scale_guide, "guide-likert.md", fixed = TRUE)

  # Test Numeric (should fail if files don't exist)
  expect_error(
    templates_collect(NULL, "en", "numeric"),
    regexp = "not found",
  )
})

test_that("templates_collect prioritises user directory over system directory", {
  sys_dir <- withr::local_tempdir(pattern = "default")
  user_dir <- withr::local_tempdir(pattern = "custom")

  # Create a file in both
  file.create(file.path(sys_dir, "system-judger.md"))
  file.create(file.path(user_dir, "system-judger.md"))

  # Create all other required files in sys_dir to satisfy the loop
  all_files <- c(
    "description-categorical.md", "guide-categorical.md",
    "reference-resolution.md", "statement-resolution.md",
    "system-linguist.md", "user-linguist.md", "system-domain.md", "user-domain.md",
    "system-interpreter.md", "user-interpreter.md", "system-debater.md",
    "user-debater.md", "user-judger.md"
  )
  for (f in all_files) file.create(file.path(sys_dir, f))

  mockery::stub(templates_collect, "system.file", sys_dir)
  mockery::stub(templates_collect, "dir.exists", TRUE)

  res <- templates_collect(
    prompts_dir = user_dir,
    language = "en",
    scale = "categorical"
  )

  # User file should be selected
  expect_match(res$`system-judger`, user_dir, fixed = TRUE)
  # Other files should still come from sys_dir
  expect_match(res$scale_description, sys_dir, fixed = TRUE)
})

test_that("templates_collect throws error if no folders found", {
  user_dir <- withr::local_tempdir(pattern = "custom")

  mockery::stub(templates_collect, "length", 0)

  expect_error(
    templates_collect(
      prompts_dir = user_dir, language = "en", scale = "likert"
    ),
    "No prompt directories found",
    fixed = TRUE
  )
})

# Set-up common paths for tests
prompts_dir <- system.file('prompts', 'en', package = 'stancer')
if (!dir.exists(prompts_dir)) prompts_dir <- here::here('inst', 'prompts', 'en')

test_that('prompts_prepare returns list with system and task', {
  templates <- list(
    `system-linguist` = file.path(prompts_dir, 'system-linguist.md'),
    `user-linguist` = file.path(prompts_dir, 'user-linguist.md')
  )
  skip_if_not(all(file.exists(unlist(templates))))

  result <- prompts_prepare(
    role = "linguist",
    templates = templates,
    language = "en",
    target = "climate change",
    text = c("some text", "and more"),
    target_type = "the object"
  )

  expect_type(result, "list")
  expect_named(result, c("system", "task"))
})

test_that('prompts_prepare returns non-empty strings', {
  templates <- list(
    `system-linguist` = file.path(prompts_dir, 'system-linguist.md'),
    `user-linguist` = file.path(prompts_dir, 'user-linguist.md')
  )
  skip_if_not(all(file.exists(unlist(templates))))

  result <- prompts_prepare(
    role = "linguist",
    templates = templates,
    language = "en",
    target = "climate change",
    text = c("some text", "and more"),
    target_type = "the object"
  )

  expect_type(result$system, "character")
  expect_type(result$task, "character")
  expect_true(nchar(result$system) > 0)
  expect_true(all(nchar(result$task) > 0))
})

test_that('prompts_prepare works with character vector for text', {
  templates <- list(
    `system-linguist` = file.path(prompts_dir, 'system-linguist.md'),
    `user-linguist` = file.path(prompts_dir, 'user-linguist.md')
  )
  skip_if_not(all(file.exists(unlist(templates))))

  texts <- c("some text", "and more")

  result <- prompts_prepare(
    role = "linguist",
    templates = templates,
    language = "en",
    target = "climate change",
    text = texts,
    target_type = "the object"
  )

  expect_type(result, "list")
  expect_length(result$system, 1)
  expect_length(result$task, length(texts))
})

test_that('prompts_prepare works with all valid roles', {
  roles <- c('linguist', 'domain', 'interpreter', 'debater', 'judger')

  templates <- list(
    `system-linguist` = file.path(prompts_dir, 'system-linguist.md'),
    `user-linguist` = file.path(prompts_dir, 'user-linguist.md'),
    `system-domain` = file.path(prompts_dir, 'system-domain.md'),
    `user-domain` = file.path(prompts_dir, 'user-domain.md'),
    `system-interpreter` = file.path(prompts_dir, 'system-interpreter.md'),
    `user-interpreter` = file.path(prompts_dir, 'user-interpreter.md'),
    `system-debater` = file.path(prompts_dir, 'system-debater.md'),
    `user-debater` = file.path(prompts_dir, 'user-debater.md'),
    `system-judger` = file.path(prompts_dir, 'system-judger.md'),
    `user-judger` = file.path(prompts_dir, 'user-judger.md'),
    reference_resolution = file.path(prompts_dir, 'reference-resolution.md'),
    statement_resolution = file.path(prompts_dir, 'statement-resolution.md'),
    scale_guide = file.path(prompts_dir, 'guide-likert.md')
  )
  skip_if_not(all(file.exists(unlist(templates))))

  texts <- c("some text", "and more")

  for (r in roles) {
    result <- prompts_prepare(
      role = r,
      templates = templates,
      language = "en",
      target = "climate change",
      text = texts,
      target_type = "the object",
      domain = "content analysis expert",
      stance = "neutral",
      LingResponse = "This is just a placeholder phrase",
      ExpertResponse = "Just a dummy text document with no much sense",
      UserResponse = "Every second real tweet be like",
      FavourResponse = "I have a feeling it is positive",
      AgainstResponse = "Most likely, this is some kind of malicious mockery",
      NeutralResponse = "Context is missing and we should be sceptical"
    )

    expect_type(result, "list")
    expect_named(result, c("system", "task"))
    expect_type(result$system, "character")
    expect_type(result$task, "character")
    expect_length(result$system, 1)
    expect_length(result$task, length(texts))
    expect_true(nchar(result$system) > 0)
    expect_true(all(nchar(result$task) > 0))
  }
})

test_that('prompts_prepare rejects invalid role', {
  templates <- list(
    `system-linguist` = file.path(prompts_dir, 'system-linguist.md'),
    `user-linguist` = file.path(prompts_dir, 'user-linguist.md')
  )
  skip_if_not(all(file.exists(unlist(templates))))

  expect_error(
    prompts_prepare(
      role = "invalid_role",
      templates = templates,
      language = "en",
      target = "climate change",
      text = c("some text", "and more"),
      target_type = "the object"
    ),
    "must be one of",
    fixed = TRUE
  )
})

test_that('prompts_prepare rejects invalid language', {
  templates <- list(
    `system-linguist` = file.path(prompts_dir, 'system-linguist.md'),
    `user-linguist` = file.path(prompts_dir, 'user-linguist.md')
  )
  skip_if_not(all(file.exists(unlist(templates))))

  expect_error(
    prompts_prepare(
      role = "linguist",
      templates = templates,
      language = "fr",
      target = "climate change",
      text = c("some text", "and more"),
      target_type = "the object"
    ),
    "must be one of",
    fixed = TRUE
  )
})

test_that('prompts_prepare handles missing system template', {
  templates <- list(
    `system-linguist` = file.path(prompts_dir, 'nonexistent-system.md'),
    `user-linguist` = file.path(prompts_dir, 'user-linguist.md')
  )
  skip_if(file.exists(templates$`system-linguist`))

  expect_error(
    prompts_prepare(
      role = "linguist",
      templates = templates,
      language = "en",
      target = "climate change",
      text = c("some text", "and more"),
      target_type = "the object"
    ),
    "System template not found",
    fixed = TRUE
  )
})

test_that('prompts_prepare handles missing user template', {
  templates <- list(
    `system-linguist` = file.path(prompts_dir, 'system-linguist.md'),
    `user-linguist` = file.path(prompts_dir, 'nonexistent-user.md')
  )
  skip_if(file.exists(templates$`user-linguist`))

  expect_error(
    prompts_prepare(
      role = "linguist",
      templates = templates,
      language = "en",
      target = "climate change",
      text = c("some text", "and more"),
      target_type = "the object"
    ),
    "User template not found",
    fixed = TRUE
  )
})

test_that('prompts_prepare works with domain role and domain parameter', {
  templates <- list(
    `system-domain` = file.path(prompts_dir, 'system-domain.md'),
    `user-domain` = file.path(prompts_dir, 'user-domain.md')
  )
  skip_if_not(all(file.exists(unlist(templates))))

  result <- prompts_prepare(
    role = "domain",
    templates = templates,
    language = "en",
    target = "artificial intelligence",
    text = "AI will replace all human jobs",
    target_type = "the object",
    domain = "technology and employment expert"
  )

  expect_type(result, "list")
  expect_true(nchar(result$system) > 0)
  expect_true(nchar(result$task) > 0)
})

test_that('prompts_prepare works with judger role and no additional options', {
  templates <- list(
    `system-judger` = file.path(prompts_dir, 'system-judger.md'),
    `user-judger` = file.path(prompts_dir, 'user-judger.md'),
    reference_resolution = file.path(prompts_dir, 'reference-resolution.md'),
    statement_resolution = file.path(prompts_dir, 'statement-resolution.md'),
    scale_guide = file.path(prompts_dir, 'guide-likert.md')
  )
  skip_if_not(all(file.exists(unlist(templates))))

  texts <- c("some text", "and more")

  result <- prompts_prepare(
    role = "judger",
    templates = templates,
    language = "en",
    add_reference_resolution = FALSE,
    add_statement_resolution = FALSE,
    target = "content analysis",
    text = texts,
    target_type = "the object",
    FavourResponse = "I have a feeling it is positive",
    AgainstResponse = "Most likely, this is some kind of malicious mockery",
    NeutralResponse = "Context is missing and we should be sceptical"
  )

  expect_type(result, "list")
  expect_true(nchar(result$system) > 0)
  expect_true(all(nchar(result$task) > 0))
  expect_length(result$system, 1)
  expect_length(result$task, length(texts))
  expect_no_match(result$system, "reference_instruction")
  expect_no_match(result$system, "statement_instruction")
  expect_no_match(result$system, "Resolve a reference if")
  expect_no_match(result$system, "Rules for Statements")
})

test_that('prompts_prepare works with judger role and reference resolution', {
  templates <- list(
    `system-judger` = file.path(prompts_dir, 'system-judger.md'),
    `user-judger` = file.path(prompts_dir, 'user-judger.md'),
    reference_resolution = file.path(prompts_dir, 'reference-resolution.md'),
    statement_resolution = file.path(prompts_dir, 'statement-resolution.md'),
    scale_guide = file.path(prompts_dir, 'guide-likert.md')
  )
  skip_if_not(all(file.exists(unlist(templates))))

  texts <- c("some text", "and more")

  result <- prompts_prepare(
    role = "judger",
    templates = templates,
    language = "en",
    add_reference_resolution = TRUE,
    add_statement_resolution = FALSE,
    target = "content analysis",
    text = texts,
    target_type = "the object",
    FavourResponse = "I have a feeling it is positive",
    AgainstResponse = "Most likely, this is some kind of malicious mockery",
    NeutralResponse = "Context is missing and we should be sceptical"
  )

  expect_type(result, "list")
  expect_true(nchar(result$system) > 0)
  expect_true(all(nchar(result$task) > 0))
  expect_length(result$system, 1)
  expect_length(result$task, length(texts))
  expect_no_match(result$system, "reference_instruction")
  expect_no_match(result$system, "statement_instruction")
  expect_match(result$system, "Resolve a reference if")
  expect_no_match(result$system, "Rules for Statements")
})

test_that('prompts_prepare works with judger role and statement resolution', {
  templates <- list(
    `system-judger` = file.path(prompts_dir, 'system-judger.md'),
    `user-judger` = file.path(prompts_dir, 'user-judger.md'),
    reference_resolution = file.path(prompts_dir, 'reference-resolution.md'),
    statement_resolution = file.path(prompts_dir, 'statement-resolution.md'),
    scale_guide = file.path(prompts_dir, 'guide-likert.md')
  )
  skip_if_not(all(file.exists(unlist(templates))))

  texts <- c("some text", "and more")

  result <- prompts_prepare(
    role = "judger",
    templates = templates,
    language = "en",
    add_reference_resolution = FALSE,
    add_statement_resolution = TRUE,
    target = "content analysis",
    text = texts,
    target_type = "the object",
    FavourResponse = "I have a feeling it is positive",
    AgainstResponse = "Most likely, this is some kind of malicious mockery",
    NeutralResponse = "Context is missing and we should be sceptical"
  )

  expect_type(result, "list")
  expect_true(nchar(result$system) > 0)
  expect_true(all(nchar(result$task) > 0))
  expect_length(result$system, 1)
  expect_length(result$task, length(texts))
  expect_no_match(result$system, "reference_instruction")
  expect_no_match(result$system, "statement_instruction")
  expect_no_match(result$system, "Resolve a reference if")
  expect_match(result$system, "Rules for Statements")
})

test_that('prompts_prepare works with judger role and both options', {
  templates <- list(
    `system-judger` = file.path(prompts_dir, 'system-judger.md'),
    `user-judger` = file.path(prompts_dir, 'user-judger.md'),
    reference_resolution = file.path(prompts_dir, 'reference-resolution.md'),
    statement_resolution = file.path(prompts_dir, 'statement-resolution.md'),
    scale_guide = file.path(prompts_dir, 'guide-likert.md')
  )
  skip_if_not(all(file.exists(unlist(templates))))

  texts <- c("some text", "and more")

  result <- prompts_prepare(
    role = "judger",
    templates = templates,
    language = "en",
    add_reference_resolution = TRUE,
    add_statement_resolution = TRUE,
    target = "content analysis",
    text = texts,
    target_type = "the object",
    FavourResponse = "I have a feeling it is positive",
    AgainstResponse = "Most likely, this is some kind of malicious mockery",
    NeutralResponse = "Context is missing and we should be sceptical"
  )

  expect_type(result, "list")
  expect_true(nchar(result$system) > 0)
  expect_true(all(nchar(result$task) > 0))
  expect_length(result$system, 1)
  expect_length(result$task, length(texts))
  expect_no_match(result$system, "reference_instruction")
  expect_no_match(result$system, "statement_instruction")
  expect_match(result$system, "Resolve a reference if")
  expect_match(result$system, "Rules for Statements")
})

test_that('prompts_prepare returns consistent results for same inputs', {
  templates <- list(
    `system-linguist` = file.path(prompts_dir, 'system-linguist.md'),
    `user-linguist` = file.path(prompts_dir, 'user-linguist.md')
  )
  skip_if_not(all(file.exists(unlist(templates))))

  result1 <- prompts_prepare(
    role = "linguist",
    templates = templates,
    language = "en",
    target = "content analysis",
    text = c("some text", "and more"),
    target_type = "the object"
  )
  result2 <- prompts_prepare(
    role = "linguist",
    templates = templates,
    language = "en",
    target = "content analysis",
    text = c("some text", "and more"),
    target_type = "the object"
  )

  expect_identical(result1$system, result2$system)
  expect_identical(result1$task, result2$task)
})

test_that('prompts_prepare produces different results for different target', {
  templates <- list(
    `system-linguist` = file.path(prompts_dir, 'system-linguist.md'),
    `user-linguist` = file.path(prompts_dir, 'user-linguist.md')
  )
  skip_if_not(all(file.exists(unlist(templates))))

  result1 <- prompts_prepare(
    role = "linguist",
    templates = templates,
    language = "en",
    target = "climate change",
    text = c("some text", "and more"),
    target_type = "the object"
  )
  result2 <- prompts_prepare(
    role = "linguist",
    templates = templates,
    language = "en",
    target = "artificial intelligence",
    text = c("some text", "and more"),
    target_type = "the object"
  )

  expect_identical(result1$system, result2$system)
  expect_disjoint(result1$task, result2$task)
})

test_that('prompts_prepare fails with empty user prompt', {
  templates <- list(
    `system-judger` = file.path(prompts_dir, 'system-judger.md'),
    `user-judger` = file.path(prompts_dir, 'user-judger.md')
  )
  skip_if_not(all(file.exists(unlist(templates))))

  texts <- c("content analysis", "text mining")

  mockery::stub(prompts_prepare, "ellmer::interpolate_file", NULL)
  prompts_prepare(
    role = "judger",
    templates = templates,
    language = "en",
    add_reference_resolution = TRUE,
    add_statement_resolution = TRUE,
    target = "content analysis",
    text = texts
  ) |>
    expect_error("User prompt is NULL", fixed = TRUE)
})

test_that('prompts_prepare fails with empty strings', {
  templates <- list(
    `system-linguist` = file.path(prompts_dir, 'system-linguist.md'),
    `user-linguist` = file.path(prompts_dir, 'user-linguist.md')
  )
  skip_if_not(all(file.exists(unlist(templates))))

  texts <- c("content analysis", "text mining")

  m <- mockery::mock("System prompt", "")
  mockery::stub(prompts_prepare, "ellmer::interpolate_file", m)
  prompts_prepare(
    role = "linguist",
    templates = templates,
    language = "en",
    target = "content analysis",
    text = texts
  ) |>
    expect_error("User prompt is empty", fixed = TRUE)
  
  m <- mockery::mock("", "User prompt")
  mockery::stub(prompts_prepare, "ellmer::interpolate_file", m)
  prompts_prepare(
    role = "linguist",
    templates = templates,
    language = "en",
    target = "content analysis",
    text = texts
  ) |>
    expect_error("System prompt is empty", fixed = TRUE)
})

test_that("tasks_validate returns invisible TRUE on valid input", {
  tasks <- c("Content analysis task 1", "Content analysis task 2")
  expect_true(tasks_validate(tasks, 2))
  expect_invisible(tasks_validate(tasks, 2))
})

test_that("tasks_validate throws error on incorrect length", {
  tasks <- c("Content analysis task 1", "Content analysis task 2")
  expect_error(
    tasks_validate(tasks, 3),
    "User prompt interpolation returned unexpected results",
    fixed = TRUE
  )

  expect_error(
    tasks_validate(tasks, 1),
    "User prompt interpolation returned unexpected results",
    fixed = TRUE
  )
})

test_that("tasks_validate throws error if tasks is not character", {
  expect_error(
    tasks_validate(list("Content analysis task 1", "Content analysis task 2"), 2),
    "User prompt interpolation returned unexpected results",
    fixed = TRUE
  )

  expect_error(
    tasks_validate(c(1, 2), 2),
    "User prompt interpolation returned unexpected results",
    fixed = TRUE
  )
})

test_that("tasks_validate throws error on empty strings", {
  tasks_with_empty <- c("Valid task", "")
  expect_error(
    tasks_validate(tasks_with_empty, 2),
    "User prompt is empty after interpolation",
    fixed = TRUE
  )
})

test_that("tasks_validate throws error on NA values", {
  # nchar(NA) is NA, which fails the if(any(nchar...)) check or behaves unexpectedly
  tasks_with_na <- c("Valid task", NA_character_)
  expect_error(
    tasks_validate(tasks_with_na, 2),
    "contains missing",
    fixed = TRUE
  )
})

test_that("tasks_validate works with single task", {
  expect_true(tasks_validate("Single task", 1))
})

test_that("tasks_validate rejects zero length expectation", {
  expect_error(tasks_validate(character(0), 0), "Wrong", fixed = TRUE)
})

test_that("tasks_validate rejects fractional `expected_length`", {
  expect_error(tasks_validate("A task", 1.5), "Wrong", fixed = TRUE)
})

# Mocking a Chat object for testing
MockChat <- R6::R6Class(
  "MockChat",
  public = list(
    system_prompt = NULL,
    set_system_prompt = function(prompt) {
      self$system_prompt <- prompt
    }
  )
)

test_that("tasks_prepare returns correct structure for single system prompt", {
  chat_base <- MockChat$new()
  prompts <- list(
    system = "System Instructions",
    task = c("Task 1", "Task 2", "Task 3")
  )
  n_texts <- 3

  result <- tasks_prepare(chat_base, prompts, n_texts)

  expect_type(result, "list")
  expect_named(result, c("chats", "tasks"))
  expect_length(result$chats, 1)
  expect_length(result$tasks, 3)
  expect_equal(result$chats[[1]]$system_prompt, "System Instructions")
})

test_that("tasks_prepare returns correct structure for multiple system prompts", {
  chat_base <- MockChat$new()
  prompts <- list(
    system = c("System 1", "System 2"),
    task = c("Task 1", "Task 2")
  )
  n_texts <- 2

  result <- tasks_prepare(chat_base, prompts, n_texts)

  expect_named(result, c("chats", "tasks"))
  expect_length(result$chats, 2)
  expect_equal(result$chats[[1]]$system_prompt, "System 1")
  expect_equal(result$chats[[2]]$system_prompt, "System 2")
})

test_that("tasks_prepare throws error on mismatched system prompt length", {
  chat_base <- MockChat$new()
  # 2 system prompts for 3 texts is invalid (must be 1 or n_texts)
  prompts <- list(
    system = c("System 1", "System 2"),
    task = c("Task 1", "Task 2", "Task 3")
  )
  n_texts <- 3

  expect_error(
    tasks_prepare(chat_base, prompts, n_texts),
    regexp = "Length of system and user prompts must match 3",
    fixed = FALSE
  )
})

test_that("tasks_prepare validates user tasks using tasks_validate", {
  chat_base <- MockChat$new()
  # Empty task should trigger tasks_validate error
  prompts <- list(
    system = "System",
    task = c("Task 1", "")
  )
  n_texts <- 2

  expect_error(
    tasks_prepare(chat_base, prompts, n_texts),
    regexp = "User prompt is empty after interpolation",
    fixed = TRUE
  )
})

test_that("tasks_prepare clones the base chat deeply", {
  chat_base <- MockChat$new()
  chat_base$system_prompt <- "Original"

  prompts <- list(
    system = "New System",
    task = "Task 1"
  )

  result <- tasks_prepare(chat_base, prompts, 1)

  # Check that the clone has the new prompt but the base remains unchanged
  expect_equal(result$chats[[1]]$system_prompt, "New System")
  expect_equal(chat_base$system_prompt, "Original")
  # Verify they are different objects
  expect_false(identical(chat_base, result$chats[[1]]))
})
