# WARNING - Generated by {fusen} from dev/flat_stancer.Rmd: do not edit by hand # nolint: line_length_linter.

# Test 1: Basic functionality - values within range
test_that('truncate returns values unchanged when within range', {
  expect_equal(truncate(3, a = 0, b = 5), 3)
  expect_equal(truncate(c(1, 2, 3), a = 0, b = 5), c(1, 2, 3))
})

# Test 2: Values below lower bound
test_that('truncate sets values below a to a', {
  expect_equal(truncate(-1, a = 0, b = 5), 0)
  expect_equal(truncate(c(-5, -1, 0), a = 0, b = 5), c(0, 0, 0))
})

# Test 3: Values above upper bound
test_that('truncate sets values above b to b', {
  expect_equal(truncate(10, a = 0, b = 5), 5)
  expect_equal(truncate(c(5, 6, 10), a = 0, b = 5), c(5, 5, 5))
})

# Test 4: Mixed values (below, within, above)
test_that('truncate handles mixed values correctly', {
  expect_equal(
    truncate(c(-1, 0, 3, 5, 10), a = 0, b = 5),
    c(0, 0, 3, 5, 5)
  )
})

# Test 5: Negative ranges
test_that('truncate works with negative ranges', {
  expect_equal(truncate(c(-10, -5, 0), a = -8, b = -2), c(-8, -5, -2))
})

# Test 6: Single value at boundaries
test_that('truncate handles boundary values', {
  expect_equal(truncate(0, a = 0, b = 5), 0)
  expect_equal(truncate(5, a = 0, b = 5), 5)
})

# Test 7: Vectorized operation
test_that('truncate is vectorized', {
  x <- c(-10, -5, 0, 5, 10, 15)
  result <- truncate(x, a = 0, b = 10)
  expect_equal(result, c(0, 0, 0, 5, 10, 10))
})

# Test 8: Floating point values
test_that('truncate works with floating point numbers', {
  expect_equal(truncate(3.5, a = 0, b = 5), 3.5)
  expect_equal(truncate(-0.5, a = 0, b = 5), 0)
  expect_equal(truncate(5.5, a = 0, b = 5), 5)
})

# Test 9: Very large and very small numbers
test_that('truncate handles extreme values', {
  expect_equal(truncate(1e10, a = 0, b = 100), 100)
  expect_equal(truncate(-1e10, a = 0, b = 100), 0)
})

# Test 10: Zero as bound
test_that('truncate works with zero as bound', {
  expect_equal(truncate(c(-5, 0, 5), a = 0, b = 10), c(0, 0, 5))
  expect_equal(truncate(c(-5, 0, 5), a = -10, b = 0), c(-5, 0, 0))
})

# Test 11: Equal bounds (a == b)
test_that('truncate works when a equals b', {
  expect_equal(truncate(c(-5, 0, 5), a = 3, b = 3), c(3, 3, 3))
})

# Test 12: Reversed bounds (a > b) - should still work with pmin/pmax
test_that('truncate handles reversed bounds', {
  # pmin and pmax will handle this gracefully
  result <- truncate(5, a = 10, b = 0)
  expect_equal(result, 0)
})

# Test 13: Empty vector
test_that('truncate handles empty vectors', {
  expect_equal(truncate(numeric(0), a = 0, b = 5), numeric(0))
})

# Test 14: NA values are preserved
test_that('truncate preserves NA values', {
  result <- truncate(c(1, NA, 3), a = 0, b = 5)
  expect_equal(result[1], 1)
  expect_true(is.na(result[2]))
  expect_equal(result[3], 3)
})

# Test 15: Inf values
test_that('truncate handles infinite values', {
  expect_equal(truncate(Inf, a = 0, b = 5), 5)
  expect_equal(truncate(-Inf, a = 0, b = 5), 0)
})

# Error handling: x is not numeric
test_that('truncate rejects non-numeric x', {
  expect_error(truncate("text", a = 0, b = 5), 'must be numeric', fixed = TRUE)
  expect_error(truncate(TRUE, a = 0, b = 5), 'must be numeric', fixed = TRUE)
  expect_error(truncate(list(1, 2), a = 0, b = 5), 'must be numeric', fixed = TRUE)
})

# Error handling: a is not numeric
test_that('truncate rejects non-numeric a', {
  expect_error(truncate(5, a = "zero", b = 5), 'must be numeric', fixed = TRUE)
  expect_error(truncate(5, a = list(0), b = 5), 'must be numeric', fixed = TRUE)
})

# Error handling: b is not numeric
test_that('truncate rejects non-numeric b', {
  expect_error(truncate(5, a = 0, b = "five"), 'must be numeric', fixed = TRUE)
  expect_error(truncate(5, a = 0, b = list(5)), 'must be numeric', fixed = TRUE)
})

# Error handling: all three are non-numeric
test_that('truncate rejects multiple non-numeric arguments', {
  expect_error(truncate("x", a = "a", b = "b"), 'must be numeric', fixed = TRUE)
})

# Error handling: NULL values
test_that('truncate rejects NULL values', {
  expect_error(truncate(NULL, a = 0, b = 5), 'must be numeric', fixed = TRUE)
  expect_error(truncate(5, a = NULL, b = 5), 'must be numeric', fixed = TRUE)
  expect_error(truncate(5, a = 0, b = NULL), 'must be numeric', fixed = TRUE)
})
