# WARNING - Generated by {fusen} from dev/flat_stancer.Rmd: do not edit by hand # nolint: line_length_linter.

# Test 1: stage_complete returns elapsed time when msg is NULL
test_that('stage_complete returns elapsed time for NULL msg', {
  result <- stage_complete(tic = 0, toc = 1.5, msg = NULL)
  expect_equal(result, "1.5 seconds elapsed")
})

# Test 2: stage_complete returns elapsed time when msg is NA
test_that('stage_complete returns elapsed time for NA msg', {
  result <- stage_complete(tic = 0, toc = 2.345, msg = NA)
  expect_equal(result, "2.345 seconds elapsed")
})

# Test 3: stage_complete formats message with checkmark and time
test_that('stage_complete formats message with checkmark', {
  result <- stage_complete(tic = 0, toc = 1, msg = "Processing")
  expect_match(result, "\u2705 Processing complete – 1 seconds elapsed")
})

# Test 4: stage_complete rounds elapsed time to 3 decimal places
test_that('stage_complete rounds time to 3 decimals', {
  result <- stage_complete(tic = 0, toc = 1.23456, msg = "Test")
  expect_match(result, "1.235 seconds elapsed")
})
