# WARNING - Generated by {fusen} from dev/flat_stancer.Rmd: do not edit by hand # nolint: line_length_linter.

test_that('stance_cola is a function', {
  expect_true(inherits(stance_cola, 'function'))
})

test_that("stance_cola works", {
  # Mocking all internal stages to avoid API calls
  # stub_llm_methods()
  mockery::stub(stance_cola, "templates_collect", list())
  mockery::stub(
    stance_cola,
    "stage_1_parallel_analysis",
    function(x, ...) x
  )
  mockery::stub(
    stance_cola,
    "stage_2_parallel_debates",
    function(x, ...) x
  )
  mockery::stub(
    stance_cola,
    "stage_3_parallel_judgement",
    function(x, ...) {
      x$judgement_results <- data.frame(
        stance = "Negative", explanation = "Content analysis results")
      x
    }
  )
  mockery::stub(stance_cola, "validate_stage", function(x, ...) x)
  
  # Use a chat list
  chats <- list(
    ellmer::chat_mistral(echo = "none"),
    ellmer::chat_mistral(echo = "none"),
    ellmer::chat_mistral(echo = "none")
  )
  
  res <- stance_cola(
    "Text mining is fun", "Text mining", type = "object",
    target_type = "the object", scale = "Likert",
    chats = chats, verbose = FALSE, language = "en",
    prompts_dir = "/", domain_role = "Sociologist"
  )
  
  expect_type(res, "list")
  expect_equal(res$judgement_results$stance, "Negative")
  
  expect_output(
    stance_cola(
      "Content analysis is fun", "Content Analysis is fun", type = "claim",
      target_type = "the claim", scale = "Likert",
      chats = chats, verbose = TRUE, language = "en",
      prompts_dir = "/", domain_role = "Sociologist"
    ),
    "STANCE ANALYSIS"
  )
})

test_that("stance_cola returns informative error", {
  mockery::stub(stance_cola, "templates_collect", list())
  mockery::stub(
    stance_cola,
    "stage_1_parallel_analysis",
    function(x, ...) x
  )
  mockery::stub(
    stance_cola,
    "stage_2_parallel_debates",
    function(x, ...) x
  )
  mockery::stub(
    stance_cola,
    "stage_3_parallel_judgement",
    function(x, ...) {
      x$judgement_results <- data.frame(
        stance = "Negative", explanation = "Content analysis results")
      x
    }
  )
  mockery::stub(stance_cola, "validate_stage", function(x, ...) x)
  
  chats <- list(ellmer::chat_mistral(echo = "none"))
  
  stance_cola(
    c("Text mining is fun", "Natural language processing is text mining"),
    c("Text mining", "Text mining"),
    type = c("object", "object"),
    target_type = c("the object", "the object"),
    prompts_dir = "/", scale = "Likert", domain_role = "Data Scientist",
    chats = chats, verbose = FALSE, language = "en"
  ) |>
    expect_error("judgement returned unexpected", fixed = TRUE)
})
