# WARNING - Generated by {fusen} from dev/flat_stancer.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("tasks_validate returns invisible TRUE on valid input", {
  tasks <- c("Content analysis task 1", "Content analysis task 2")
  expect_true(tasks_validate(tasks, 2))
  expect_invisible(tasks_validate(tasks, 2))
})

test_that("tasks_validate throws error on incorrect length", {
  tasks <- c("Content analysis task 1", "Content analysis task 2")
  expect_error(
    tasks_validate(tasks, 3),
    "User prompt interpolation returned unexpected results",
    fixed = TRUE
  )

  expect_error(
    tasks_validate(tasks, 1),
    "User prompt interpolation returned unexpected results",
    fixed = TRUE
  )
})

test_that("tasks_validate throws error if tasks is not character", {
  expect_error(
    tasks_validate(list("Content analysis task 1", "Content analysis task 2"), 2),
    "User prompt interpolation returned unexpected results",
    fixed = TRUE
  )

  expect_error(
    tasks_validate(c(1, 2), 2),
    "User prompt interpolation returned unexpected results",
    fixed = TRUE
  )
})

test_that("tasks_validate throws error on empty strings", {
  tasks_with_empty <- c("Valid task", "")
  expect_error(
    tasks_validate(tasks_with_empty, 2),
    "User prompt is empty after interpolation",
    fixed = TRUE
  )
})

test_that("tasks_validate throws error on NA values", {
  # nchar(NA) is NA, which fails the if(any(nchar...)) check or behaves unexpectedly
  tasks_with_na <- c("Valid task", NA_character_)
  expect_error(
    tasks_validate(tasks_with_na, 2),
    "contains missing",
    fixed = TRUE
  )
})

test_that("tasks_validate works with single task", {
  expect_true(tasks_validate("Single task", 1))
})

test_that("tasks_validate rejects zero length expectation", {
  expect_error(tasks_validate(character(0), 0), "Wrong", fixed = TRUE)
})

test_that("tasks_validate rejects fractional `expected_length`", {
  expect_error(tasks_validate("A task", 1.5), "Wrong", fixed = TRUE)
})

# Mocking a Chat object for testing
MockChat <- R6::R6Class(
  "MockChat",
  public = list(
    system_prompt = NULL,
    set_system_prompt = function(prompt) {
      self$system_prompt <- prompt
    }
  )
)

test_that("tasks_prepare returns correct structure for single system prompt", {
  chat_base <- MockChat$new()
  prompts <- list(
    system = "System Instructions",
    task = c("Task 1", "Task 2", "Task 3")
  )
  n_texts <- 3

  result <- tasks_prepare(chat_base, prompts, n_texts)

  expect_type(result, "list")
  expect_named(result, c("chats", "tasks"))
  expect_length(result$chats, 1)
  expect_length(result$tasks, 3)
  expect_equal(result$chats[[1]]$system_prompt, "System Instructions")
})

test_that("tasks_prepare returns correct structure for multiple system prompts", {
  chat_base <- MockChat$new()
  prompts <- list(
    system = c("System 1", "System 2"),
    task = c("Task 1", "Task 2")
  )
  n_texts <- 2

  result <- tasks_prepare(chat_base, prompts, n_texts)

  expect_named(result, c("chats", "tasks"))
  expect_length(result$chats, 2)
  expect_equal(result$chats[[1]]$system_prompt, "System 1")
  expect_equal(result$chats[[2]]$system_prompt, "System 2")
})

test_that("tasks_prepare throws error on mismatched system prompt length", {
  chat_base <- MockChat$new()
  # 2 system prompts for 3 texts is invalid (must be 1 or n_texts)
  prompts <- list(
    system = c("System 1", "System 2"),
    task = c("Task 1", "Task 2", "Task 3")
  )
  n_texts <- 3

  expect_error(
    tasks_prepare(chat_base, prompts, n_texts),
    regexp = "Length of system and user prompts must match 3",
    fixed = FALSE
  )
})

test_that("tasks_prepare validates user tasks using tasks_validate", {
  chat_base <- MockChat$new()
  # Empty task should trigger tasks_validate error
  prompts <- list(
    system = "System",
    task = c("Task 1", "")
  )
  n_texts <- 2

  expect_error(
    tasks_prepare(chat_base, prompts, n_texts),
    regexp = "User prompt is empty after interpolation",
    fixed = TRUE
  )
})

test_that("tasks_prepare clones the base chat deeply", {
  chat_base <- MockChat$new()
  chat_base$system_prompt <- "Original"

  prompts <- list(
    system = "New System",
    task = "Task 1"
  )

  result <- tasks_prepare(chat_base, prompts, 1)

  # Check that the clone has the new prompt but the base remains unchanged
  expect_equal(result$chats[[1]]$system_prompt, "New System")
  expect_equal(chat_base$system_prompt, "Original")
  # Verify they are different objects
  expect_false(identical(chat_base, result$chats[[1]]))
})
