# WARNING - Generated by {fusen} from dev/flat_stancer.Rmd: do not edit by hand # nolint: line_length_linter.

# Test 1: recycle_arg replicates single value to length n
test_that('recycle_arg replicates single value', {
  result <- recycle_arg("x", n = 3)
  expect_equal(result, c("x", "x", "x"))
})

# Test 2: recycle_arg returns unchanged vector of length n
test_that('recycle_arg returns vector of matching length', {
  input <- c("a", "b", "c")
  result <- recycle_arg(input, n = 3)
  expect_identical(result, input)
})

# Test 3: recycle_arg rejects vector with mismatched length
test_that('recycle_arg rejects mismatched length', {
  expect_error(
    recycle_arg(c("a", "b"), n = 3),
    "must have length 1 or 3",
    fixed = TRUE
  )
})

# Test 4: recycle_arg includes argument name in error message
test_that('recycle_arg includes arg name in error', {
  my_vector <- c(1, 2, 3, 4)
  expect_error(
    recycle_arg(my_vector, n = 2),
    "my_vector",
    fixed = TRUE
  )
})
