# WARNING - Generated by {fusen} from dev/flat_stancer.Rmd: do not edit by hand # nolint: line_length_linter.

# Reusing the MockChat
MockChat <- R6::R6Class(
  "MockChat",
  public = list(
    system_prompt = NULL,
    set_system_prompt = function(prompt) {
      self$system_prompt <- prompt
    },
    chat = function(..., echo = NULL) paste("Response", seq_along(list(...)))
  )
)

test_that("stage_2_parallel_debates executes three debate branches", {
  # 1. Set-up Data
  inputs <- list(
    texts = c("T1", "T2"),
    targets = c("A", "B"),
    target_types = c("statement", "statement"),
    language = "en",
    scale = 'likert',
    prompt_templates = list(t = 1),
    analysis_results = list(
      linguistic = c("L1", "L2"),
      domain = c("D1", "D2"),
      social_media = c("S1", "S2")
    )
  )

  # 2. Set-up Mocks
  # mockery::stub(stage_2_parallel_debates, "validate_fields", TRUE)
  # mockery::stub(stage_2_parallel_debates, "validate_inputs", TRUE)
  mockery::stub(stage_2_parallel_debates, "tictoc::tic", NULL)
  mockery::stub(stage_2_parallel_debates, "tictoc::toc", NULL)

  # Mock l() localization helper
  mockery::stub(stage_2_parallel_debates, "l", function(lang, key, scale) key)

  # Mock prepare_debater_chats
  # We return a dummy chat and tasks
  mockery::stub(
    stage_2_parallel_debates,
    "prepare_debater_chats",
    function(stance, ...) {
      list(chats = list(MockChat$new()), tasks = paste(stance, "task"))
    }
  )

  # Mock parallel_chat_text to return stance-specific results
  mock_parallel <- mockery::mock(
    "Pos Result", # first call (positive)
    "Neg Result", # second call (negative)
    "Neu Result"  # third call (neutral)
  )
  mockery::stub(stage_2_parallel_debates, "ellmer::parallel_chat_text", mock_parallel)

  # 3. Execute
  result <- stage_2_parallel_debates(inputs, MockChat$new(), verbose = FALSE)

  # 4. Verify
  expect_named(result$debate_results, c("positive", "negative", "neutral"))
  expect_equal(result$debate_results$positive, "Pos Result")
  expect_equal(result$debate_results$negative, "Neg Result")
  expect_equal(result$debate_results$neutral, "Neu Result")

  # Verify it was called 3 times (once for each stance)
  mockery::expect_called(mock_parallel, 3)
})

test_that("stage_2_parallel_debates validates Stage 1 results before proceeding", {
  inputs <- list(
    texts = c("T1", "T2"),
    analysis_results = list(
      linguistic = "Too Short", # Should be length 2
      domain = c("D1", "D2"),
      social_media = c("S1", "S2")
    )
  )

  # Mock validate_fields but let validate_inputs run
  mockery::stub(stage_2_parallel_debates, "validate_fields", TRUE)

  # validate_inputs should throw error because linguistic length (1) != n (2)
  expect_error(
    stage_2_parallel_debates(inputs, MockChat$new(), verbose = FALSE),
    "Linguistic analysis returned unexpected results",
    fixed = TRUE
  )
})

test_that("stage_2_parallel_debates passes the correct RPM to parallel_chat_text", {
  # Set-up minimal valid inputs
  inputs <- list(
    texts = "T1", targets = "A", target_types = "statement",
    language = "en", scale = "likert",
    prompt_templates = list(t = 1),
    analysis_results = list(
      linguistic = "L1", domain = "D1", social_media = "S1"
    )
  )

  # Mock dependencies
  # mockery::stub(stage_2_parallel_debates, "validate_fields", TRUE)
  # mockery::stub(stage_2_parallel_debates, "validate_inputs", TRUE)
  mockery::stub(stage_2_parallel_debates, "l", "mock stance")
  mockery::stub(
    stage_2_parallel_debates,
    "prepare_debater_chats",
    list(chats = list(MockChat$new()), tasks = "task")
  )

  mock_parallel <- mockery::mock("Pos Result", "Neg Result", "Neu Result")
  mockery::stub(stage_2_parallel_debates, "ellmer::parallel_chat_text", mock_parallel)

  # Execute with custom RPM
  stage_2_parallel_debates(inputs, MockChat$new(), rpm = 42, verbose = FALSE)

  # Verify RPM in the first call to parallel_chat_text
  args <- mockery::mock_args(mock_parallel)[[1]]
  expect_equal(args$rpm, 42)
  expect_equal(args$prompts, "task")
})

test_that("stage_2_parallel_debates correctly localises stances for each branch", {
  # 1. Set-up data
  inputs <- list(
    texts = "T1", targets = "A", target_types = "statement",
    language = "en", scale = "likert",
    prompt_templates = list(t = "file"),
    analysis_results = list(
      linguistic = "L1", domain = "D1", social_media = "S1"
    )
  )

  # 2. Set-up Mocks
  # mockery::stub(stage_2_parallel_debates, "validate_fields", TRUE)
  # mockery::stub(stage_2_parallel_debates, "validate_inputs", TRUE)
  mockery::stub(stage_2_parallel_debates, "tictoc::tic", NULL)
  mockery::stub(stage_2_parallel_debates, "tictoc::toc", NULL)

  # Mocking l(), so that it returns a recognisable marker
  mockery::stub(stage_2_parallel_debates, "l", function(lang, key, scale) {
    paste0("loc_", key)
  })

  # Мокаем prepare_debater_chats, чтобы отследить, какой stance в неё пришел
  mock_prepare <- mockery::mock(
    list(chats = list(MockChat$new()), tasks = "task"), # для positive
    list(chats = list(MockChat$new()), tasks = "task"), # для negative
    list(chats = list(MockChat$new()), tasks = "task")  # для neutral
  )
  mockery::stub(stage_2_parallel_debates, "prepare_debater_chats", mock_prepare)

  # Mock parallel_chat_text to return stance-specific results
  mock_parallel <- mockery::mock(
    "Pos Result", # first call (positive)
    "Neg Result", # second call (negative)
    "Neu Result"  # third call (neutral)
  )
  mockery::stub(stage_2_parallel_debates, "ellmer::parallel_chat_text", mock_parallel)

  # 3. Execute
  stage_2_parallel_debates(inputs, MockChat$new(), verbose = FALSE)

  # 4. Verify
  # Достаем аргументы всех трех вызовов prepare_debater_chats
  mockery::expect_called(mock_prepare, 3)

  prep_args <- mockery::mock_args(mock_prepare)

  # Проверяем, что в каждом вызове аргумент stance был локализован правильно
  expect_equal(prep_args[[1]]$stance, "loc_stance_positive")
  expect_equal(prep_args[[2]]$stance, "loc_stance_negative")
  expect_equal(prep_args[[3]]$stance, "loc_stance_neutral")

  # Также можно проверить, что inputs и chat_base передаются без изменений
  expect_equal(prep_args[[1]]$inputs$language, "en")

  expect_equal(prep_args[[1]]$inputs$scale, "likert")
})

test_that("stage_2_parallel_debates handles empty input texts gracefully", {
  # If n=0, the loops should still work but return empty lists
  inputs <- list(
    texts = character(0), targets = character(0), target_types = character(0),
    language = "en", scale = "likert",
    prompt_templates = list(t = "file"),
    analysis_results = list(
      linguistic = character(0), domain = character(0), social_media = character(0)
    )
  )

  # mockery::stub(stage_2_parallel_debates, "validate_fields", TRUE)
  # mockery::stub(stage_2_parallel_debates, "validate_inputs", TRUE)
  mockery::stub(
    stage_2_parallel_debates,
    "prepare_debater_chats",
    list(chats = list(MockChat$new()), tasks = character(0))
  )
  # Mock parallel_chat_text to return stance-specific results
  mock_parallel <- mockery::mock(character(0), character(0), character(0))
  mockery::stub(stage_2_parallel_debates, "ellmer::parallel_chat_text", mock_parallel)

  result <- stage_2_parallel_debates(inputs, MockChat$new(), verbose = FALSE)

  expect_length(result$debate_results$positive, 0)
  expect_named(result$debate_results, c("positive", "negative", "neutral"))
})
