# WARNING - Generated by {fusen} from dev/flat_stancer.Rmd: do not edit by hand # nolint: line_length_linter.

test_that('stancer_check_translations returns invisibly TRUE', {
  result <- stancer_check_translations()
  expect_true(result)
  expect_invisible(stancer_check_translations())
})

test_that('stancer_check_translations prints available languages', {
  expect_output(
    stancer_check_translations(),
    "Available languages:"
  )
})

test_that('stancer_check_translations lists all languages', {
  expect_output(
    stancer_check_translations(),
    "en"
  )
  expect_output(
    stancer_check_translations(),
    "uk"
  )
  expect_output(
    stancer_check_translations(),
    "ru"
  )
})

test_that('stancer_check_translations shows key count per language', {
  expect_output(
    stancer_check_translations(),
    "Language: en"
  )
  expect_output(
    stancer_check_translations(),
    "Keys: \\d+"
  )
})

test_that('stancer_check_translations identifies keys with cases', {
  expect_output(
    stancer_check_translations(),
    "Keys with cases:"
  )
})

test_that('stancer_check_translations output is consistent', {
  output1 <- capture.output(stancer_check_translations())
  output2 <- capture.output(stancer_check_translations())
  expect_equal(output1, output2)
})

test_that('stancer_check_translations handles all languages equally', {
  output <- capture.output(stancer_check_translations())

  # Проверяем, что каждый язык имеет свою секцию
  en_count <- sum(grepl("Language: en", output))
  uk_count <- sum(grepl("Language: uk", output))
  ru_count <- sum(grepl("Language: ru", output))

  expect_equal(en_count, 1)
  expect_equal(uk_count, 1)
  expect_equal(ru_count, 1)
})
