# WARNING - Generated by {fusen} from dev/flat_stancer.Rmd: do not edit by hand # nolint: line_length_linter.

# Test 1: Basic functionality - values within range
test_that('truncate returns values unchanged when within range', {
  expect_equal(truncate(3, a = 0, b = 5), 3)
  expect_equal(truncate(c(1, 2, 3), a = 0, b = 5), c(1, 2, 3))
})

# Test 2: Values below lower bound
test_that('truncate sets values below a to a', {
  expect_equal(truncate(-1, a = 0, b = 5), 0)
  expect_equal(truncate(c(-5, -1, 0), a = 0, b = 5), c(0, 0, 0))
})

# Test 3: Values above upper bound
test_that('truncate sets values above b to b', {
  expect_equal(truncate(10, a = 0, b = 5), 5)
  expect_equal(truncate(c(5, 6, 10), a = 0, b = 5), c(5, 5, 5))
})

# Test 4: Mixed values (below, within, above)
test_that('truncate handles mixed values correctly', {
  expect_equal(
    truncate(c(-1, 0, 3, 5, 10), a = 0, b = 5),
    c(0, 0, 3, 5, 5)
  )
})

# Test 5: Negative ranges
test_that('truncate works with negative ranges', {
  expect_equal(truncate(c(-10, -5, 0), a = -8, b = -2), c(-8, -5, -2))
})

# Test 6: Single value at boundaries
test_that('truncate handles boundary values', {
  expect_equal(truncate(0, a = 0, b = 5), 0)
  expect_equal(truncate(5, a = 0, b = 5), 5)
})

# Test 7: Vectorized operation
test_that('truncate is vectorized', {
  x <- c(-10, -5, 0, 5, 10, 15)
  result <- truncate(x, a = 0, b = 10)
  expect_equal(result, c(0, 0, 0, 5, 10, 10))
})

# Test 8: Floating point values
test_that('truncate works with floating point numbers', {
  expect_equal(truncate(3.5, a = 0, b = 5), 3.5)
  expect_equal(truncate(-0.5, a = 0, b = 5), 0)
  expect_equal(truncate(5.5, a = 0, b = 5), 5)
})

# Test 9: Very large and very small numbers
test_that('truncate handles extreme values', {
  expect_equal(truncate(1e10, a = 0, b = 100), 100)
  expect_equal(truncate(-1e10, a = 0, b = 100), 0)
})

# Test 10: Zero as bound
test_that('truncate works with zero as bound', {
  expect_equal(truncate(c(-5, 0, 5), a = 0, b = 10), c(0, 0, 5))
  expect_equal(truncate(c(-5, 0, 5), a = -10, b = 0), c(-5, 0, 0))
})

# Test 11: Equal bounds (a == b)
test_that('truncate works when a equals b', {
  expect_equal(truncate(c(-5, 0, 5), a = 3, b = 3), c(3, 3, 3))
})

# Test 12: Reversed bounds (a > b) - should still work with pmin/pmax
test_that('truncate handles reversed bounds', {
  # pmin and pmax will handle this gracefully
  result <- truncate(5, a = 10, b = 0)
  expect_equal(result, 0)
})

# Test 13: Empty vector
test_that('truncate handles empty vectors', {
  expect_equal(truncate(numeric(0), a = 0, b = 5), numeric(0))
})

# Test 14: NA values are preserved
test_that('truncate preserves NA values', {
  result <- truncate(c(1, NA, 3), a = 0, b = 5)
  expect_equal(result[1], 1)
  expect_true(is.na(result[2]))
  expect_equal(result[3], 3)
})

# Test 15: Inf values
test_that('truncate handles infinite values', {
  expect_equal(truncate(Inf, a = 0, b = 5), 5)
  expect_equal(truncate(-Inf, a = 0, b = 5), 0)
})

# Error handling: x is not numeric
test_that('truncate rejects non-numeric x', {
  expect_error(truncate("text", a = 0, b = 5), 'must be numeric', fixed = TRUE)
  expect_error(truncate(TRUE, a = 0, b = 5), 'must be numeric', fixed = TRUE)
  expect_error(truncate(list(1, 2), a = 0, b = 5), 'must be numeric', fixed = TRUE)
})

# Error handling: a is not numeric
test_that('truncate rejects non-numeric a', {
  expect_error(truncate(5, a = "zero", b = 5), 'must be numeric', fixed = TRUE)
  expect_error(truncate(5, a = list(0), b = 5), 'must be numeric', fixed = TRUE)
})

# Error handling: b is not numeric
test_that('truncate rejects non-numeric b', {
  expect_error(truncate(5, a = 0, b = "five"), 'must be numeric', fixed = TRUE)
  expect_error(truncate(5, a = 0, b = list(5)), 'must be numeric', fixed = TRUE)
})

# Error handling: all three are non-numeric
test_that('truncate rejects multiple non-numeric arguments', {
  expect_error(truncate("x", a = "a", b = "b"), 'must be numeric', fixed = TRUE)
})

# Error handling: NULL values
test_that('truncate rejects NULL values', {
  expect_error(truncate(NULL, a = 0, b = 5), 'must be numeric', fixed = TRUE)
  expect_error(truncate(5, a = NULL, b = 5), 'must be numeric', fixed = TRUE)
  expect_error(truncate(5, a = 0, b = NULL), 'must be numeric', fixed = TRUE)
})

# Test 1: abort throws an error
test_that('abort throws an error', {
  expect_error(abort("Test error message"))
})

# Test 2: abort with simple string message
test_that('abort with simple string message', {
  expect_error(
    abort("This is an error"),
    "This is an error",
    fixed = TRUE
  )
})

# Test 3: abort with cli formatting - .arg
test_that('abort with .arg formatting', {
  expect_error(
    abort("{.arg x} must be numeric"),
    "must be numeric",
    fixed = TRUE
  )
})

# Test 4: abort with cli formatting - .val
test_that('abort with .val formatting', {
  expect_error(
    abort("Invalid value: {.val {5}}"),
    "Invalid value",
    fixed = TRUE
  )
})

# Test 5: abort with cli formatting - .cls
test_that('abort with .cls formatting', {
  expect_error(
    abort("Expected {.cls character}, got {.cls numeric}"),
    "Expected",
    fixed = TRUE
  )
})

# Test 6: abort with multiple cli formatting elements
test_that('abort with multiple formatting elements', {
  expect_error(
    abort(
      "Argument {.arg x} must be {.cls numeric}, not {.cls list}"
    ),
    "must be",
    fixed = TRUE
  )
})

# Test 7: abort with interpolation - variable substitution
test_that('abort with variable interpolation', {
  var_name <- "test_var"
  expect_error(
    abort("Variable '{var_name}' not found"),
    "test_var",
    fixed = TRUE
  )
})

# Test 8: abort with complex interpolation
test_that('abort with complex interpolation', {
  lang <- "en"
  expect_error(
    abort("Language '{lang}' not available"),
    "Language 'en' not available",
    fixed = TRUE
  )
})

# Test 9: abort preserves error class
test_that('abort creates rlang_error', {
  expect_error(
    abort("Test error"),
    class = "rlang_error"
  )
})

# Test 10: abort with empty message
test_that('abort with empty message', {
  expect_error(abort(""))
})

# Test 11: abort with very long message
test_that('abort with long message', {
  long_msg <- paste(rep("a", 1000), collapse = "")
  expect_error(abort(long_msg))
})

# Test 12: abort with special characters
test_that('abort with special characters', {
  expect_error(
    abort("Error with special chars: @#$%^&*()"),
    "special chars",
    fixed = TRUE
  )
})

# Test 13: abort with quotes in message
test_that('abort with quotes in message', {
  expect_error(
    abort('Error with "double" and \'single\' quotes'),
    "quotes",
    fixed = TRUE
  )
})

# Test 14: abort with list formatting
test_that('abort with list formatting', {
  expect_error(
    abort("Available options: {.val {c('a', 'b', 'c')}}"),
    "Available",
    fixed = TRUE
  )
})

# Test 15: abort with vector in message
test_that('abort with vector interpolation', {
  vals <- c("x", "y", "z")
  expect_error(
    abort("Invalid values: {.val {vals}}"),
    "Invalid",
    fixed = TRUE
  )
})

# Test 16: abort with numeric values in message
test_that('abort with numeric interpolation', {
  n <- 111
  expect_error(
    abort("Expected {n} items, got 0"),
    "Expected 111",
    fixed = TRUE
  )
})

# Test 17: abort with logical values in message
test_that('abort with logical values', {
  flag <- TRUE
  expect_error(
    abort("Flag is {flag}"),
    "Flag is TRUE",
    fixed = TRUE
  )
})

# Test 18: abort with NA values
test_that('abort with NA values', {
  na_val <- NA
  expect_error(
    abort("Value is {na_val}"),
    "Value",
    fixed = TRUE
  )
})

# Test 19: abort with function name in message
test_that('abort with function reference', {
  expect_error(
    abort("Function {.fn truncate} failed"),
    "failed",
    fixed = TRUE
  )
})

# Test 20: abort uses caller environment
test_that('abort uses caller environment', {
  test_var <- "from_caller"
  expect_error(
    abort("Variable: {test_var}"),
    "from_caller",
    fixed = TRUE
  )
})

# Test 21: abort in nested function call
test_that('abort in nested function', {
  inner_func <- function() {
    abort("Error from inner function")
  }

  outer_func <- function() {
    inner_func()
  }

  expect_error(
    outer_func(),
    "Error from inner function",
    fixed = TRUE
  )
})

# Test 22: abort does not return value (throws immediately)
test_that('abort does not return', {
  result <- tryCatch(
    {
      abort("Test")
      "should not reach here"
    },
    error = function(e) {
      "caught error"
    }
  )
  expect_equal(result, "caught error")
})

# Test 23: abort with .arg and variable
test_that('abort with .arg and variable name', {
  param_name <- "data"
  expect_error(
    abort("Argument {.arg {param_name}} is invalid"),
    "invalid",
    fixed = TRUE
  )
})

# Test 24: abort with .cls and actual class
test_that('abort with .cls and object class', {
  obj <- list(a = 1)
  expect_error(
    abort("Expected data.frame, got {.cls {class(obj)}}"),
    "Expected",
    fixed = TRUE
  )
})

# Test 25: abort with multiple .val elements
test_that('abort with multiple .val elements', {
  expect_error(
    abort(
      "Got {.val {1}}, expected one of {.val {c(2, 3, 4)}}"
    ),
    "Got",
    fixed = TRUE
  )
})

# Test 26: abort preserves message formatting
test_that('abort message is not modified', {
  msg <- "Exact error message"
  tryCatch(
    abort(msg),
    error = function(e) {
      expect_true(grepl(msg, conditionMessage(e), fixed = TRUE))
    }
  )
})

# Test 27: abort called multiple times creates different errors
test_that('multiple abort calls create separate errors', {
  error1 <- tryCatch(
    abort("Error 1"),
    error = function(e) e
  )

  error2 <- tryCatch(
    abort("Error 2"),
    error = function(e) e
  )

  expect_true(grepl("Error 1", conditionMessage(error1)))
  expect_true(grepl("Error 2", conditionMessage(error2)))
  expect_false(identical(error1, error2))
})

# Test 28: abort with complex nested formatting
test_that('abort with complex nested formatting', {
  lang <- "en"
  available <- c("en", "ru", "fr")
  expect_error(
    abort(
      "Language '{lang}' not available. Use: {.val {available}}"
    ),
    "not available",
    fixed = TRUE
  )
})

# Test 29: abort requires exactly one argument
test_that('abort requires msg argument', {
  expect_error(abort(), "missing", fixed = TRUE)
})

# Test 30: abort with NULL message
test_that('abort with NULL message', {
  expect_error(abort(NULL), 'must be supplied', fixed = TRUE)
})

# Test 31: abort with numeric message (coerced to string)
test_that('abort with numeric message', {
  expect_error(
    abort(123),
    "123",
    fixed = TRUE
  )
})

# Test 32: abort with expression in message
test_that('abort with expression evaluation', {
  x <- 5
  y <- 3
  expect_error(
    abort("Sum is {x + y}"),
    "Sum is 8",
    fixed = TRUE
  )
})

# Test 33: abort message with unicode characters
test_that('abort with unicode characters', {
  expect_error(
    abort("Hello \U1F680"),
    "Hello",
    fixed = TRUE
  )
})

# Test 1: catch executes expression successfully
test_that('catch executes expression without error', {
  expect_no_error(catch(1 + 1))
})

# Test 2: catch with variable assignment
test_that('catch evaluates expression with variables', {
  x <- 5
  result <- catch(x * 2)
  expect_equal(result, 10)
})

# Test 3: catch with function call
test_that('catch executes function call', {
  result <- catch(sqrt(16))
  expect_equal(result, 4)
})

# Test 4: catch catches errors and wraps them
test_that('catch catches error and wraps message', {
  expect_error(
    catch(stop("Original error")),
    "Error in",
    fixed = TRUE
  )
})

# Test 5: catch preserves original error message
test_that('catch preserves original error message', {
  expect_error(
    catch(stop("Original error")),
    "Original error",
    fixed = TRUE
  )
})

# Test 6: catch with custom expr_name
test_that('catch with custom expr_name parameter', {
  expect_error(
    catch(stop("Test"), expr_name = "custom_operation"),
    "Error in custom_operation",
    fixed = TRUE
  )
})

# Test 7: catch with default expr_name from deparse
test_that('catch uses deparse(substitute(expr)) for default name', {
  expect_error(
    catch(1 / "1"),
    "Error in 1",
    fixed = TRUE
  )
})

# Test 8: catch rejects non-character expr_name
test_that('catch rejects non-character expr_name', {
  expect_error(
    catch(1 + 1, expr_name = 123),
    "must be a character scalar",
    fixed = TRUE
  )
})

# Test 9: catch rejects non-scalar character expr_name
test_that('catch rejects non-scalar character expr_name', {
  expect_error(
    catch(1 + 1, expr_name = c("a", "b")),
    "must be a character scalar",
    fixed = TRUE
  )
})

# Test 10: catch with complex expression
test_that('catch evaluates complex expression', {
  result <- catch({
    x <- 10
    y <- 20
    x + y
  })
  expect_equal(result, 30)
})

# Test 11: catch with error in nested function call
test_that('catch catches error in nested function', {
  expect_error(
    catch(sqrt(as.numeric(sqrt("NA")))),
    "Error in",
    fixed = TRUE
  )
})

# Test 12: catch with NULL expr_name throws error
test_that('catch rejects NULL expr_name', {
  expect_error(
    catch(1 + 1, expr_name = NULL),
    "must be a character scalar",
    fixed = TRUE
  )
})

# Test 13: catch with empty string expr_name
test_that('catch accepts empty string expr_name', {
  result <- catch(1 + 1, expr_name = "")
  expect_equal(result, 2)
})

data <- data.frame(text = "Julia is fast & beautiful", language = "Julia")

# Test 1: catch_eval evaluates expressions successfully
test_that('catch_eval evaluates expressions successfully', {
  expect_no_error(target_vec <- catch_eval(rlang::quo(language), data))
  expect_equal(target_vec, "Julia")
})

# Test 2: catch_eval throws an error on evaluation failure
test_that('catch_eval throws an error on evaluation failure', {
  expect_error(catch_eval(rlang::quo(type), data), "column name", fixed = TRUE)
})

# Test 3: catch_eval rejects wrong arguments
test_that('catch_eval rejects wrong arguments', {
  expect_error(catch_eval("language", data), "must be a quosure", fixed = TRUE)
})

data <- data.frame(text = "Julia is fast & beautiful", language = "Julia")

# Test 1: safe_eval evaluates expressions successfully
test_that('safe_eval evaluates expressions successfully', {
  expect_no_error(text_vec <- safe_eval(rlang::quo(text), data))
  expect_equal(text_vec, "Julia is fast & beautiful")
})

# Test 2: safe_eval returns NULL on evaluation failure
test_that('safe_eval returns NULL on evaluation failure', {
  expect_no_error(type_vec <- safe_eval(rlang::quo(type), data))
  expect_null(type_vec)
})

# Test 1: recycle_arg replicates single value to length n
test_that('recycle_arg replicates single value', {
  result <- recycle_arg("x", n = 3)
  expect_equal(result, c("x", "x", "x"))
})

# Test 2: recycle_arg returns unchanged vector of length n
test_that('recycle_arg returns vector of matching length', {
  input <- c("a", "b", "c")
  result <- recycle_arg(input, n = 3)
  expect_identical(result, input)
})

# Test 3: recycle_arg rejects vector with mismatched length
test_that('recycle_arg rejects mismatched length', {
  expect_error(
    recycle_arg(c("a", "b"), n = 3),
    "must have length 1 or 3",
    fixed = TRUE
  )
})

# Test 4: recycle_arg includes argument name in error message
test_that('recycle_arg includes arg name in error', {
  my_vector <- c(1, 2, 3, 4)
  expect_error(
    recycle_arg(my_vector, n = 2),
    "my_vector",
    fixed = TRUE
  )
})
