# WARNING - Generated by {fusen} from dev/flat_stancer.Rmd: do not edit by hand # nolint: line_length_linter.

# Set-up common paths for tests
prompts_dir <- system.file('prompts', 'en', package = 'stancer')
if (!dir.exists(prompts_dir)) prompts_dir <- here::here('inst', 'prompts', 'en')

test_that('type_stance_analysis returns object type', {
  template_file <- file.path(prompts_dir, 'description-categorical.md')
  skip_if_not(file.exists(template_file))
  result <- type_stance_analysis(
    language = "en",
    description_file = template_file,
    scale = "categorical"
  )
  expect_is(result, "ellmer::TypeObject")
})

test_that('type_stance_analysis includes stance and explanation fields', {
  template_file <- file.path(prompts_dir, 'description-categorical.md')
  skip_if_not(file.exists(template_file))
  result <- type_stance_analysis(
    language = "en",
    description_file = template_file,
    scale = "categorical"
  )
  expect_true("stance" %in% names(result@properties))
  expect_true("explanation" %in% names(result@properties))
})

test_that('type_stance_analysis creates categorical scale by default', {
  template_file <- file.path(prompts_dir, 'description-categorical.md')
  skip_if_not(file.exists(template_file))
  result <- type_stance_analysis(
    language = "en",
    description_file = template_file
  )
  expect_is(result@properties$stance, "ellmer::TypeEnum")
  expect_equal(result@properties$stance@values, c('Positive', 'Negative', 'Neutral'))
})

test_that('type_stance_analysis creates numeric scale when specified', {
  template_file <- file.path(prompts_dir, 'description-numeric.md')
  skip_if_not(file.exists(template_file))
  result <- type_stance_analysis(
    language = "en",
    description_file = template_file,
    scale = "numeric"
  )
  expect_is(result@properties$stance, "ellmer::TypeBasic")
  expect_equal(result@properties$stance@type, "number")
})

test_that('type_stance_analysis creates Likert scale when specified', {
  template_file <- file.path(prompts_dir, 'description-likert.md')
  skip_if_not(file.exists(template_file))
  result <- type_stance_analysis(
    language = "en",
    description_file = template_file,
    scale = "likert"
  )
  expect_is(result@properties$stance, "ellmer::TypeEnum")
  expect_equal(
    result@properties$stance@values,
    c('Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree')
  )
})

test_that('type_stance_analysis includes localised explanation description', {
  template_file <- file.path(prompts_dir, 'description-categorical.md')
  skip_if_not(file.exists(template_file))
  result <- type_stance_analysis(
    language = "en",
    description_file = template_file
  )
  expect_is(result@properties$explanation, "ellmer::TypeBasic")
  expect_equal(result@properties$explanation@type, "string")
  expect_type(result@properties$explanation@description, "character")
  expect_true(nchar(result@properties$explanation@description) > 0)
})

test_that('type_stance_analysis uses correct language for explanation', {
  template_file <- file.path(prompts_dir, 'description-categorical.md')
  skip_if_not(file.exists(template_file))

  result_en <- type_stance_analysis(
    language = "en",
    description_file = template_file
  )
  result_uk <- type_stance_analysis(
    language = "uk",
    description_file = template_file
  )

  expect_false(
    result_en@properties$explanation@description ==
      result_uk@properties$explanation@description
  )
})

test_that('type_stance_analysis rejects invalid scale', {
  template_file <- file.path(prompts_dir, 'description-categorical.md')
  skip_if_not(file.exists(template_file))
  expect_error(
    type_stance_analysis(
      language = "en",
      description_file = template_file,
      scale = "invalid"
    ),
    "must be one of",
    fixed = TRUE
  )
})

test_that('type_stance_analysis rejects invalid language', {
  template_file <- file.path(prompts_dir, 'description-categorical.md')
  skip_if_not(file.exists(template_file))
  expect_error(
    type_stance_analysis(
      language = "fr",
      description_file = template_file
    ),
    "Language 'fr' not available",
    fixed = TRUE
  )
})

test_that('type_stance_analysis handles missing description file', {
  template_file <- file.path(prompts_dir, 'nonexistent.md')
  skip_if(file.exists(template_file))
  expect_error(
    type_stance_analysis(
      language = "en",
      description_file = template_file
    ),
    class = "error"
  )
})

test_that('type_stance_analysis works with all available languages', {
  template_file <- file.path(prompts_dir, 'description-categorical.md')
  skip_if_not(file.exists(template_file))

  available_langs <- stancer_available_languages()

  for (lang in available_langs) {
    result <- type_stance_analysis(
      language = lang,
      description_file = template_file
    )
    expect_is(result, "ellmer::TypeObject")
    expect_true("stance" %in% names(result@properties))
    expect_true("explanation" %in% names(result@properties))
  }
})

test_that('type_stance_analysis works with all scale types', {
  cat_file <- file.path(prompts_dir, 'description-categorical.md')
  num_file <- file.path(prompts_dir, 'description-numeric.md')
  likert_file <- file.path(prompts_dir, 'description-likert.md')

  skip_if_not(
    file.exists(cat_file) &&
      file.exists(num_file) &&
      file.exists(likert_file)
  )

  result_cat <- type_stance_analysis(
    language = "en",
    description_file = cat_file,
    scale = "categorical"
  )
  result_num <- type_stance_analysis(
    language = "en",
    description_file = num_file,
    scale = "numeric"
  )
  result_likert <- type_stance_analysis(
    language = "en",
    description_file = likert_file,
    scale = "likert"
  )

  expect_is(result_cat@properties$stance, "ellmer::TypeEnum")
  expect_equal(result_num@properties$stance@type, "number")
  expect_is(result_likert@properties$stance, "ellmer::TypeEnum")
})
