# WARNING - Generated by {fusen} from dev/flat_stancer.Rmd: do not edit by hand # nolint: line_length_linter.

# Helper to stub all internal stages of llm_stance.character
stub_llm_stages <- function() {
  testthat::local_mocked_bindings(
    validate_character = TRUE,
    templates_collect = list(),
    validate_stage = function(x, ...) x,
    stage_1_parallel_analysis = function(x, ...) x,
    stage_2_parallel_debates = function(x, ...) x,
    stage_3_parallel_judgement = function(x, ...) {
      x$judgement_results <- data.frame(
        stance = "Neutral",
        explanation = "Mocked text mining result"
      )
      x
    }
  )
}

test_that('llm_stance.character is a function', {
  expect_true(inherits(llm_stance.character, 'function'))
})

test_that("llm_stance.character handles chat list and cloning", {
  # Mocking all internal stages to avoid API calls
  # stub_llm_stages()
  mockery::stub(llm_stance.character, "validate_character", TRUE)
  mockery::stub(llm_stance.character, "rlang::is_installed", TRUE)
  mockery::stub(llm_stance.character, "cld2::detect_language", "en")
  mockery::stub(llm_stance.character, "templates_collect", list())
  mockery::stub(
    llm_stance.character,
    "stage_1_parallel_analysis",
    function(x, ...) x
  )
  mockery::stub(
    llm_stance.character,
    "stage_2_parallel_debates",
    function(x, ...) x
  )
  mockery::stub(
    llm_stance.character,
    "stage_3_parallel_judgement",
    function(x, ...) {
      x$judgement_results <- data.frame(
        stance = "Negative", explanation = "Content analysis results")
      x
    }
  )
  mockery::stub(llm_stance.character, "validate_stage", function(x, ...) x)

  # Use an empty Chat object
  chat <- ellmer::chat_mistral(echo = "none")

  # Test with single chat
  res <- llm_stance(
    "Text mining is fun", "Text mining", type = "object",
    chat_base = chat, verbose = TRUE, language = "en"
  )

  expect_named(
    res, c("summary", "analysis", "debates", "judgements", "metadata")
  )
  expect_equal(res$metadata$n_total, 1)
  expect_s3_class(res, "stance_result")

  # Test with list of 1 chat
  chat_list <- list(chat)
  res_list <- llm_stance(
    "Text mining is fun", "Text mining", type = "object",
    chat_base = chat_list, verbose = FALSE, language = "en"
  )
  expect_named(
    res_list, c("summary", "analysis", "debates", "judgements", "metadata")
  )
  expect_equal(res_list$metadata$n_total, 1)
  expect_s3_class(res_list, "stance_result")

  # Test with list of 2 chats (Stage 1&2 use chat 1, Stage 3 uses chat 2)
  chat_list <- list(chat, chat)
  res_list <- llm_stance(
    "Text mining is fun", "Text mining", type = "object",
    chat_base = chat_list, verbose = FALSE, language = "en"
  )
  expect_named(
    res_list, c("summary", "analysis", "debates", "judgements", "metadata")
  )
  expect_equal(res_list$metadata$n_total, 1)
  expect_s3_class(res_list, "stance_result")

  # Test with list of 3 chats (Stage 1&2 use chat 1, Stage 3 uses chat 2)
  chat_list <- list(chat, chat, chat)
  res_list <- llm_stance(
    "Text mining is fun", "Text mining", type = "object",
    chat_base = chat_list, verbose = FALSE, language = "en"
  )
  expect_named(
    res_list, c("summary", "analysis", "debates", "judgements", "metadata")
  )
  expect_equal(res_list$metadata$n_total, 1)
  expect_s3_class(res_list, "stance_result")
  
  # Test with list with one invalid element
  chat_list <- list(chat, "chat", chat)
  expect_error(
    llm_stance(
      "Text mining is fun", "Text mining", type = "object",
      chat_base = chat_list, verbose = FALSE, language = "en"
    ),
    "Element 2 of",
    fixed = TRUE
  )
})

test_that("llm_stance.character aborts on invalid language", {
  mockery::stub(llm_stance.character, "stancer_available_languages", c("en", "ru"))

  expect_error(
    llm_stance("text", "target", chat_base = list(), language = "fr"),
    regexp = "not available",
    fixed = FALSE
  )
})

test_that("llm_stance.character: language auto-detection and validation", {
  # stub_llm_stages()
  mockery::stub(llm_stance.character, "validate_character", TRUE)
  mockery::stub(llm_stance.character, "rlang::is_installed", TRUE)
  mockery::stub(llm_stance.character, "cld2::detect_language", "en")
  mockery::stub(llm_stance.character, "templates_collect", list())
  mockery::stub(
    llm_stance.character,
    "stage_1_parallel_analysis",
    function(x, ...) x
  )
  mockery::stub(
    llm_stance.character,
    "stage_2_parallel_debates",
    function(x, ...) x
  )
  mockery::stub(
    llm_stance.character,
    "stage_3_parallel_judgement",
    function(x, ...) {
      x$judgement_results <- data.frame(
        stance = "Negative", explanation = "Content analysis results")
      x
    }
  )
  mockery::stub(llm_stance.character, "validate_stage", function(x, ...) x)

  # 1. Test auto-detection warning
  expect_warning(
    llm_stance(
      "Some English text",
      "Target",
      type = "object",
      chat_base = ellmer::chat_anthropic(echo = "none"),
      language = NULL,
      verbose = FALSE
    ),
    "automatically detected", fixed = TRUE
  )

  # 2. Test error for non-character language input (e.g. numeric)
  expect_error(
    llm_stance("T", "T", chat_base = MockChat$new(), language = 123),
    "must be a character scalar", fixed = TRUE
  )
})

test_that("llm_stance.character: chat_base list length validation", {
  # stub_llm_stages()
  mockery::stub(llm_stance.character, "validate_character", TRUE)
  mockery::stub(llm_stance.character, "rlang::is_installed", TRUE)
  mockery::stub(llm_stance.character, "cld2::detect_language", "en")
  mockery::stub(llm_stance.character, "templates_collect", list())
  mockery::stub(
    llm_stance.character,
    "stage_1_parallel_analysis",
    function(x, ...) x
  )
  mockery::stub(
    llm_stance.character,
    "stage_2_parallel_debates",
    function(x, ...) x
  )
  mockery::stub(
    llm_stance.character,
    "stage_3_parallel_judgement",
    function(x, ...) {
      x$judgement_results <- data.frame(
        stance = "Positive", explanation = "Text mining results")
      x
    }
  )
  mockery::stub(llm_stance.character, "validate_stage", function(x, ...) x)
  chat <- ellmer::chat_mistral(echo = "none")

  # Error for 4 chats
  expect_error(
    llm_stance(
      x = "T",
      target = "T",
      language = "en",
      chat_base = list(chat, chat, chat, chat),
      verbose = FALSE
    ),
    "must have 1, 2, or 3 elements",
    fixed = TRUE
  )

  # Error for invalid object type
  expect_error(
    llm_stance(
      x = "T",
      target = "T",
      chat_base = "not a chat",
      language = "en",
      verbose = FALSE
    ),
    "object or a list of 1-3",
    fixed = TRUE
  )
})

test_that("llm_stance.character: domain_role length validation", {
  # stub_llm_stages()
  mockery::stub(llm_stance.character, "validate_character", TRUE)
  mockery::stub(llm_stance.character, "validate_fields", TRUE)
  mockery::stub(llm_stance.character, "rlang::is_installed", TRUE)
  mockery::stub(llm_stance.character, "cld2::detect_language", "en")
  mockery::stub(llm_stance.character, "templates_collect", list())
  mockery::stub(
    llm_stance.character,
    "stage_1_parallel_analysis",
    function(x, ...) x$analysis_results <- list("L", "D", "SM")
  )
  mockery::stub(
    llm_stance.character,
    "stage_2_parallel_debates",
    function(x, ...) x$debate_results <- list("Pos", "Neu", "Neg")
  )
  mockery::stub(
    llm_stance.character,
    "stage_3_parallel_judgement",
    function(x, ...) {
      x$judgement_results <- data.frame(
        stance = c("Positive", "Neutral", "Negative"),
        explanation = c("E1", "E2", "E3")
      )
      x
    }
  )
  mockery::stub(llm_stance.character, "validate_stage", function(x, ...) x)

  # n = 2, but domain_role = 3
  expect_error(
    llm_stance(
      x = c("T1", "T2"),
      target = "Target",
      chat_base = ellmer::chat_mistral(echo = "none"),
      language = "en",
      domain_role = c("R1", "R2", "R3"),
      verbose = FALSE
    ),
    "must have length 1 or 2",
    fixed = TRUE
  )
  
  # Warning: multiple domain roles
  expect_warning(
    llm_stance(
      x = c("T1", "T2", "T3"),
      target = "Text Mining",
      chat_base = ellmer::chat_mistral(echo = "none"),
      language = "en",
      domain_role = c("D1", "D2", "D3"),
      verbose = TRUE
    ),
    "Multiple domain roles detected",
    fixed = TRUE
  )
})

test_that("llm_stance.character: likert scale post-processing", {
  # Custom stub for stage 3 to return a specific Likert value
  mockery::stub(llm_stance.character, "validate_character", TRUE)
  mockery::stub(llm_stance.character, "templates_collect", list())
  mockery::stub(llm_stance.character, "validate_stage", function(x, ...) x)
  mockery::stub(
    llm_stance.character,
    "stage_1_parallel_analysis",
    function(x, ...) x
  )
  mockery::stub(
    llm_stance.character,
    "stage_2_parallel_debates",
    function(x, ...) x
  )
  mockery::stub(
    llm_stance.character,
    "stage_3_parallel_judgement",
    function(x, ...) {
      x$judgement_results <- data.frame(
        stance = "Strongly Agree",
        explanation = "Likert scale result"
      )
      x
    })

  res <- llm_stance(
    x = "T",
    target = "T",
    type = "statement",
    chat_base = ellmer::chat_mistral(echo = "none"),
    language = "uk",
    scale = "likert",
    verbose = FALSE
  )

  expect_s3_class(res$summary$stance, "factor")
  expect_true(is.ordered(res$summary$stance))
  expect_equal(as.character(res$summary$stance), "Strongly Agree")
})

test_that("llm_stance.character rejects invalid argument values", {
  mockery::stub(llm_stance.character, "validate_character", TRUE)
  
  # Invalid `type`
  expect_error(
    llm_stance(
      "Text mining is interesting",
      target = "Text Mining",
      type = 111L
    ),
    "must be a character vector, got",
    fixed = TRUE
  )
  
  # Invalid `domain_role`
  expect_error(
    llm_stance(
      "Content analysis is interesting",
      target = "Content Analysis is interesting",
      type = "statement",
      language = "en",
      domain_role = 111L
    ),
    "must be a character vector, got",
    fixed = TRUE
  )
})

test_that("llm_stance.character throws error on wrong result length", {
  # Custom stub for stage 3 to return a specific Likert value
  mockery::stub(llm_stance.character, "validate_character", TRUE)
  mockery::stub(llm_stance.character, "templates_collect", list())
  mockery::stub(llm_stance.character, "validate_stage", function(x, ...) x)
  mockery::stub(
    llm_stance.character,
    "stage_1_parallel_analysis",
    function(x, ...) x
  )
  mockery::stub(
    llm_stance.character,
    "stage_2_parallel_debates",
    function(x, ...) x
  )
  mockery::stub(
    llm_stance.character,
    "stage_3_parallel_judgement",
    function(x, ...) {
      x$judgement_results <- data.frame(
        stance = "Strongly Agree",
        explanation = "Likert scale result"
      )
      x
    })

  llm_stance(
    x = c("T1", "T2"),
    target = "T",
    type = "statement",
    chat_base = ellmer::chat_mistral(echo = "none"),
    language = "uk",
    scale = "likert",
    verbose = TRUE
  ) |>
    expect_error(
      "Final stance judgement returned unexpected results",
      fixed = TRUE
    )
})
