# WARNING - Generated by {fusen} from dev/flat_stancer.Rmd: do not edit by hand # nolint: line_length_linter.

# Test 1: abort throws an error
test_that('abort throws an error', {
  expect_error(abort("Test error message"))
})

# Test 2: abort with simple string message
test_that('abort with simple string message', {
  expect_error(
    abort("This is an error"),
    "This is an error",
    fixed = TRUE
  )
})

# Test 3: abort with cli formatting - .arg
test_that('abort with .arg formatting', {
  expect_error(
    abort("{.arg x} must be numeric"),
    "must be numeric",
    fixed = TRUE
  )
})

# Test 4: abort with cli formatting - .val
test_that('abort with .val formatting', {
  expect_error(
    abort("Invalid value: {.val {5}}"),
    "Invalid value",
    fixed = TRUE
  )
})

# Test 5: abort with cli formatting - .cls
test_that('abort with .cls formatting', {
  expect_error(
    abort("Expected {.cls character}, got {.cls numeric}"),
    "Expected",
    fixed = TRUE
  )
})

# Test 6: abort with multiple cli formatting elements
test_that('abort with multiple formatting elements', {
  expect_error(
    abort(
      "Argument {.arg x} must be {.cls numeric}, not {.cls list}"
    ),
    "must be",
    fixed = TRUE
  )
})

# Test 7: abort with interpolation - variable substitution
test_that('abort with variable interpolation', {
  var_name <- "test_var"
  expect_error(
    abort("Variable '{var_name}' not found"),
    "test_var",
    fixed = TRUE
  )
})

# Test 8: abort with complex interpolation
test_that('abort with complex interpolation', {
  lang <- "en"
  expect_error(
    abort("Language '{lang}' not available"),
    "Language 'en' not available",
    fixed = TRUE
  )
})

# Test 9: abort preserves error class
test_that('abort creates rlang_error', {
  expect_error(
    abort("Test error"),
    class = "rlang_error"
  )
})

# Test 10: abort with empty message
test_that('abort with empty message', {
  expect_error(abort(""))
})

# Test 11: abort with very long message
test_that('abort with long message', {
  long_msg <- paste(rep("a", 1000), collapse = "")
  expect_error(abort(long_msg))
})

# Test 12: abort with special characters
test_that('abort with special characters', {
  expect_error(
    abort("Error with special chars: @#$%^&*()"),
    "special chars",
    fixed = TRUE
  )
})

# Test 13: abort with quotes in message
test_that('abort with quotes in message', {
  expect_error(
    abort('Error with "double" and \'single\' quotes'),
    "quotes",
    fixed = TRUE
  )
})

# Test 14: abort with list formatting
test_that('abort with list formatting', {
  expect_error(
    abort("Available options: {.val {c('a', 'b', 'c')}}"),
    "Available",
    fixed = TRUE
  )
})

# Test 15: abort with vector in message
test_that('abort with vector interpolation', {
  vals <- c("x", "y", "z")
  expect_error(
    abort("Invalid values: {.val {vals}}"),
    "Invalid",
    fixed = TRUE
  )
})

# Test 16: abort with numeric values in message
test_that('abort with numeric interpolation', {
  n <- 111
  expect_error(
    abort("Expected {n} items, got 0"),
    "Expected 111",
    fixed = TRUE
  )
})

# Test 17: abort with logical values in message
test_that('abort with logical values', {
  flag <- TRUE
  expect_error(
    abort("Flag is {flag}"),
    "Flag is TRUE",
    fixed = TRUE
  )
})

# Test 18: abort with NA values
test_that('abort with NA values', {
  na_val <- NA
  expect_error(
    abort("Value is {na_val}"),
    "Value",
    fixed = TRUE
  )
})

# Test 19: abort with function name in message
test_that('abort with function reference', {
  expect_error(
    abort("Function {.fn truncate} failed"),
    "failed",
    fixed = TRUE
  )
})

# Test 20: abort uses caller environment
test_that('abort uses caller environment', {
  test_var <- "from_caller"
  expect_error(
    abort("Variable: {test_var}"),
    "from_caller",
    fixed = TRUE
  )
})

# Test 21: abort in nested function call
test_that('abort in nested function', {
  inner_func <- function() {
    abort("Error from inner function")
  }

  outer_func <- function() {
    inner_func()
  }

  expect_error(
    outer_func(),
    "Error from inner function",
    fixed = TRUE
  )
})

# Test 22: abort does not return value (throws immediately)
test_that('abort does not return', {
  result <- tryCatch(
    {
      abort("Test")
      "should not reach here"
    },
    error = function(e) {
      "caught error"
    }
  )
  expect_equal(result, "caught error")
})

# Test 23: abort with .arg and variable
test_that('abort with .arg and variable name', {
  param_name <- "data"
  expect_error(
    abort("Argument {.arg {param_name}} is invalid"),
    "invalid",
    fixed = TRUE
  )
})

# Test 24: abort with .cls and actual class
test_that('abort with .cls and object class', {
  obj <- list(a = 1)
  expect_error(
    abort("Expected data.frame, got {.cls {class(obj)}}"),
    "Expected",
    fixed = TRUE
  )
})

# Test 25: abort with multiple .val elements
test_that('abort with multiple .val elements', {
  expect_error(
    abort(
      "Got {.val {1}}, expected one of {.val {c(2, 3, 4)}}"
    ),
    "Got",
    fixed = TRUE
  )
})

# Test 26: abort preserves message formatting
test_that('abort message is not modified', {
  msg <- "Exact error message"
  tryCatch(
    abort(msg),
    error = function(e) {
      expect_true(grepl(msg, conditionMessage(e), fixed = TRUE))
    }
  )
})

# Test 27: abort called multiple times creates different errors
test_that('multiple abort calls create separate errors', {
  error1 <- tryCatch(
    abort("Error 1"),
    error = function(e) e
  )

  error2 <- tryCatch(
    abort("Error 2"),
    error = function(e) e
  )

  expect_true(grepl("Error 1", conditionMessage(error1)))
  expect_true(grepl("Error 2", conditionMessage(error2)))
  expect_false(identical(error1, error2))
})

# Test 28: abort with complex nested formatting
test_that('abort with complex nested formatting', {
  lang <- "en"
  available <- c("en", "ru", "fr")
  expect_error(
    abort(
      "Language '{lang}' not available. Use: {.val {available}}"
    ),
    "not available",
    fixed = TRUE
  )
})

# Test 29: abort requires exactly one argument
test_that('abort requires msg argument', {
  expect_error(abort(), "missing", fixed = TRUE)
})

# Test 30: abort with NULL message
test_that('abort with NULL message', {
  expect_error(abort(NULL), 'must be supplied', fixed = TRUE)
})

# Test 31: abort with numeric message (coerced to string)
test_that('abort with numeric message', {
  expect_error(
    abort(123),
    "123",
    fixed = TRUE
  )
})

# Test 32: abort with expression in message
test_that('abort with expression evaluation', {
  x <- 5
  y <- 3
  expect_error(
    abort("Sum is {x + y}"),
    "Sum is 8",
    fixed = TRUE
  )
})

# Test 33: abort message with unicode characters
test_that('abort with unicode characters', {
  expect_error(
    abort("Hello \U1F680"),
    "Hello",
    fixed = TRUE
  )
})
