# WARNING - Generated by {fusen} from dev/flat_stancer.Rmd: do not edit by hand # nolint: line_length_linter.

# Reusing the MockChat
MockChat <- R6::R6Class(
  "MockChat",
  public = list(
    system_prompt = NULL,
    set_system_prompt = function(prompt) {
      self$system_prompt <- prompt
    },
    chat = function(..., echo = NULL) paste("Response", seq_along(list(...)))
  )
)

test_that("prepare_debater_chats correctly passes Stage 1 results to prompts_prepare", {
  # 1. Set-up Data
  inputs <- list(
    texts = "Text 1",
    targets = "Target 1",
    target_types = "statement",
    language = "en",
    prompt_templates = list(t = "inst/prompts"),
    analysis_results = list(
      linguistic = "Linguistic Analysis",
      domain = "Domain Expert Analysis",
      social_media = "Social Media Analysis"
    )
  )

  # 2. Mock prompts_prepare to verify arguments
  mock_prompts <- mockery::mock(list(
    system = "System Prompt",
    user = "User Prompt"
  ))
  mockery::stub(prepare_debater_chats, "prompts_prepare", mock_prompts)

  # Mock tasks_prepare to return a standard structure
  mockery::stub(prepare_debater_chats, "tasks_prepare", list(chats = list(1), tasks = "T"))

  # 3. Execute
  prepare_debater_chats("negative", inputs, MockChat$new())

  # 4. Verify arguments passed to prompts_prepare
  args <- mockery::mock_args(mock_prompts)[[1]]
  expect_equal(args[[1]], "debater")
  expect_equal(args$stance, "negative")
  expect_equal(args$LingResponse, "Linguistic Analysis")
  expect_equal(args$ExpertResponse, "Domain Expert Analysis")
  expect_equal(args$UserResponse, "Social Media Analysis")
})

test_that("prepare_debater_chats aborts if multiple system prompts are generated", {
  # Mock prompts_prepare to return 2 system prompts
  mockery::stub(prepare_debater_chats, "prompts_prepare", list(
    system = c("System 1", "System 2"),
    user = c("User 1", "User 2")
  ))

  inputs <- list(texts = c("T1", "T2"), analysis_results = list())

  # Check for our custom abort message
  expect_error(
    prepare_debater_chats("con", inputs, MockChat$new()),
    regexp = "Multiple system prompts are not allowed at stage 2"
  )
})

test_that("prepare_debater_chats returns tasks_prepare output on success", {
  mockery::stub(prepare_debater_chats, "prompts_prepare", list(
    system = "Single System",
    user = "User Prompt"
  ))

  expected_output <- list(chats = list("MockChatObject"), tasks = "Final Prompt")
  mockery::stub(prepare_debater_chats, "tasks_prepare", expected_output)

  res <- prepare_debater_chats("neutral", list(texts = "T1"), MockChat$new())
  expect_equal(res, expected_output)
})

test_that("prepare_debater_chats fails with multiple system prompts", {
  mockery::stub(prepare_debater_chats, "prompts_prepare", list(
    system = c("System Prompt 1", "System Prompt 2"),
    user = "User Prompt"
  ))

  expect_error(
    prepare_debater_chats("positive", list(texts = "T1"), MockChat$new()),
    "Multiple system prompts are not allowed at stage 2",
    fixed = TRUE
  )
})
