# WARNING - Generated by {fusen} from dev/flat_stancer.Rmd: do not edit by hand # nolint: line_length_linter.

# Reusing the MockChat
MockChat <- R6::R6Class(
  "MockChat",
  public = list(
    system_prompt = NULL,
    set_system_prompt = function(prompt) {
      self$system_prompt <- prompt
    }
  )
)

test_that("stage_1_parallel_analysis validates inputs and returns results", {
  # 1. Set-up Data
  inputs <- list(
    texts = c("T1", "T2"),
    targets = c("A", "B"),
    target_types = c("statement", "statement"),
    language = "en",
    domain_roles = "AI Expert",
    prompt_templates = list(a = 1)
  )

  # 2. Set-up Mocks
  # Mock validate_fields to just pass
  mockery::stub(stage_1_parallel_analysis, "validate_fields", TRUE)

  # Mock execute_role to return role-specific strings
  mock_execute <- mockery::mock(
    c("L1", "L2"), # First call: linguist
    c("D1", "D2"), # Second call: domain
    c("S1", "S2")  # Third call: interpreter
  )
  mockery::stub(stage_1_parallel_analysis, "execute_role", mock_execute)

  # Mock tictoc to avoid console noise/errors
  mockery::stub(stage_1_parallel_analysis, "tictoc::tic", NULL)
  mockery::stub(stage_1_parallel_analysis, "tictoc::toc", NULL)

  # 3. Execute
  result <- stage_1_parallel_analysis(
    inputs,
    chat_base = MockChat$new(),
    verbose = FALSE
  )

  # 4. Verify
  expect_true("analysis_results" %in% names(result))
  expect_named(result$analysis_results, c("linguistic", "domain", "social_media"))
  expect_equal(result$analysis_results$linguistic, c("L1", "L2"))
  expect_equal(result$analysis_results$domain, c("D1", "D2"))
  expect_equal(result$analysis_results$social_media, c("S1", "S2"))

  # Verify execute_role was called exactly 3 times
  mockery::expect_called(mock_execute, 3)
})

test_that("stage_1_parallel_analysis fails if required fields are missing", {
  # Missing domain_roles
  incomplete_inputs <- list(
    texts = "T1",
    targets = "X",
    target_types = "statement",
    language = "en",
    prompt_templates = list()
  )

  # We don't stub validate_fields here because we want to test that it's actually called
  # and catches the error as expected.
  mockery::stub(stage_1_parallel_analysis, "validate_fields", validate_fields)
  expect_error(
    stage_1_parallel_analysis(incomplete_inputs, MockChat$new(), verbose = FALSE),
    regexp = "misses required fields: `domain_roles`"
  )
})

test_that("stage_1_parallel_analysis respects verbose flag", {
  inputs <- list(
    texts = "T1", targets = "A", target_types = "statement",
    language = "en", domain_roles = "AI Expert", prompt_templates = list()
  )

  mockery::stub(stage_1_parallel_analysis, "validate_fields", TRUE)
  mockery::stub(stage_1_parallel_analysis, "execute_role", list("Result"))
  mockery::stub(stage_1_parallel_analysis, "tictoc::tic", NULL)
  mockery::stub(stage_1_parallel_analysis, "tictoc::toc", NULL)

  expect_output(
    stage_1_parallel_analysis(inputs, MockChat$new(), verbose = TRUE),
    regexp = "Stage 1: Expert analysis"
  )

  expect_silent(
    stage_1_parallel_analysis(inputs, MockChat$new(), verbose = FALSE)
  )
})
