# WARNING - Generated by {fusen} from dev/flat_stancer.Rmd: do not edit by hand # nolint: line_length_linter.

test_that('load_translations is a function', {
  expect_true(inherits(load_translations, 'function'))
})

test_that('load_translations works', {
  expect_no_error(dict <- load_translations())
  expect_is(dict, 'list')
  expect_named(dict, c('en', 'uk', 'ru'))
})
