# WARNING - Generated by {fusen} from dev/flat_stancer.Rmd: do not edit by hand # nolint: line_length_linter.

# Reusing the MockChat
MockChat <- R6::R6Class(
  "MockChat",
  public = list(
    system_prompt = NULL,
    set_system_prompt = function(prompt) {
      self$system_prompt <- prompt
    },
    chat = function(..., echo = NULL) paste("Response", seq_along(list(...)))
  )
)

test_that("prepare_judger_chats correctly passes Stage 2 results and flags", {
  # 1. Set-up Data
  inputs <- list(
    texts = "Text 1",
    targets = "Target 1",
    target_types = "statement",
    language = "en",
    types = c("statement"), # Should trigger add_reference_resolution
    prompt_templates = list(t = "file"),
    debate_results = list(
      positive = "Pos Debate",
      negative = "Neg Debate",
      neutral = "Neu Debate"
    )
  )

  # 2. Mock prompts_prepare to verify arguments
  mock_prompts <- mockery::mock(
    list(
      system = "System Prompt",
      user = "User Prompt"
    )
  )
  mockery::stub(prepare_judger_chats, "prompts_prepare", mock_prompts)
  mockery::stub(
    prepare_judger_chats,
    "tasks_prepare",
    list(chats = list(1), tasks = "T")
  )

  # 3. Execute
  prepare_judger_chats(inputs, MockChat$new())

  # 4. Verify arguments passed to prompts_prepare
  mockery::expect_called(mock_prompts, 1)
  args <- mockery::mock_args(mock_prompts)[[1]]
  expect_equal(args[[1]], "judger")
  expect_equal(args$target_type, "statement")
  expect_equal(args$FavourResponse, "Pos Debate")
  expect_equal(args$AgainstResponse, "Neg Debate")
  expect_equal(args$NeutralResponse, "Neu Debate")

  # Verify conditional flags
  expect_false(args$add_reference_resolution)
  expect_true(args$add_statement_resolution)
})

test_that("prepare_judger_chats aborts if multiple system prompts are generated", {
  mockery::stub(prepare_judger_chats, "prompts_prepare", list(
    system = c("Sys 1", "Sys 2"),
    user = c("User 1", "User 2")
  ))

  inputs <- list(texts = c("T1", "T2"), types = "statement", debate_results = list())

  expect_error(
    prepare_judger_chats(inputs, MockChat$new()),
    regexp = "Multiple system prompts are not allowed at stage 3",
    fixed = TRUE
  )
})

test_that("prepare_judger_chats correctly handles statement resolution flag", {
  inputs <- list(
    texts = "T1", targets = "A", target_types = "statement", language = "en",
    types = "statement", # Should trigger add_statement_resolution
    prompt_templates = list(),
    debate_results = list(positive = "P", negative = "N", neutral = "Neu")
  )

  mock_prompts <- mockery::mock(list(system = "S", user = "U"))
  mockery::stub(prepare_judger_chats, "prompts_prepare", mock_prompts)
  mockery::stub(prepare_judger_chats, "tasks_prepare", list())

  prepare_judger_chats(inputs, MockChat$new())

  mockery::expect_called(mock_prompts, 1)
  args <- mockery::mock_args(mock_prompts)[[1]]
  expect_false(args$add_reference_resolution)
  expect_true(args$add_statement_resolution)
})
