# WARNING - Generated by {fusen} from dev/flat_stancer.Rmd: do not edit by hand # nolint: line_length_linter.

test_that('stancer_available_languages is a function', {
  expect_true(inherits(stancer_available_languages, 'function'))
})

test_that('load_translations works', {
  expect_no_error(stancer_available_languages())
  expect_is(stancer_available_languages(), 'character')
  expect_equal(stancer_available_languages(), c('en', 'uk', 'ru'))
})
