# WARNING - Generated by {fusen} from dev/flat_stancer.Rmd: do not edit by hand # nolint: line_length_linter.

# Test 1: l() returns simple string translation without case
test_that('l() returns simple string translation', {
  result <- l(language = "en", caption_id = "analysis")
  expect_equal(result, "Text analysis for")
  expect_type(result, "character")
})

# Test 2: l() returns translation with case parameter
test_that('l() returns translation with case', {
  result <- l(language = "en", caption_id = "object", case = "gen")
  expect_equal(result, "the object")
})

# Test 3: l() rejects invalid language
test_that('l() rejects invalid language', {
  expect_error(
    l(language = "fr", caption_id = "analysis"),
    "Language 'fr' not available",
    fixed = TRUE
  )
})

# Test 4: l() rejects invalid caption_id
test_that('l() rejects invalid caption_id', {
  expect_error(
    l(language = "en", caption_id = "nonexistent"),
    "Caption ID 'nonexistent' not found",
    fixed = TRUE
  )
})

# Test 5: l() rejects invalid case value
test_that('l() rejects invalid case value', {
  expect_error(
    l(language = "en", caption_id = "object", case = "invalid"),
    "must be one of",
    fixed = TRUE
  )
})

# Test 6: l() requires case for dictionary entries with cases
test_that('l() requires case for multi-case entries', {
  expect_error(
    l(language = "en", caption_id = "object"),
    "Case required for 'object'",
    fixed = TRUE
  )
})

# Test 7: l() rejects case for simple string entries
test_that('l() rejects case for simple string entries', {
  expect_error(
    l(language = "en", caption_id = "analysis", case = "gen"),
    "Case 'gen' not supported for 'analysis'",
    fixed = TRUE
  )
})

# Test 8: l() rejects missing case in multi-case entry
test_that('l() rejects missing case in entry', {
  expect_error(
    l(language = "en", caption_id = "stance_positive", case = "ablative"),
    "must be one of",
    fixed = TRUE
  )
})

# Test 9: l() works with different languages
test_that('l() works with Ukrainian translation', {
  result <- l(language = "uk", caption_id = "analysis")
  expect_equal(result, "Аналіз тексту для")
})

# Test 10: l() works with Russian translation
test_that('l() works with Russian translation', {
  result <- l(language = "ru", caption_id = "stage_1")
  expect_equal(result, "Проведение многомерного анализа")
})

# Test 11: l() returns correct case variant
test_that('l() returns correct case variant for different cases', {
  gen <- l(language = "en", caption_id = "statement", case = "gen")
  dat <- l(language = "en", caption_id = "statement", case = "dat")
  expect_equal(gen, "the statement")
  expect_equal(dat, "the following statement:")
  expect_true(gen != dat)
})

# Test 12: l() works with numeric case type
test_that('l() works with numeric case type', {
  result <- l(language = "en", caption_id = "stance_positive", case = "numeric")
  expect_equal(result, "positive, near 1")
})

# Test 13: l() works with likert case type
test_that('l() works with likert case type', {
  result <- l(language = "ru", caption_id = "stance_neutral", case = "likert")
  expect_equal(result, "нейтральная")
})
