# WARNING - Generated by {fusen} from dev/flat_stancer.Rmd: do not edit by hand # nolint: line_length_linter.

# Reusing the MockChat
MockChat <- R6::R6Class(
  "MockChat",
  public = list(
    system_prompt = NULL,
    set_system_prompt = function(prompt) {
      self$system_prompt <- prompt
    },
    chat = function(..., echo = NULL) paste("Response", seq_along(list(...)))
  )
)

test_that("execute_role uses parallel execution when there is one chat object", {
  # 1. Set-up Mocks
  mockery::stub(
    execute_role,
    "prepare_expert_chats",
    list(
      chats = list(MockChat$new()), # Only 1 chat -> parallel
      tasks = c("Content Analysis Prompt 1", "Content Analysis Prompt 2")
    )
  )

  mock_parallel <- mockery::mock(c("Response A", "Response B"))
  mockery::stub(execute_role, "ellmer::parallel_chat_text", mock_parallel)

  inputs <- list(texts = c("T1", "T2"))

  # 2. Execute
  res <- execute_role(
    "linguist", inputs, MockChat$new(), "Testing Parallel", verbose = FALSE
  )

  # 3. Verify
  expect_equal(res, c("Response A", "Response B"))
  mockery::expect_called(mock_parallel, 1)
  # Check arguments passed to parallel_chat_text
  args <- mockery::mock_args(mock_parallel)[[1]]
  expect_equal(
    args$prompts,
    c("Content Analysis Prompt 1", "Content Analysis Prompt 2")
  )
})

test_that("execute_role uses sequential execution when there are multiple chats", {
  # 1. Set-up Mocks
  chat1 <- MockChat$new()
  chat2 <- MockChat$new()

  mockery::stub(
    execute_role,
    "prepare_expert_chats",
    list(
      chats = list(chat1, chat2), # 2 chats -> sequential
      tasks = c("Task 1", "Task 2")
    )
  )

  inputs <- list(texts = c("T1", "T2"))

  # 2. Execute
  res <- execute_role(
    "domain", inputs, MockChat$new(), "Testing Sequential", verbose = FALSE
  )

  # 3. Verify
  expect_equal(res, c("Response 1", "Response 1"))
  # For every Chat, there is only one response
})

test_that("execute_role throws error if output length is mismatched", {
  mockery::stub(
    execute_role,
    "prepare_expert_chats",
    list(chats = list(MockChat$new()), tasks = c("P1", "P2"))
  )

  # Parallel returns only 1 response for 2 inputs
  mockery::stub(execute_role, "ellmer::parallel_chat_text", "Single Response")

  inputs <- list(texts = c("T1", "T2"))

  expect_error(
    execute_role("linguist", inputs, MockChat$new(), "Error Test", verbose = FALSE),
    regexp = "Input and output lengths differ",
    fixed = TRUE
  )
})

test_that("execute_role prints progress message when verbose is TRUE", {
  mockery::stub(
    execute_role,
    "prepare_expert_chats",
    list(chats = list(MockChat$new()), tasks = "P1")
  )
  mockery::stub(execute_role, "ellmer::parallel_chat_text", "Result A")

  expect_output(
    execute_role(
      "linguist", list(texts = "T1"), MockChat$new(), "MyInfo", verbose = TRUE
    ),
    regexp = "MyInfo..."
  )
})
