# WARNING - Generated by {fusen} from dev/flat_stancer.Rmd: do not edit by hand # nolint: line_length_linter.

test_that('load_translations is a function', {
  expect_true(inherits(load_translations, 'function'))
})

test_that('load_translations works', {
  expect_no_error(dict <- load_translations())
  expect_is(dict, 'list')
  expect_named(dict, c('en', 'uk', 'ru'))
})

test_that('stancer_available_languages is a function', {
  expect_true(inherits(stancer_available_languages, 'function'))
})

test_that('stancer_available_languages works', {
  expect_no_error(stancer_available_languages())
  expect_is(stancer_available_languages(), 'character')
  expect_equal(stancer_available_languages(), c('en', 'uk', 'ru'))
})

# Test 1: l() returns simple string translation without case
test_that('l() returns simple string translation', {
  result <- l(language = "en", caption_id = "analysis")
  expect_equal(result, "Text analysis for")
  expect_type(result, "character")
})

# Test 2: l() returns translation with case parameter
test_that('l() returns translation with case', {
  result <- l(language = "en", caption_id = "object", case = "gen")
  expect_equal(result, "the object")
})

# Test 3: l() rejects invalid language
test_that('l() rejects invalid language', {
  expect_error(
    l(language = "fr", caption_id = "analysis"),
    "Language 'fr' not available",
    fixed = TRUE
  )
})

# Test 4: l() rejects invalid caption_id
test_that('l() rejects invalid caption_id', {
  expect_error(
    l(language = "en", caption_id = "nonexistent"),
    "Caption ID 'nonexistent' not found",
    fixed = TRUE
  )
})

# Test 5: l() rejects invalid case value
test_that('l() rejects invalid case value', {
  expect_error(
    l(language = "en", caption_id = "object", case = "invalid"),
    "must be one of",
    fixed = TRUE
  )
})

# Test 5a: l() rejects non-matching case value
test_that('l() rejects non-matching case value', {
  expect_error(
    l(language = "en", caption_id = "statement", case = "likert"),
    "not found for",
    fixed = TRUE
  )
})

# Test 6: l() requires case for dictionary entries with cases
test_that('l() requires case for multi-case entries', {
  expect_error(
    l(language = "en", caption_id = "object"),
    "Case required for 'object'",
    fixed = TRUE
  )
})

# Test 7: l() rejects case for simple string entries
test_that('l() rejects case for simple string entries', {
  expect_error(
    l(language = "en", caption_id = "analysis", case = "gen"),
    "Case 'gen' not supported for 'analysis'",
    fixed = TRUE
  )
})

# Test 8: l() rejects missing case in multi-case entry
test_that('l() rejects missing case in entry', {
  expect_error(
    l(language = "en", caption_id = "stance_positive", case = "ablative"),
    "must be one of",
    fixed = TRUE
  )
})

# Test 9: l() works with different languages
test_that('l() works with Ukrainian translation', {
  result <- l(language = "uk", caption_id = "analysis")
  expect_equal(result, "Аналіз тексту для")
})

# Test 10: l() works with Russian translation
test_that('l() works with Russian translation', {
  result <- l(language = "ru", caption_id = "stage_1")
  expect_equal(result, "Проведение многомерного анализа")
})

# Test 11: l() returns correct case variant
test_that('l() returns correct case variant for different cases', {
  gen <- l(language = "en", caption_id = "statement", case = "gen")
  dat <- l(language = "en", caption_id = "statement", case = "dat")
  expect_equal(gen, "the statement")
  expect_equal(dat, "the following statement:")
  expect_true(gen != dat)
})

# Test 12: l() works with numeric case type
test_that('l() works with numeric case type', {
  result <- l(language = "en", caption_id = "stance_positive", case = "numeric")
  expect_equal(result, "positive, near 1")
})

# Test 13: l() works with likert case type
test_that('l() works with likert case type', {
  result <- l(language = "ru", caption_id = "stance_neutral", case = "likert")
  expect_equal(result, "нейтральная")
})

test_that('stancer_check_translations returns invisibly TRUE', {
  result <- stancer_check_translations()
  expect_true(result)
  expect_invisible(stancer_check_translations())
})

test_that('stancer_check_translations prints available languages', {
  expect_output(
    stancer_check_translations(),
    "Available languages:"
  )
})

test_that('stancer_check_translations lists all languages', {
  expect_output(
    stancer_check_translations(),
    "en"
  )
  expect_output(
    stancer_check_translations(),
    "uk"
  )
  expect_output(
    stancer_check_translations(),
    "ru"
  )
})

test_that('stancer_check_translations shows key count per language', {
  expect_output(
    stancer_check_translations(),
    "Language: en"
  )
  expect_output(
    stancer_check_translations(),
    "Keys: \\d+"
  )
})

test_that('stancer_check_translations identifies keys with cases', {
  expect_output(
    stancer_check_translations(),
    "Keys with cases:"
  )
})

test_that('stancer_check_translations output is consistent', {
  output1 <- capture.output(stancer_check_translations())
  output2 <- capture.output(stancer_check_translations())
  expect_equal(output1, output2)
})

test_that('stancer_check_translations handles all languages equally', {
  output <- capture.output(stancer_check_translations())

  # Проверяем, что каждый язык имеет свою секцию
  en_count <- sum(grepl("Language: en", output))
  uk_count <- sum(grepl("Language: uk", output))
  ru_count <- sum(grepl("Language: ru", output))

  expect_equal(en_count, 1)
  expect_equal(uk_count, 1)
  expect_equal(ru_count, 1)
})

# Test 1: type_to_term returns correct term for object type
test_that('type_to_term returns object term in English', {
  result <- type_to_term(type = "object", language = "en")
  expect_equal(result, "the object")
})

# Test 2: type_to_term returns correct term for statement type
test_that('type_to_term returns statement term in English', {
  result <- type_to_term(type = "statement", language = "en")
  expect_equal(result, "the following statement:")
})

# Test 3: type_to_term works with Ukrainian language
test_that('type_to_term works with Ukrainian', {
  result <- type_to_term(type = "object", language = "uk")
  expect_equal(result, "об'єкту")
})

# Test 4: type_to_term works with Russian language
test_that('type_to_term works with Russian', {
  result <- type_to_term(type = "statement", language = "ru")
  expect_equal(result, "суждению")
})

# Test 5: type_to_term rejects invalid type
test_that('type_to_term rejects invalid type', {
  expect_error(
    type_to_term(type = "invalid", language = "en"),
    "must be one of",
    fixed = TRUE
  )
})

# Test 6: type_to_term rejects invalid language
test_that('type_to_term rejects invalid language', {
  expect_error(
    type_to_term(type = "object", language = "fr"),
    "must be one of",
    fixed = TRUE
  )
})

# Test 7: type_to_term uses dative case (dat) for all terms
test_that('type_to_term uses dative case', {
  # Проверяем, что используется именно дательный падеж (dat), а не именительный (gen)
  object_dat <- type_to_term(type = "object", language = "en")
  # Для английского "the object" одинаков, но проверяем логику
  expect_type(object_dat, "character")
  expect_length(object_dat, 1)
})

# Test 8: type_to_term returns character string
test_that('type_to_term returns character string', {
  result <- type_to_term(type = "object", language = "en")
  expect_type(result, "character")
  expect_length(result, 1)
})

# Test 9: type_to_term works with all available languages
test_that('type_to_term works with all available languages', {
  available_langs <- stancer_available_languages()

  for (lang in available_langs) {
    result_obj <- type_to_term(type = "object", language = lang)
    result_stmt <- type_to_term(type = "statement", language = lang)

    expect_type(result_obj, "character")
    expect_type(result_stmt, "character")
    expect_length(result_obj, 1)
    expect_length(result_stmt, 1)
  }
})

# Test 10: type_to_term returns different terms for different types
test_that('type_to_term returns different terms for different types', {
  object_term <- type_to_term(type = "object", language = "en")
  statement_term <- type_to_term(type = "statement", language = "en")

  expect_false(object_term == statement_term)
})
