# WARNING - Generated by {fusen} from dev/flat_stancer.Rmd: do not edit by hand # nolint: line_length_linter.

# Reusing the MockChat
MockChat <- R6::R6Class(
  "MockChat",
  public = list(
    system_prompt = NULL,
    set_system_prompt = function(prompt) {
      self$system_prompt <- prompt
    },
    chat = function(..., echo = NULL) paste("Response", seq_along(list(...)))
  )
)

test_that("stage_3_parallel_judgement executes structured chat with correct schema", {
  # 1. Setup Data
  inputs <- list(
    texts = c("T1", "T2"),
    targets = c("A", "B"),
    types = c("statement", "statement"),
    target_types = c("statement", "statement"),
    language = "en",
    scale = "likert",
    prompt_templates = list(scale_description = "Desc"),
    debate_results = list(
      positive = c("P1", "P2"),
      negative = c("N1", "N2"),
      neutral = c("Neu1", "Neu2")
    )
  )

  # 2. Setup Mocks
  # mockery::stub(stage_3_parallel_judgement, "validate_fields", TRUE)
  # mockery::stub(stage_3_parallel_judgement, "validate_inputs", TRUE)
  mockery::stub(stage_3_parallel_judgement, "tictoc::tic", NULL)
  mockery::stub(stage_3_parallel_judgement, "tictoc::toc", NULL)

  # Mock schema generator
  mockery::stub(stage_3_parallel_judgement, "type_stance_analysis", "mock_schema")

  # Mock prepare_judger_chats
  mockery::stub(stage_3_parallel_judgement, "prepare_judger_chats", list(
    chats = list(MockChat$new()),
    tasks = c("Task 1", "Task 2")
  ))

  # Mock parallel_chat_structured
  mock_results <- data.frame(
    stance = c("Strongly Disagree", "Agree"),
    reasoning = c("R1", "R2")
  )
  mock_parallel <- mockery::mock(mock_results)
  mockery::stub(
    stage_3_parallel_judgement,
    "ellmer::parallel_chat_structured",
    mock_parallel
  )

  # 3. Execute
  result <- stage_3_parallel_judgement(inputs, MockChat$new(), verbose = FALSE)

  # 4. Verify
  mockery::expect_called(mock_parallel, 1)
  expect_equal(result$judgement_results, mock_results)

  # Verify arguments passed to parallel_chat_structured
  args <- mockery::mock_args(mock_parallel)[[1]]
  expect_equal(args$type, "mock_schema")
  expect_true(args$convert)
})

test_that("stage_3_parallel_judgement warns when NA stances are returned", {
  inputs <- list(
    texts = "T1", targets = "A", types = "statement", target_types = "statement",
    language = "en", scale = "likert", prompt_templates = list(),
    debate_results = list(positive = "P", negative = "N", neutral = "Neu")
  )

  # mockery::stub(stage_3_parallel_judgement, "validate_fields", TRUE)
  # mockery::stub(stage_3_parallel_judgement, "validate_inputs", TRUE)
  mockery::stub(
    stage_3_parallel_judgement,
    "prepare_judger_chats",
    list(chats = list(1), tasks = "T")
  )
  mockery::stub(stage_3_parallel_judgement, "type_stance_analysis", "likert schema")

  # Return a result with NA stance
  mock_results <- data.frame(stance = NA_real_, explanation = "AI has failed")
  mockery::stub(
    stage_3_parallel_judgement,
    "ellmer::parallel_chat_structured",
    mock_results
  )

  # Expect warning from cli::cli_warn
  expect_warning(
    stage_3_parallel_judgement(inputs, MockChat$new(), verbose = FALSE),
    regexp = "1 item returned NA stance",
    fixed = TRUE
  )
})

test_that("stage_3_parallel_judgement passes additional arguments (...) to parallel call", {
  inputs <- list(
    texts = "T1", targets = "A", types = "statement", target_types = "statement",
    language = "en", scale = "likert", prompt_templates = list(),
    debate_results = list(positive = "P", negative = "N", neutral = "Neu")
  )

  # mockery::stub(stage_3_parallel_judgement, "validate_fields", TRUE)
  # mockery::stub(stage_3_parallel_judgement, "validate_inputs", TRUE)
  mockery::stub(stage_3_parallel_judgement, "type_stance_analysis", "likert schema")
  mockery::stub(
    stage_3_parallel_judgement,
    "prepare_judger_chats",
    list(chats = list(1), tasks = "T")
  )

  mock_parallel <- mockery::mock(
    data.frame(stance = "Strongly Agree", explanation = "AI Content Analysis")
  )
  mockery::stub(
    stage_3_parallel_judgement,
    "ellmer::parallel_chat_structured",
    mock_parallel
  )

  # Pass a custom argument like 'max_tokens'
  stage_3_parallel_judgement(
    inputs,
    MockChat$new(),
    verbose = FALSE,
    rpm = 111,
    max_active = 12,
    on_error = "stop"
  )

  args <- mockery::mock_args(mock_parallel)[[1]]
  expect_equal(args$max_active, 12)
  expect_equal(args$on_error, "stop")
  expect_equal(args$rpm, 111)
})
