# WARNING - Generated by {fusen} from dev/flat_stancer.Rmd: do not edit by hand # nolint: line_length_linter.

# Test 1: catch executes expression successfully
test_that('catch executes expression without error', {
  expect_no_error(catch(1 + 1))
})

# Test 2: catch with variable assignment
test_that('catch evaluates expression with variables', {
  x <- 5
  result <- catch(x * 2)
  expect_equal(result, 10)
})

# Test 3: catch with function call
test_that('catch executes function call', {
  result <- catch(sqrt(16))
  expect_equal(result, 4)
})

# Test 4: catch catches errors and wraps them
test_that('catch catches error and wraps message', {
  expect_error(
    catch(stop("Original error")),
    "Error in",
    fixed = TRUE
  )
})

# Test 5: catch preserves original error message
test_that('catch preserves original error message', {
  expect_error(
    catch(stop("Original error")),
    "Original error",
    fixed = TRUE
  )
})

# Test 6: catch with custom expr_name
test_that('catch with custom expr_name parameter', {
  expect_error(
    catch(stop("Test"), expr_name = "custom_operation"),
    "Error in custom_operation",
    fixed = TRUE
  )
})

# Test 7: catch with default expr_name from deparse
test_that('catch uses deparse(substitute(expr)) for default name', {
  expect_error(
    catch(1 / "1"),
    "Error in 1",
    fixed = TRUE
  )
})

# Test 8: catch rejects non-character expr_name
test_that('catch rejects non-character expr_name', {
  expect_error(
    catch(1 + 1, expr_name = 123),
    "must be a character scalar",
    fixed = TRUE
  )
})

# Test 9: catch rejects non-scalar character expr_name
test_that('catch rejects non-scalar character expr_name', {
  expect_error(
    catch(1 + 1, expr_name = c("a", "b")),
    "must be a character scalar",
    fixed = TRUE
  )
})

# Test 10: catch with complex expression
test_that('catch evaluates complex expression', {
  result <- catch({
    x <- 10
    y <- 20
    x + y
  })
  expect_equal(result, 30)
})

# Test 11: catch with error in nested function call
test_that('catch catches error in nested function', {
  expect_error(
    catch(sqrt(as.numeric(sqrt("NA")))),
    "Error in",
    fixed = TRUE
  )
})

# Test 12: catch with NULL expr_name throws error
test_that('catch rejects NULL expr_name', {
  expect_error(
    catch(1 + 1, expr_name = NULL),
    "must be a character scalar",
    fixed = TRUE
  )
})

# Test 13: catch with empty string expr_name
test_that('catch accepts empty string expr_name', {
  result <- catch(1 + 1, expr_name = "")
  expect_equal(result, 2)
})

data <- data.frame(text = "Julia is fast & beautiful", language = "Julia")

# Test 1: catch_eval evaluates expressions successfully
test_that('catch_eval evaluates expressions successfully', {
  expect_no_error(target_vec <- catch_eval(rlang::quo(language), data))
  expect_equal(target_vec, "Julia")
})

# Test 2: catch_eval throws an error on evaluation failure
test_that('catch_eval throws an error on evaluation failure', {
  expect_error(catch_eval(rlang::quo(type), data), "column name", fixed = TRUE)
})

# Test 3: catch_eval rejects wrong arguments
test_that('catch_eval rejects wrong arguments', {
  expect_error(catch_eval("language", data), "must be a quosure", fixed = TRUE)
})

data <- data.frame(text = "Julia is fast & beautiful", language = "Julia")

# Test 1: safe_eval evaluates expressions successfully
test_that('safe_eval evaluates expressions successfully', {
  expect_no_error(text_vec <- safe_eval(rlang::quo(text), data))
  expect_equal(text_vec, "Julia is fast & beautiful")
})

# Test 2: safe_eval returns NULL on evaluation failure
test_that('safe_eval returns NULL on evaluation failure', {
  expect_no_error(type_vec <- safe_eval(rlang::quo(type), data))
  expect_null(type_vec)
})
