# WARNING - Generated by {fusen} from dev/flat_stancer.Rmd: do not edit by hand # nolint: line_length_linter.

# Helper to stub all internal stages of llm_stance.character
stub_llm_methods <- function() {
  # Создаем фиктивный результат, который возвращает stance_cola
  mock_output <- list(
    judgement_results = data.frame(
      stance = "Neutral",
      explanation = "Mocked result"
    ),
    analysis_results = list("Expert analysis"),
    debate_results = list("Debate content")
  )
  
  testthat::local_mocked_bindings(
    validate_character = function(...) TRUE,
    stance_cola = function(...) mock_output
    # stance_pamr = function(...) mock_output,
    # stance_default = function(...) mock_output
  )
}

test_that('llm_stance.character is a function', {
  expect_true(inherits(llm_stance.character, 'function'))
})

test_that("llm_stance.character handles chat list and cloning", {
  stub_llm_methods()
  mockery::stub(llm_stance.character, "rlang::is_installed", TRUE)
  mockery::stub(llm_stance.character, "cld2::detect_language", "en")
  
  # Use an empty Chat object
  chat <- ellmer::chat_mistral(echo = "none")
  
  # Test with single chat
  res <- llm_stance(
    "Text mining is fun", "Text mining", type = "object",
    chat_base = chat, verbose = TRUE, language = "en"
  )
  
  expect_named(
    res, c("summary", "analysis", "debates", "judgements", "metadata")
  )
  expect_equal(res$metadata$n_total, 1)
  expect_equal(res$metadata$scale, "categorical")
  expect_s3_class(res, "stance_result")
  
  # Test with list of 1 chat
  chat_list <- list(chat)
  res_list <- llm_stance(
    "Text mining is fun", "Text mining", type = "object",
    chat_base = chat_list, verbose = FALSE, language = "en"
  )
  expect_named(
    res_list, c("summary", "analysis", "debates", "judgements", "metadata")
  )
  expect_equal(res_list$metadata$n_total, 1)
  expect_s3_class(res_list, "stance_result")
  
  # Test with list of 2 chats (Stage 1&2 use chat 1, Stage 3 uses chat 2)
  chat_list <- list(chat, chat)
  res_list <- llm_stance(
    "Text mining is fun", "Text mining", type = "object",
    chat_base = chat_list, verbose = FALSE, language = "en"
  )
  expect_named(
    res_list, c("summary", "analysis", "debates", "judgements", "metadata")
  )
  expect_equal(res_list$metadata$n_total, 1)
  expect_s3_class(res_list, "stance_result")
  
  # Test with list of 3 chats (Stage 1&2 use chat 1, Stage 3 uses chat 2)
  chat_list <- list(chat, chat, chat)
  res_list <- llm_stance(
    "Text mining is fun", "Text mining", type = "object",
    chat_base = chat_list, scale = "Likert", verbose = FALSE
  )
  expect_named(
    res_list, c("summary", "analysis", "debates", "judgements", "metadata")
  )
  expect_equal(res_list$metadata$n_total, 1)
  expect_equal(res_list$metadata$scale, "Likert")
  expect_s3_class(res_list, "stance_result")
  
  # Test with list with one invalid element
  chat_list <- list(chat, "chat", chat)
  expect_error(
    llm_stance(
      "Text mining is fun", "Text mining", type = "object",
      chat_base = chat_list, verbose = FALSE, language = "en"
    ),
    "Element 2 of",
    fixed = TRUE
  )
})

test_that("llm_stance.character aborts on invalid language", {
  mockery::stub(llm_stance.character, "stancer_available_languages", c("en", "ru"))
  
  expect_error(
    llm_stance("text", "target", chat_base = list(), language = "fr"),
    regexp = "not available",
    fixed = FALSE
  )
})

test_that("llm_stance.character: language auto-detection and validation", {
  stub_llm_methods()
  mockery::stub(llm_stance.character, "validate_character", TRUE)
  mockery::stub(llm_stance.character, "rlang::is_installed", TRUE)
  mockery::stub(llm_stance.character, "cld2::detect_language", "en")
  
  # 1. Test auto-detection warning
  expect_warning(
    llm_stance(
      "Some English text",
      "Target",
      type = "object",
      chat_base = ellmer::chat_anthropic(echo = "none"),
      language = NULL,
      verbose = FALSE
    ),
    "automatically detected", fixed = TRUE
  )
  
  # 2. Test error for non-character language input (e.g. numeric)
  expect_error(
    llm_stance("T", "T", chat_base = MockChat$new(), language = 123),
    "must be a character scalar", fixed = TRUE
  )
})

test_that("llm_stance.character: chat_base list length validation", {
  stub_llm_methods()
  mockery::stub(llm_stance.character, "validate_character", TRUE)
  mockery::stub(llm_stance.character, "rlang::is_installed", TRUE)
  mockery::stub(llm_stance.character, "cld2::detect_language", "en")
  chat <- ellmer::chat_mistral(echo = "none")
  
  # Error for 4 chats
  expect_error(
    llm_stance(
      x = "T",
      target = "T",
      language = "en",
      chat_base = list(chat, chat, chat, chat),
      verbose = FALSE
    ),
    "must have 1, 2, or 3 elements",
    fixed = TRUE
  )
  
  # Error for invalid object type
  expect_error(
    llm_stance(
      x = "T",
      target = "T",
      chat_base = "not a chat",
      language = "en",
      verbose = FALSE
    ),
    "object or a list of 1-3",
    fixed = TRUE
  )
})

test_that("llm_stance.character: domain_role length validation", {
  stub_llm_methods()
  mockery::stub(llm_stance.character, "validate_character", TRUE)
  mockery::stub(llm_stance.character, "validate_fields", TRUE)
  mockery::stub(llm_stance.character, "rlang::is_installed", TRUE)
  mockery::stub(llm_stance.character, "cld2::detect_language", "en")
  
  # n = 2, but domain_role = 3
  expect_error(
    llm_stance(
      x = c("T1", "T2"),
      target = "Target",
      chat_base = ellmer::chat_mistral(echo = "none"),
      language = "en",
      domain_role = c("R1", "R2", "R3"),
      verbose = FALSE
    ),
    "must have length 1 or 2",
    fixed = TRUE
  )
  
  # Warning: multiple domain roles
  expect_warning(
    llm_stance(
      x = c("T1", "T2", "T3"),
      target = "Text Mining",
      chat_base = ellmer::chat_mistral(echo = "none"),
      language = "en",
      domain_role = c("D1", "D2", "D3"),
      verbose = TRUE
    ),
    "Multiple domain roles detected",
    fixed = TRUE
  )
})

test_that("llm_stance.character: likert scale post-processing", {
  # Специальный мок для проверки фактора Likert
  mock_likert <- list(
    judgement_results = data.frame(
      stance = "Strongly Agree",
      explanation = "Likert result"
    )
  )
  
  testthat::local_mocked_bindings(
    validate_character = function(...) TRUE,
    stance_cola = function(...) mock_likert
  )
  
  res <- llm_stance(
    x = "T", target = "T",
    chat_base = ellmer::chat_mistral(),
    scale = "Likert", method = "cola", language = "en"
  )
  
  expect_s3_class(res$summary$stance, "factor")
  expect_true(is.ordered(res$summary$stance))
  expect_equal(as.character(res$summary$stance), "Strongly Agree")
})

test_that("llm_stance.character rejects invalid argument values", {
  mockery::stub(llm_stance.character, "validate_character", TRUE)
  
  # Invalid `type`
  expect_error(
    llm_stance(
      "Text mining is interesting",
      target = "Text Mining",
      type = 111L
    ),
    "must be a character vector, got",
    fixed = TRUE
  )
  
  # Invalid `domain_role`
  expect_error(
    llm_stance(
      "Content analysis is interesting",
      target = "Content Analysis is interesting",
      type = "claim",
      language = "en",
      domain_role = 111L
    ),
    "must be a character vector, got",
    fixed = TRUE
  )
})

test_that("llm_stance.character: categorical scale levels", {
  mock_cat <- list(
    judgement_results = data.frame(
      stance = "Positive",
      explanation = "Cat result"
    )
  )
  testthat::local_mocked_bindings(
    validate_character = function(...) TRUE,
    stance_cola = function(...) mock_cat
  )
  
  res <- llm_stance(
    "T", "T", chat_base = ellmer::chat_mistral(),
    scale = "categorical", language = "en"
  )
  
  expect_s3_class(res$summary$stance, "factor")
  expect_equal(levels(res$summary$stance), c("Negative", "Neutral", "Positive"))
})

test_that("llm_stance.character throws error on wrong result length", {
  # Custom stub for stage 3 to return a specific Likert value
  mockery::stub(llm_stance.character, "validate_character", TRUE)
  mock_likert <- list(
    judgement_results = data.frame(
      stance = "Strongly Agree",
      explanation = "Likert result"
    )
  )
  
  llm_stance(
    x = c("T1", "T2"),
    target = "T",
    type = "claim",
    chat_base = ellmer::chat_mistral(echo = "none"),
    language = "uk",
    scale = "likert",
    verbose = TRUE
  ) |>
    expect_error(
      "Final stance judgement returned unexpected results",
      fixed = TRUE
    )
})
