# WARNING - Generated by {fusen} from dev/flat_stancer.Rmd: do not edit by hand # nolint: line_length_linter.

#' Abort with formatted error message
#'
#' @param ... Arguments passed to cli::cli_abort()
#'
#' @return Throws error
#' @keywords internal
#' @importFrom cli cli_abort
#' @noRd

abort <- function(msg) {
  cli::cli_abort(
    msg,
    call = rlang::expr(llm_stance()),
    .envir = rlang::caller_env()
  )
}
