# WARNING - Generated by {fusen} from dev/flat_stancer.Rmd: do not edit by hand # nolint: line_length_linter.

#' Execute expert role analysis
#'
#' @description
#' An internal worker that handles the execution of LLM requests for a
#' specific expert role. It switches between parallel execution
#' (when a single system prompt is shared) and sequential execution (when
#' each task requires a unique system prompt).
#'
#' @param expert_role Character. The role to execute (e.g., "linguist").
#' @param inputs A list containing texts, targets, and prompt templates.
#' @param chat_base An `ellmer::Chat` object used as a template.
#' @param info Character. A descriptive label for logging and error messages.
#' @param rpm Integer. Requests per minute limit for parallel execution.
#' @param verbose Logical. Whether to print progress messages to the console.
#'
#' @return A character vector of LLM responses, one for each input text.
#'
#' @keywords internal
#' @importFrom ellmer parallel_chat_text
#'
#' @noRd

execute_role <- function(
    expert_role,
    inputs,
    chat_base,
    info,
    rpm = 500,
    verbose = TRUE
) {
  tasks <- prepare_expert_chats(
    inputs,
    chat_base = chat_base,
    expert_role = expert_role
  )

  if (verbose) cat('    \U1F4CA', glue::glue('{info}...'), '\n')

  # If multiple system_prompts, e.g
  if (length(tasks$chats) > 1) {
    # Use sequential analysis
    results <- vapply(
      seq_along(tasks$tasks),
      function(task_i) {
        chat <- tasks$chats[[task_i]]
        result <- chat$chat(tasks$tasks[[task_i]], echo = 'none')
        if (!is.character(result)) {
          abort("Unexpected results in {info} {task_i}")
        }
        result
      },
      character(1)
    ) |> catch(tolower(info))
  } else {
    # Use parallel analysis
    results <- ellmer::parallel_chat_text(
      # Unpack the Chat object
      chat = tasks$chats[[1]],
      prompts = tasks$tasks,
      rpm = rpm
    ) |> catch(tolower(info))
  }

  if (!is.character(results) || (length(results) != length(inputs$texts))) {
    abort(
      c(
        "Unexpected results in {info}",
        "x" = "Input and output lengths differ: {length(inputs$texts)} vs {length(results)}"
      )
    )
  }

  results
}

#' Prepare chat configurations for debate agents
#'
#' @description
#' Prepares the prompts and chat objects for Stage 2 (Debate). It takes the
#' linguistic, domain, and social media analysis results from Stage 1 and
#' injects them into the 'debater' templates.
#'
#' @param stance Character. The stance label to be debated for (used in prompts).
#' @param inputs A list containing:
#'   - `texts`, `targets`, `target_types`, `language`, `prompt_templates`
#'   - `analysis_results`: A list with `linguistic`, `domain`, and `social_media`
#'     vectors from Stage 1.
#' @param chat_base An `ellmer::Chat` object.
#'
#' @return A list with two elements:
#'   - `chats`: A list containing a single `ellmer::Chat` object.
#'   - `tasks`: A character vector of user prompts for each input text.
#'
#' @keywords internal
#'
#' @noRd

prepare_debater_chats <- function(
    stance,
    inputs,
    chat_base
) {
  # Prepare prompts using all context from Stage 1
  prompts <- with(
    inputs,
    prompts_prepare(
      'debater',
      language = language,
      templates = prompt_templates,
      text = texts,
      target_type = target_types,
      target = targets,
      stance = stance,
      LingResponse = analysis_results$linguistic,
      ExpertResponse = analysis_results$domain,
      UserResponse = analysis_results$social_media
    )
  )

  # Stage 2 requires a consistent system prompt across all items
  if (length(prompts$system) > 1) {
    abort(
      c(
        "Multiple system prompts are not allowed at stage 2",
        "i" = "Consider checking variable placeholders in system templates"
      )
    )
  }

  tasks_prepare(chat_base, prompts, length(inputs$texts))
}

#' Prepare chat configurations for expert agents
#'
#' @description
#' A high-level internal helper that orchestrates the preparation of expert
#' sessions for specific analysis roles (linguist, domain expert, or interpreter).
#'
#' @details
#' This function acts as a bridge between the input data and the execution
#' engine. It extracts necessary variables from the `inputs` list,
#' interpolates the corresponding templates using [prompts_prepare()],
#' and then initialises the chat objects via [tasks_prepare()].
#'
#' @param inputs A list containing all necessary data for prompt interpolation:
#'   - `texts`: Character vector of statements to analyse.
#'   - `targets`: Character vector of analysis targets.
#'   - `target_types`: Character vector of localised target types.
#'   - `prompt_templates`: List of paths to markdown template files.
#'   - `language`: Character string (e.g., "en").
#'   - `domain_roles`: (Optional) Character vector for the domain expert role.
#' @param chat_base An `ellmer::Chat` object used as a template for cloning.
#' @param expert_role Character. One of `"linguist"`, `"domain"`, or `"interpreter"`.
#'
#' @return A list containing:
#' - `chats`: A list of configured `ellmer::Chat` objects.
#' - `tasks`: A character vector of interpolated user prompts.
#'
#' @keywords internal
#' @importFrom rlang arg_match
#'
#' @noRd

prepare_expert_chats <- function(
    inputs,
    chat_base,
    expert_role = c('linguist', 'domain', 'interpreter')
) {
  expert_role <- rlang::arg_match(
    expert_role,
    c('linguist', 'domain', 'interpreter'),
    multiple = FALSE
  )

  # Load instructions for the expert
  prompts <- with(
    inputs,
    prompts_prepare(
      expert_role,
      templates = prompt_templates,
      language = language,
      text = texts,
      target = targets,
      target_type = target_types,
      domain = domain_roles
    )
  )

  tasks_prepare(chat_base, prompts, length(inputs$texts))
}

#' Prepare chat configurations for judge agent
#'
#' @param inputs Input texts
#' @param chat_base Base chat configuration
#'
#' @return List of chat configurations
#' @keywords internal
#'
#' @noRd

prepare_judger_chats <- function(
    inputs,
    chat_base
) {
  prompts <- with(
    inputs,
    prompts_prepare(
      'judger',
      language = language,
      templates = prompt_templates,
      text = texts,
      target_type = target_types,
      target = targets,
      FavourResponse = debate_results$positive,
      AgainstResponse = debate_results$negative,
      NeutralResponse = debate_results$neutral,
      # Additional instructions based on object types
      add_reference_resolution = 'object' %in% types,
      add_statement_resolution = 'statement' %in% types
    )
  )

  if (length(prompts$system) > 1) {
    abort(
      c(
        "Multiple system prompts are not allowed at stage 3",
        "i" = "Consider checking variable placeholders in system templates"
      )
    )
  }

  tasks_prepare(chat_base, prompts, length(inputs$texts))
}
