# WARNING - Generated by {fusen} from dev/flat_stancer.Rmd: do not edit by hand # nolint: line_length_linter.

#' Safely evaluate expression and catch errors
#'
#' @param expr Expression to evaluate
#' @param expr_name Name of expression for error messages
#'
#' @return Result of expression or throws an error
#' @keywords internal
#' @importFrom rlang is_scalar_character try_fetch
#' @importFrom cli cli_abort
#' @noRd

catch <- function(
    expr,
    expr_name = paste(deparse(substitute(expr)), collapse = '')
) {
  if (!rlang::is_scalar_character(expr_name)) {
    cli::cli_abort(
      "{.arg expr_name} must be a character scalar.
            Got {.cls {class(expr_name)}}"
    )
  }

  rlang::try_fetch(
    expr,
    error = function(e) {
      abort("Error in {expr_name}: {e$message}")
    }
  )
}

#' Safely evaluate quosures (throws an error)
#'
#' @param quo A quosure to evaluate
#' @param data A data frame, or named list or vector.
#'
#' @return Result of evaluation or throws an error
#' @keywords internal
#' @importFrom rlang is_quosure try_fetch as_name
#' @importFrom cli cli_abort
#' @noRd

catch_eval <- function(
    quo,
    data
) {
  if (!rlang::is_quosure(quo)) {
    cli::cli_abort(
      "{.arg quo} must be a quosure.
            Got {.cls {class(quo)}}"
    )
  }

  rlang::try_fetch(
    rlang::eval_tidy(quo, data),
    error = function(e) {
      abort(
        c(
          "Cannot find {.val {rlang::as_name(quo)}} in data or environment",
          "i" = "Use a column name or provide a vector"
        )
      )
    }
  )
}

#' Safely evaluate quosures (returns NULL)
#'
#' @param quo A quosure to evaluate
#' @param data A data frame, or named list or vector.
#'
#' @return Result of evaluation or `NULL`
#' @keywords internal
#' @importFrom rlang try_fetch
#' @noRd

safe_eval <- function(
    quo,
    data
) {
  rlang::try_fetch(
    catch_eval(quo, data),
    error = function(e) NULL
  )
}
