# WARNING - Generated by {fusen} from dev/flat_stancer.Rmd: do not edit by hand # nolint: line_length_linter.

#' Execute expert role analysis
#'
#' @description
#' An internal worker that handles the execution of LLM requests for a
#' specific expert role. It switches between parallel execution
#' (when a single system prompt is shared) and sequential execution (when
#' each task requires a unique system prompt).
#'
#' @param expert_role Character. The role to execute (e.g., "linguist").
#' @param inputs A list containing texts, targets, and prompt templates.
#' @param chat_base An `ellmer::Chat` object used as a template.
#' @param info Character. A descriptive label for logging and error messages.
#' @param rpm Integer. Requests per minute limit for parallel execution.
#' @param verbose Logical. Whether to print progress messages to the console.
#'
#' @return A character vector of LLM responses, one for each input text.
#'
#' @keywords internal
#' @importFrom ellmer parallel_chat_text
#' @noRd

execute_role <- function(
    expert_role,
    inputs,
    chat_base,
    info,
    rpm = 500,
    verbose = TRUE
) {
  tasks <- prepare_expert_chats(
    inputs,
    chat_base = chat_base,
    expert_role = expert_role
  )

  if (verbose) cat('    \U1F4CA', glue::glue('{info}...'), '\n')

  # If multiple system_prompts, e.g
  if (length(tasks$chats) > 1) {
    # Use sequential analysis
    results <- vapply(
      seq_along(tasks$tasks),
      function(task_i) {
        chat <- tasks$chats[[task_i]]
        result <- chat$chat(tasks$tasks[[task_i]], echo = 'none')
        if (!is.character(result)) {
          abort("Unexpected results in {info} {task_i}")
        }
        result
      },
      character(1)
    ) |> catch(tolower(info))
  } else {
    # Use parallel analysis
    results <- ellmer::parallel_chat_text(
      # Unpack the Chat object
      chat = tasks$chats[[1]],
      prompts = tasks$tasks,
      rpm = rpm
    ) |> catch(tolower(info))
  }

  if (!is.character(results) || (length(results) != length(inputs$texts))) {
    abort(
      c(
        "Unexpected results in {info}",
        "x" = "Input and output lengths differ: {length(inputs$texts)} vs {length(results)}"
      )
    )
  }

  results
}
