# WARNING - Generated by {fusen} from dev/flat_stancer.Rmd: do not edit by hand # nolint: line_length_linter.

#' @rdname stance_cola
#'
#' @noRd
stance_cola <- function(
    text,
    target,
    type,
    target_type,
    chats,
    language,
    scale,
    domain_role,
    prompts_dir,
    verbose,
    rpm = 20,
    ...
) {
  ## Prompts ----
  prompt_templates <- templates_collect(prompts_dir, language, scale)
  
  n <- length(text)
  inputs <- list(
    texts = text,
    targets = target,
    types = type,
    target_types = target_type,
    language = language,
    scale = scale,
    domain_roles = domain_role,
    prompt_templates = prompt_templates
  )
  
  if (verbose) {
    cat("\n")
    cat(strrep("=", 70), "\n")
    cat(glue::glue("\U1F50D STANCE ANALYSIS (COLA) - Processing {n} item(s)"), "\n")
    cat(strrep("=", 70), "\n\n")
    cat("Method: COLA", "\n")
    cat(glue::glue("Types: {paste(unique(type), collapse = ', ')}"), "\n")
    cat(glue::glue("Language: {language}"), "\n")
    cat(
      glue::glue("Domain roles: {paste(unique(domain_role), collapse = ', ')}"),
      "\n"
    )
    cat("\n")
  }
  
  output <- inputs |>
    stage_1_parallel_analysis(chats[[1]], verbose, rpm) |>
    validate_stage('Stage 1 (Expert analysis)') |>
    stage_2_parallel_debates(chats[[2]], verbose, rpm) |>
    validate_stage('Stage 2 (Stance debates)') |>
    stage_3_parallel_judgement(chats[[3]], verbose, rpm, ...)
  
  if (is.null(output$judgement_results) || nrow(output$judgement_results) != n) {
    cli::cli_abort("Final stance judgement returned unexpected results")
  }
  
  output
}
