# WARNING - Generated by {fusen} from dev/flat_stancer.Rmd: do not edit by hand # nolint: line_length_linter.

#' Inspect stance_result contents
#'
#' @param x A `stance_result` object.
#' @param ... Additional arguments passed to methods
#'
#' @return Invisibly x
#' @export

inspect <- function(x, ...) {
  UseMethod("inspect")
}

#' Inspect stance_result contents
#'
#' @description
#' A diagnostic tool to peer into the internal steps of the stance analysis.
#' It allows you to view metadata, raw linguistic/expert analysis,
#' internal debates between models, or the final explanation for a specific row.
#'
#' @param x A `stance_result` object.
#' @param what Character. Primary level: 'metadata', 'analysis', 'debates', or 'explanation'.
#' @param within Optional character. Secondary level (e.g., 'linguistic' for analysis).
#' @param index Integer. The row index of the text item to inspect.
#'
#' @return The input object (invisibly).
#' @export
#' @examples
#' # result <- llm_stance(...)
#' # inspect(result, what = 'metadata')
#' # inspect(result, what = 'analysis', within = 'linguistic')
#' # inspect(result, what = 'debates', within = 'negative', index = 1)

inspect.stance_result <- function(
    x,
    what = c('metadata', 'analysis', 'debates', 'explanation'),
    within = NULL,
    index = 1
) {

  what <- match.arg(what)
  ellmer:::check_number_whole(index, min = 1)

  switch(
    what,

    #### Inspect Metadata ----
    metadata = {
      cat("\n", cli::rule("METADATA"), "\n\n")
      yaml::write_yaml(x$metadata, file = stdout())
    },

    #### Inspect Analysis Results ----
    analysis = {
      if (is.null(within)) {
        cat("\n", cli::rule("ANALYSIS - Available sections"), "\n\n")
        available <- names(x$analysis)
        cat("Available sections:\n")
        for (section in available) {
          cat(
            cli::col_cyan(
              sprintf("  • %s\n", section)
            )
          )
        }
        cat(
          "\nUsage: ",
          "inspect(result, what = 'analysis', ",
          "within = 'section_name')\n\n",
          sep = ""
        )
      } else {
        if (!within %in% names(x$analysis)) {
          cli::cli_abort(
            "Section '{within}' not found in analysis. ",
            "Available: {.val {names(x$analysis)}}"
          )
        }

        if (index > length(x$analysis)) {
          cli::cli_abort(
            "Index {index} out of bounds. ",
            "Analysis has {length(x$analysis)} rows."
          )
        }

        content <- x$analysis[[within]][index]

        cat(
          "\n",
          cli::rule(
            sprintf(
              "ANALYSIS: %s [row %d]",
              within,
              index
            )
          ),
          "\n\n"
        )

        if (is.na(content) || is.null(content)) {
          cat(cli::col_yellow("(empty)\n\n"))
        } else {
          cat(ellmer::interpolate(content))
          cat("\n")
        }
      }
    },

    #### Inspect Stance Debates ----
    debates = {
      if (is.null(within)) {
        cat("\n", cli::rule("DEBATES - Available sections"), "\n\n")
        available <- names(x$debates)
        cat("Available sections:\n")
        for (section in available) {
          cat(
            cli::col_cyan(
              sprintf("  • %s\n", section)
            )
          )
        }
        cat(
          "\nUsage: ",
          "inspect(result, what = 'debates', ",
          "within = 'section_name')\n\n",
          sep = ""
        )
      } else {
        if (!within %in% names(x$debates)) {
          cli::cli_abort(
            "Section '{within}' not found in debates. ",
            "Available: {.val {names(x$debates)}}"
          )
        }

        if (index > length(x$debates)) {
          cli::cli_abort(
            "Index {index} out of bounds. ",
            "Debates has {length(x$debates)} rows."
          )
        }

        content <- x$debates[[within]][index]

        cat(
          "\n",
          cli::rule(
            sprintf(
              "DEBATES: %s [row %d]",
              within,
              index
            )
          ),
          "\n\n"
        )

        if (is.na(content) || is.null(content)) {
          cat(cli::col_yellow("(empty)\n\n"))
        } else {
          cat(ellmer::interpolate(content))
          cat("\n")
        }
      }
    },

    #### Inspect Explanation ----
    explanation = {
      if (!is.null(within)) {
        cli::cli_warn(
          c(
            'Stance result explanation has no sections.',
            'Unused argument: {.arg within}'
          )
        )
      }

      if (index > length(x$summary$explanation)) {
        cli::cli_abort(
          c(
            "Index {index} out of bounds. ",
            "The data have {nrow(x$summary)} rows."
          )
        )
      }

      content <- x[['summary']][['explanation']][index]

      cat(
        "\n",
        cli::rule(
          sprintf("EXPLANATION: [row %d]", index)
        ),
        "\n\n"
      )

      if (is.na(content) || is.null(content)) {
        cat(cli::col_yellow("(empty)\n\n"))
      } else {
        cat(ellmer::interpolate(content))
        cat("\n")
      }
    }
  )

  invisible(x)
}
