# WARNING - Generated by {fusen} from dev/flat_stancer.Rmd: do not edit by hand # nolint: line_length_linter.

#' Get localised string
#'
#' @param language Target language code
#' @param caption_id Translation key
#' @param case Optional second level key (e.g., 'gen', 'dat', 'likert')
#'
#' @return Character string with translation
#' @keywords internal
#' @noRd

l <- function(language, caption_id, case = NULL) {
  # Check lanuage
  if (!language %in% stancer_available_languages()) {
    abort(
      "Language '{language}' not available. \\
            Use: {.val {stancer_available_languages()}}"
    )
  }

  dict <- load_translations()

  # Проверка ключа
  if (!caption_id %in% names(dict[[language]])) {
    cli::cli_abort(
      "Caption ID '{caption_id}' not found ",
      "in language '{language}'"
    )
  }

  translation <- dict[[language]][[caption_id]]

  if (!is.null(case)) {
    case <- rlang::arg_match(
      case,
      c('gen', 'dat', 'categorical', 'numeric', 'likert'),
      multiple = FALSE
    )

    if (!is.list(translation)) {
      cli::cli_abort(
        "Case '{case}' not supported for '{caption_id}' ",
        "(expected list with cases)"
      )
    }

    if (!case %in% names(translation)) {
      cli::cli_abort(
        "Case '{case}' not found for '{caption_id}'"
      )
    }

    translation[[case]]
  } else {
    if (is.list(translation)) {
      cli::cli_abort(
        "Case required for '{caption_id}'. ",
        "Available: {.val {names(translation)}}"
      )
    }

    translation
  }
}
