# WARNING - Generated by {fusen} from dev/flat_stancer.Rmd: do not edit by hand # nolint: line_length_linter.

#' Detect stance using COLA framework
#'
#' @description
#' `llm_stance()` implements a multi-stage "Collaborative rOle-infused LLM-based
#' Agents" (COLA) framework to detect stance in text towards a specific target
#' or statement.
#' It supports character vectors and data frames (compatible with `mall` style).
#'
#' @param x Input text(s) as a character vector or a data.frame containing (any of) `text`, `target`, `type`, `domain_role` or `language` arguments.
#' @param ... Additional arguments passed to `ellmer::parallel_chat_structured`.
#'
#' @return A `stance_result` object (for character method) or a modified
#'   data frame (for data.frame method).
#'
#' @export
llm_stance <- function(x, ...) {
  UseMethod("llm_stance")
}

#' @rdname llm_stance
#' @description
#' The `character` method performs the full three-stage analysis:
#' 1. **Expert Analysis**: Linguistic, domain, and social media perspectives.
#' 2. **Stance Debates**: Parallel generation of arguments for, against, and neutral.
#' 3. **Judgement**: Final synthesis into a structured stance score.
#'
#' @details
#' ## Chat Configuration Recommendations
#' For optimal results, consider the following requirements for each stage:
#' \itemize{
#'   \item \strong{Expert Analysis (Stage 1)}: Requires excellent real-world
#'   awareness and reasoning. Structured output is NOT required.
#'   \item \strong{Stance Debates (Stage 2)}: Requires creativity and strong
#'   writing skills. Structured output is NOT required.
#'   \item \strong{Stance Judgement (Stage 3)}: Requires large context width,
#'   superior reasoning, and \strong{MUST} support structured output (JSON mode).
#' }
#' 
#' @param target Character. The entity or statement the stance is directed at.
#' @param chat_base An `ellmer::Chat` object or a list of up to 3 such objects.
#' @param type Analysis type: "object" (entity-based) or "statement" (proposition-based).
#' @param language Language code (e.g., "en", "ru"). If `NULL`, auto-detected.
#' @param scale Stance scale: "categorical", "numeric", or "likert".
#' @param domain_role Optional specific role for the domain expert (e.g., "historian").
#' @param prompts_dir Optional path to custom prompt templates.
#' @param verbose Logical. Show progress and summary table.
#' @param rpm Integer. Global requests per minute limit.
#'
#' @return S3 object of class "stance_result" with:
#'   - summary: data.frame with results
#'   - analysis: expert analysis results
#'   - debates: debate results
#'   - judgements: final judgements
#'   - metadata: processing metadata
#' ⁠@importFrom ellmer is_chat
#' @importFrom cli cli_abort cli_warn
#' @importFrom rlang is_character is_scalar_character is_list arg_match is_installed
#' @importFrom glue glue
#' @importFrom tibble as_tibble
#' @importFrom tictoc tic toc
#' @export
#' @examples
#' # result <- llm_stance(
#' #   x = "I support renewable energy",
#' #   target = "renewable energy",
#' #   chat_base = chat_model,
#' #   type = "object",
#' #   scale = "categorical"
#' # )
llm_stance.character <- function(
    x,
    target,
    chat_base,
    type = c('object'),
    language = stancer_available_languages(),
    scale = c('categorical', 'numeric', 'likert'),
    domain_role = NULL,
    prompts_dir = NULL,
    verbose = TRUE,
    rpm = 20,
    ...
) {
  ## Validation ----
  tictoc::tic('Analysis')

  # Validate text and target
  text <- x
  validate_character(text)
  validate_character(target)

  n <- length(text)

  # Validate type
  if (rlang::is_character(type)) {
    if (length(type == 2) != n) {
      type <- rlang::arg_match(type, c('object', 'statement'), multiple = FALSE)
    } else {
      type <- rlang::arg_match(type, c('object', 'statement'), multiple = TRUE)
    }
  } else {
    cli::cli_abort(
      "{.arg type} must be a character vector, got {.cls {class(type)}}"
    )
  }

  # Validate language
  if (is.null(language) || length(language) > 1) {
    if (rlang::is_installed("cld2")) {
      language <- cld2::detect_language(text[[1]], lang_code = TRUE)
      cli::cli_warn(
        "The analysis language was automatically detected: {.val {language}}"
      )
    }
  }
  if (rlang::is_scalar_character(language)) {
    if (!language %in% stancer_available_languages()) {
      cli::cli_abort(
        c(
          "Language {.val {language}} not available",
          "i" = "Use one of: {.val {stancer_available_languages()}}"
        )
      )
    }
  } else {
    cli::cli_abort(
      "{.arg language} must be a character scalar, got \
            {.cls {class(language)}} of length {.val {length(language)}}"
    )
  }

  # Validate scale
  scale <- rlang::arg_match(scale, c('categorical', 'numeric', 'likert'))

  # Validate domain_role
  if (is.null(domain_role)) {
    domain_role <- switch(
      language,
      uk = 'sociologist', # 'соціолог',
      ru = 'sociologist', # 'социолог',
      'social commentator'
    )
  } else {
    if (!rlang::is_character(domain_role) || length(domain_role) < 1) {
      cli::cli_abort(
        "{.arg domain_role} must be a character vector, got {.cls {class(domain_role)}}"
      )
    }
    if (!(length(domain_role) == 1 || length(domain_role) == n)) {
      cli::cli_abort(
        c(
          "{.arg domain_role} must have length 1 or {n} (same as {.arg text})",
          "x" = "Got {length(domain_role)}"
        )
      )
    }
  }

  if (length(domain_role) > 1) {
    cli::cli_warn(
      "Multiple domain roles detected. Parallel execution is unsupported."
    )
  }

  ### Chat Validation ----
  # Validate and arrange the `chat_base` argument across stages
  #
  # Recommendations (see vignette and docstrings):
  # 1. Expert analysis (Stage 1):
  #     - Excellent real-world awareness
  #     - Decent reasoning skills
  #     - Sufficient writing skills
  #     - Context width depends on task
  #     - Structured output: NOT required
  # 2. Stance debates (Stage 2):
  #     - Sufficient context width
  #     - Creative and writing skills
  #     - Structured output: NOT required
  # 3. Stance decision (Stage 3):
  #     - Large context width
  #     - Excellent reasoning skills
  #     - Excellent real-world awareness
  #     - Structured output: REQUIRED
  chats <- if (rlang::is_list(chat_base)) {
    # Validate each element
    for (i in seq_along(chat_base)) {
      if (!ellmer:::is_chat(chat_base[[i]])) {
        cli::cli_abort(
          "Element {i} of {.arg chat_base} is not an {.cls ellmer::Chat} object"
        )
      }
    }

    # Arrange based on list length
    indices <- switch(
      length(chat_base),
      `1` = c(1, 1, 1),
      `2` = c(1, 1, 2),
      `3` = c(1, 2, 3),
      cli::cli_abort(
        c(
          "{.arg chat_base} must have 1, 2, or 3 elements",
          "x" = "You provided {length(chat_base)}"
        )
      )
    )
    lapply(indices, \(i) chat_base[[i]]$clone(deep = TRUE))

  } else if (ellmer:::is_chat(chat_base)) {
    rep(list(chat_base$clone(deep = TRUE)), times = 3)

  } else {
    cli::cli_abort(
      c(
        "{.arg chat_base} must be an {.cls ellmer::Chat} object or \
                a list of 1-3 {.cls ellmer::Chat} objects",
        "x" = "Got {.cls {class(chat_base)}}"
      )
    )
  }

  ## Prompts ----
  prompt_templates <- templates_collect(prompts_dir, language, scale)

  ## Preparation ----
  target <- recycle_arg(target, n)
  type <- recycle_arg(type, n)

  target_types <- sapply(type, type_to_term, language = language)

  inputs <- list(
    texts = text,
    targets = target,
    types = type,
    target_types = target_types,
    language = language,
    scale = scale,
    domain_roles = domain_role,
    prompt_templates = prompt_templates
  )

  if (verbose) {
    cat("\n")
    cat(strrep("=", 70), "\n")
    cat(glue::glue("\U1F50D STANCE ANALYSIS - Processing {n} item(s)"), "\n")
    cat(strrep("=", 70), "\n\n")
    cat(glue::glue("Types: {paste(unique(type), collapse = ', ')}"), "\n")
    cat(glue::glue("Language: {language}"), "\n")
    cat(
      glue::glue("Domain roles: {paste(unique(domain_role), collapse = ', ')}"),
      "\n"
    )
    cat("\n")
  }

  ## Analysis ----
  output <- inputs |>
    stage_1_parallel_analysis(chats[[1]], verbose, rpm) |>
    validate_stage('Stage 1 (Expert analysis)') |>
    stage_2_parallel_debates(chats[[2]], verbose, rpm) |>
    validate_stage('Stage 2 (Stance debates)') |>
    stage_3_parallel_judgement(chats[[3]], verbose, rpm, ...)

  if (is.null(output$judgement_results) || nrow(output$judgement_results) != n) {
    cli::cli_abort("Final stance judgement returned unexpected results")
  }

  # Additional postprocessing of quantitative and Likert stance labels
  if (scale == 'numeric') {
    # output$judgement_results$stance <- truncate(
    #     (output$judgement_results$stance - 50) / 50,
    #     -1,
    #     1
    # )
  } else if (scale == 'likert') {
    output$judgement_results$stance <- factor(
      output$judgement_results$stance,
      levels = c(
        'Strongly Disagree',
        'Disagree',
        'Neutral',
        'Agree',
        'Strongly Agree'
      ),
      ordered = TRUE
    )
  }

  ## Postprocessing ----
  summary_df <- data.frame(
    text = text,
    target = target,
    target_type = type,
    language = language
  ) |>
    cbind(output$judgement_results) |>
    tibble::as_tibble()

  if (verbose) {
    cat("\U1F4CA Summary Table:\n")
    print(summary_df)
    cat("\n")
    cat(strrep("=", 70), "\n")
    toc <- tictoc::toc(func.toc = stage_complete, quiet = FALSE)
    cat(strrep("=", 70), "\n\n")
  } else {
    toc <- tictoc::toc(func.toc = stage_complete, quiet = TRUE)
  }

  ## Return ----
  structure(
    list(
      summary = summary_df,
      analysis = output$analysis_results,
      debates = output$debate_results,
      judgements = output$judgement_results,
      metadata = list(
        n_total = n,
        n_processed = nrow(output$judgement_results),
        n_failed = sum(is.na(output$judgement_results$stance)),
        language = language,
        types = unique(type),
        domain_role = domain_role,
        model = unique(sapply(chats, \(chat) chat$get_model())),
        elapsed = toc$toc - toc$tic,
        timestamp = Sys.time()
      )
    ),
    class = c("stance_result", "list")
  )
}
