# WARNING - Generated by {fusen} from dev/flat_stancer.Rmd: do not edit by hand # nolint: line_length_linter.

#' Load translation dictionary
#'
#' @return List containing translations for all supported languages
#' @keywords internal
#' @noRd

load_translations <- function() {
  yaml_file <- system.file("i18n/translations.yaml", package = "stancer")
  if (!file.exists(yaml_file)) yaml_file <- here::here("inst/i18n/translations.yaml")
  rlang::try_fetch(
    yaml::read_yaml(yaml_file),
    error = function(e) cli::cli_abort("Tranlsations not found.")
  )
}
