# WARNING - Generated by {fusen} from dev/flat_stancer.Rmd: do not edit by hand # nolint: line_length_linter.

#' Get localised string
#'
#' @param language Target language code
#' @param caption_id Translation key
#' @param case Optional second level key (e.g., 'gen', 'dat', 'likert')
#'
#' @return Character string with translation
#' @keywords internal
#'
#' @noRd

l <- function(language, caption_id, case = NULL) {
  # Check lanuage
  if (!language %in% stancer_available_languages()) {
    abort(
      "Language '{language}' not available. \\
            Use: {.val {stancer_available_languages()}}"
    )
  }

  dict <- load_translations()

  # Проверка ключа
  if (!caption_id %in% names(dict[[language]])) {
    cli::cli_abort(
      "Caption ID '{caption_id}' not found ",
      "in language '{language}'"
    )
  }

  translation <- dict[[language]][[caption_id]]

  if (!is.null(case)) {
    case <- rlang::arg_match(
      case,
      c('gen', 'dat', 'categorical', 'numeric', 'likert'),
      multiple = FALSE
    )

    if (!is.list(translation)) {
      cli::cli_abort(
        "Case '{case}' not supported for '{caption_id}' ",
        "(expected list with cases)"
      )
    }

    if (!case %in% names(translation)) {
      cli::cli_abort(
        "Case '{case}' not found for '{caption_id}'"
      )
    }

    translation[[case]]
  } else {
    if (is.list(translation)) {
      cli::cli_abort(
        "Case required for '{caption_id}'. ",
        "Available: {.val {names(translation)}}"
      )
    }

    translation
  }
}

#' Load translation dictionary
#'
#' @return List containing translations for all supported languages
#' @keywords internal
#'
#' @noRd

load_translations <- function() {
  yaml_file <- system.file("i18n/translations.yaml", package = "stancer")
  rlang::try_fetch(
    yaml::read_yaml(yaml_file),
    error = function(e) cli::cli_abort("Tranlsations not found.")
  )
}

#' Get available languages for stancer
#'
#' @return Character vector of supported language codes
#'
#' @export
#' @examples
#' stancer_available_languages()

stancer_available_languages <- function() {
  names(load_translations())
}

#' Check translation dictionary structure
#'
#' @description
#' Validates and displays information about the translation dictionary,
#' including available languages, number of keys, and keys with case variants.
#' Useful for verifying translation completeness and structure.
#'
#' @details
#' This function performs the following checks:
#' - Lists all available languages in the dictionary
#' - Counts total translation keys per language
#' - Identifies keys with case variants (e.g., 'gen', 'dat', 'likert')
#'
#' The function prints a formatted report to the console and returns
#' invisibly TRUE.
#'
#' @return
#' Invisibly `TRUE`. Called for side effects (printing to console).
#'
#' @keywords internal
#'
#' @export
#' @examples
#' stancer_check_translations()

stancer_check_translations <- function() {
  dict <- load_translations()

  cat("Available languages:", paste(names(dict), collapse = ", "), "\n\n")

  for (language in names(dict)) {
    cat("Language:", language, "\n")
    cat("  Keys:", length(dict[[language]]), "\n")

    # Проверка структуры
    cases_keys <- sapply(dict[[language]], function(x) is.list(x))
    if (any(cases_keys)) {
      cat("  Keys with cases:", sum(cases_keys), "\n")
    }
    cat("\n")
  }

  invisible(TRUE)
}

#' Convert analysis type to human-readable term
#'
#' @param type Analysis type: "object" or "statement"
#' @param language Language code
#'
#' @return Character string with localised term
#' @keywords internal
#'
#' @noRd

type_to_term <- function(
    type = c('object', 'statement'),
    language = stancer_available_languages()
) {
  type <- rlang::arg_match(type, c('object', 'statement'), multiple = FALSE)
  language <- rlang::arg_match(language, stancer_available_languages(), multiple = FALSE)

  switch(
    type,
    object = l(language, 'object', 'dat'),
    statement = l(language, 'statement', 'dat')
  )
}
