# WARNING - Generated by {fusen} from dev/flat_stancer.Rmd: do not edit by hand # nolint: line_length_linter.

#' Convert stance_result to data frame
#'
#' @description
#' Extracts the summary table from a `stance_result` object and returns it as
#' a data frame. This allows for easy further analysis using standard R tools.
#' @param x A `stance_result` object
#' @param row.names Optional NULL or a character vector giving the row names for the data frame. Missing values are not allowed.
#' @param optional Logical. If TRUE, setting row names and converting column names to syntactic names is optional.
#' @param ... Additional arguments passed to [base::as.data.frame()].
#'
#' @return Data frame
#'
#' @export

as.data.frame.stance_result <- function(
    x,
    row.names = NULL,
    optional = FALSE,
    ...
) {
  x$summary
}

#' Inspect stance_result contents
#'
#' @param x A `stance_result` object.
#' @param ... Additional arguments passed to methods.
#'
#' @return The input object (invisibly).
#'
#' @export

inspect <- function(x, ...) {
  UseMethod("inspect")
}

#' @rdname inspect
#' Inspect stance_result contents
#'
#' @description
#' A diagnostic tool to peer into the internal steps of the stance analysis.
#' It allows you to view metadata, raw linguistic/expert analysis,
#' internal debates between models, or the final explanation for a specific row.
#'
#' @param what Character. Primary level: 'metadata', 'analysis', 'debates', or 'explanation'.
#' @param within Optional character. Secondary level (e.g., 'linguistic' for analysis).
#' @param index Integer. The row index of the text item to inspect.
#'
#' @return The input object (invisibly).
#'
#' @export
#' @examples
#' # result <- llm_stance(...)
#' # inspect(result, what = 'metadata')
#' # inspect(result, what = 'analysis', within = 'linguistic')
#' # inspect(result, what = 'debates', within = 'negative', index = 1)

inspect.stance_result <- function(
    x,
    what = c('metadata', 'analysis', 'debates', 'explanation'),
    within = NULL,
    index = 1,
    ...
) {

  what <- match.arg(what)
  ellmer:::check_number_whole(index, min = 1)

  switch(
    what,

    #### Inspect Metadata ----
    metadata = {
      cat("\n", cli::rule("METADATA"), "\n\n")
      yaml::write_yaml(x$metadata, file = stdout())
    },

    #### Inspect Analysis Results ----
    analysis = {
      if (is.null(within)) {
        cat("\n", cli::rule("ANALYSIS - Available sections"), "\n\n")
        available <- names(x$analysis)
        cat("Available sections:\n")
        for (section in available) {
          cat(
            cli::col_cyan(
              sprintf("  \U2022 %s\n", section)
            )
          )
        }
        cat(
          "\nUsage: ",
          "inspect(result, what = 'analysis', ",
          "within = 'section_name')\n\n",
          sep = ""
        )
      } else {
        if (!within %in% names(x$analysis)) {
          cli::cli_abort(
            "Section '{within}' not found in analysis. ",
            "Available: {.val {names(x$analysis)}}"
          )
        }

        if (index > length(x$analysis)) {
          cli::cli_abort(
            "Index {index} out of bounds. ",
            "Analysis has {length(x$analysis)} rows."
          )
        }

        content <- x$analysis[[within]][index]

        cat(
          "\n",
          cli::rule(
            sprintf(
              "ANALYSIS: %s [row %d]",
              within,
              index
            )
          ),
          "\n\n"
        )

        if (is.na(content) || is.null(content)) {
          cat(cli::col_yellow("(empty)\n\n"))
        } else {
          cat(ellmer::interpolate(content), fill = TRUE)
          cat("\n")
        }
      }
    },

    #### Inspect Stance Debates ----
    debates = {
      if (is.null(within)) {
        cat("\n", cli::rule("DEBATES - Available sections"), "\n\n")
        available <- names(x$debates)
        cat("Available sections:\n")
        for (section in available) {
          cat(
            cli::col_cyan(
              sprintf("  \U2022 %s\n", section)
            )
          )
        }
        cat(
          "\nUsage: ",
          "inspect(result, what = 'debates', ",
          "within = 'section_name')\n\n",
          sep = ""
        )
      } else {
        if (!within %in% names(x$debates)) {
          cli::cli_abort(
            "Section '{within}' not found in debates. ",
            "Available: {.val {names(x$debates)}}"
          )
        }

        if (index > length(x$debates)) {
          cli::cli_abort(
            "Index {index} out of bounds. ",
            "Debates has {length(x$debates)} rows."
          )
        }

        content <- x$debates[[within]][index]

        cat(
          "\n",
          cli::rule(
            sprintf(
              "DEBATES: %s [row %d]",
              within,
              index
            )
          ),
          "\n\n"
        )

        if (is.na(content) || is.null(content)) {
          cat(cli::col_yellow("(empty)\n\n"))
        } else {
          cat(ellmer::interpolate(content), fill = TRUE)
          cat("\n")
        }
      }
    },

    #### Inspect Explanation ----
    explanation = {
      if (!is.null(within)) {
        cli::cli_warn(
          c(
            'Stance result explanation has no sections.',
            'Unused argument: {.arg within}'
          )
        )
      }

      if (index > length(x$summary$explanation)) {
        cli::cli_abort(
          c(
            "Index {index} out of bounds. ",
            "The data have {nrow(x$summary)} rows."
          )
        )
      }

      content <- x[['summary']][['explanation']][index]

      cat(
        "\n",
        cli::rule(
          sprintf("EXPLANATION: [row %d]", index)
        ),
        "\n\n"
      )

      if (is.na(content) || is.null(content)) {
        cat(cli::col_yellow("(empty)\n\n"))
      } else {
        cat(ellmer::interpolate(content), fill = TRUE)
        cat("\n")
      }
    }
  )

  invisible(x)
}

#' @rdname llm_stance
#' @param text The text column (if `x` is a data.frame) or character vector to analyse.
#' @param .output_col Name of the column where results will be stored.
#'
#' @importFrom cli cli_abort cli_warn cli_inform
#' @importFrom rlang is_null as_name
#'
#' @export
#' @examples
#' # results <- llm_stance(
#' #   x = tweets_df,
#' #   text = "text",
#' #   target = "climate_change",
#' #   chat_base = chat_model
#' # )

llm_stance.data.frame <- function(
    x,
    text = NULL,
    target = NULL,
    type = NULL,
    domain_role = NULL,
    language = NULL,
    chat_base,
    scale = 'categorical',
    prompts_dir = NULL,
    verbose = TRUE,
    rpm = 20,
    .output_col = '.stance',
    ...
) {
  data <- x

  # Tidy evaluation
  text_quo <- rlang::enquo(text)
  target_quo <- rlang::enquo(target)
  type_quo <- rlang::enquo(type)
  language_quo <- rlang::enquo(language)
  domain_role_quo <- rlang::enquo(domain_role)

  # Validate and get argument vectors
  text_vec <- catch_eval(text_quo, data)
  target_vec <-  catch_eval(target_quo, data)
  type_vec <- safe_eval(type_quo, data)
  language_vec <- safe_eval(language_quo, data)
  domain_role_vec <- safe_eval(domain_role_quo, data)

  # Fall-back to the defaults
  if (rlang::is_null(type_vec)) {
    type_vec <- c('object', 'statement')
  }

  if (rlang::is_null(language_vec)) {
    cli::cli_warn(
      c("Cannot find {.arg language} in data or environment")
    )
  }

  # Names for messages
  text_name <- rlang::as_name(text_quo)
  target_name <- rlang::as_name(target_quo)

  if (verbose) {
    cli::cli_inform(
      c(
        "i" = "Processing {.val {text_name}} and {.val {target_name}} columns"
      )
    )
  }

  result <- llm_stance(
    x = text_vec,
    target = target_vec,
    type = type_vec,
    language = language_vec,
    domain_role = domain_role_vec,
    chat_base = chat_base,
    scale = scale,
    prompts_dir = prompts_dir,
    verbose = verbose,
    rpm = rpm,
    ...
  )

  # Augment `data`
  n_rows <- nrow(data)
  n_results <- nrow(result$summary)

  if (n_results != n_rows) {
    cli::cli_warn(
      c(
        "Result has {n_results} rows, but data has {n_rows} rows",
        "i" = "Returning only matching rows"
      )
    )
    result$summary <- result$summary[seq_len(min(n_rows, n_results)), ]
  }

  data[[.output_col]] <- c(result$summary$stance, rep(NA, n_rows - n_results))

  attr(data, 'llm_stance_metadata') <- result$metadata

  if (verbose) {
    cli::cli_inform(
      c(
        "v" = "Analysis complete!",
        "i" = "Results added to {.val {(.output_col)}} column"
      )
    )
  }

  return(data)
}

#' Print stance_result object
#'
#' @description
#' A custom print method for `stance_result` objects. It displays a formatted
#' header with processing metadata (items processed, language, models used, etc.)
#' followed by the summary table of stance results.
#' @param x A `stance_result` object.
#' @param ... Additional arguments to [base::print.data.frame()] or other `print` methods for the summary table.
#'
#' @return The input object (invisibly).
#' @importFrom glue glue
#'
#' @export
#' @examples
#' # result <- llm_stance(
#' #   x = "R is smart and tidy",
#' #   target = "R programming language",
#' #   chat_base = ellmer::chat_anthropic()
#' # )
#' # print(result)

print.stance_result <- function(x, ...) {
    cat("Stance Analysis Result\n")
    cat(strrep("=", 60), "\n")
    cat(
        glue::glue("Processed: {x$metadata$n_processed}/{x$metadata$n_total} items"),
        "\n"
    )
    cat(glue::glue("Failed: {x$metadata$n_failed} items"), "\n")
    cat(glue::glue("Language: {x$metadata$language}"), "\n")
    cat(glue::glue("Types: {paste(x$metadata$types, collapse = ', ')}"), "\n")
    cat(
        glue::glue(
            "Domain role(s): {paste(x$metadata$domain_role, collapse = ', ')}"
        ),
        "\n"
    )
    cat(
        glue::glue("Model(s) used: {paste(x$metadata$model, collapse = ', ')}"),
        "\n"
    )
    cat(glue::glue("Time elapsed: {round(x$metadata$elapsed, 2)} sec"), "\n")
    cat(glue::glue("Timestamp: {x$metadata$timestamp}"), "\n")
    cat(strrep("=", 60), "\n\n")

    cat("Summary Table:\n")
    print(x$summary, ...)

    invisible(x)
}

#' Summarise stance_result object
#'
#' @description
#' Provides a statistical summary of the stance analysis results. It displays
#' the frequency distribution of detected stances and a cross-tabulation
#' of stances by target entity/statement.
#' @param object A `stance_result` object.
#' @param ... Additional arguments passed to [base::print.table()].
#'
#' @return The input object (invisibly).
#'
#' @export

summary.stance_result <- function(object, ...) {
    cat("Stance Distribution:\n")
    print(table(object$summary$stance))
    cat("\n")

    cat("By Target:\n")
    print(table(object$summary$target, object$summary$stance), ...)

    invisible(object)
}
