# WARNING - Generated by {fusen} from dev/flat_stancer.Rmd: do not edit by hand # nolint: line_length_linter.

#' Prepare chat configurations for expert agents
#'
#' @description
#' A high-level internal helper that orchestrates the preparation of expert
#' sessions for specific analysis roles (linguist, domain expert, or interpreter).
#'
#' @details
#' This function acts as a bridge between the input data and the execution
#' engine. It extracts necessary variables from the `inputs` list,
#' interpolates the corresponding templates using [prompts_prepare()],
#' and then initialises the chat objects via [tasks_prepare()].
#'
#' @param inputs A list containing all necessary data for prompt interpolation:
#'   - `texts`: Character vector of statements to analyse.
#'   - `targets`: Character vector of analysis targets.
#'   - `target_types`: Character vector of localised target types.
#'   - `prompt_templates`: List of paths to markdown template files.
#'   - `language`: Character string (e.g., "en").
#'   - `domain_roles`: (Optional) Character vector for the domain expert role.
#' @param chat_base An `ellmer::Chat` object used as a template for cloning.
#' @param expert_role Character. One of `"linguist"`, `"domain"`, or `"interpreter"`.
#'
#' @return A list containing:
#' - `chats`: A list of configured `ellmer::Chat` objects.
#' - `tasks`: A character vector of interpolated user prompts.
#'
#' @keywords internal
#' @importFrom rlang arg_match
#' @noRd

prepare_expert_chats <- function(
    inputs,
    chat_base,
    expert_role = c('linguist', 'domain', 'interpreter')
) {
  expert_role <- rlang::arg_match(
    expert_role,
    c('linguist', 'domain', 'interpreter'),
    multiple = FALSE
  )

  # Load instructions for the expert
  prompts <- with(
    inputs,
    prompts_prepare(
      expert_role,
      templates = prompt_templates,
      language = language,
      text = texts,
      target = targets,
      target_type = target_types,
      domain = domain_roles
    )
  )

  tasks_prepare(chat_base, prompts, length(inputs$texts))
}
