# WARNING - Generated by {fusen} from dev/flat_stancer.Rmd: do not edit by hand # nolint: line_length_linter.

#' Prepare chat configurations for judge agent
#'
#' @param inputs Input texts
#' @param chat_base Base chat configuration
#'
#' @return List of chat configurations
#' @keywords internal
#' @noRd

prepare_judger_chats <- function(
    inputs,
    chat_base
) {
  prompts <- with(
    inputs,
    prompts_prepare(
      'judger',
      language = language,
      templates = prompt_templates,
      text = texts,
      target_type = target_types,
      target = targets,
      FavourResponse = debate_results$positive,
      AgainstResponse = debate_results$negative,
      NeutralResponse = debate_results$neutral,
      # Additional instructions based on object types
      add_reference_resolution = 'object' %in% types,
      add_statement_resolution = 'statement' %in% types
    )
  )

  if (length(prompts$system) > 1) {
    abort(
      c(
        "Multiple system prompts are not allowed at stage 3",
        "i" = "Consider checking variable placeholders in system templates"
      )
    )
  }

  tasks_prepare(chat_base, prompts, length(inputs$texts))
}
