# WARNING - Generated by {fusen} from dev/flat_stancer.Rmd: do not edit by hand # nolint: line_length_linter.

#' Prepare chat configurations for debate agents
#'
#' @description
#' Prepares the prompts and chat objects for Stage 2 (Debate). It takes the
#' linguistic, domain, and social media analysis results from Stage 1 and
#' injects them into the 'debater' templates.
#'
#' @param stance Character. The stance label to be debated for (used in prompts).
#' @param inputs A list containing:
#'   - `texts`, `targets`, `target_types`, `language`, `prompt_templates`
#'   - `analysis_results`: A list with `linguistic`, `domain`, and `social_media`
#'     vectors from Stage 1.
#' @param chat_base An `ellmer::Chat` object.
#'
#' @return A list with two elements:
#'   - `chats`: A list containing a single `ellmer::Chat` object.
#'   - `tasks`: A character vector of user prompts for each input text.
#'
#' @keywords internal
#' @noRd

prepare_debater_chats <- function(
    stance,
    inputs,
    chat_base
) {
  # Prepare prompts using all context from Stage 1
  prompts <- with(
    inputs,
    prompts_prepare(
      'debater',
      language = language,
      templates = prompt_templates,
      text = texts,
      target_type = target_types,
      target = targets,
      stance = stance,
      LingResponse = analysis_results$linguistic,
      ExpertResponse = analysis_results$domain,
      UserResponse = analysis_results$social_media
    )
  )

  # Stage 2 requires a consistent system prompt across all items
  if (length(prompts$system) > 1) {
    abort(
      c(
        "Multiple system prompts are not allowed at stage 2",
        "i" = "Consider checking variable placeholders in system templates"
      )
    )
  }

  tasks_prepare(chat_base, prompts, length(inputs$texts))
}
