# WARNING - Generated by {fusen} from dev/flat_stancer.Rmd: do not edit by hand # nolint: line_length_linter.

#' Prepare system and user prompts for a given role
#'
#' @description
#' Loads and interpolates system and user prompt templates for a specific role
#' in the stance analysis workflow. This function prepares the prompts that
#' guide the language model's behaviour for different analysis stages.
#'
#' @details
#' The function supports five distinct roles in the stance analysis pipeline:
#'
#' - **linguist**: Performs linguistic analysis of statements
#' - **domain**: Provides domain-specific expertise and context
#' - **interpreter**: Interprets social media content
#' - **debater**: Presents arguments and counter-arguments
#' - **judger**: Makes final stance judgements (supports additional options)
#'
#' For the `judger` role, additional instructions can be included:
#' - `add_reference_resolution`: Include instructions for resolving references
#' - `add_statement_resolution`: Include instructions for resolving statements
#'
#' The function performs the following operations:
#' 1. Validates the role and language parameters
#' 2. Loads template files for the specified role
#' 3. Interpolates templates with provided variables (via `...`)
#' 4. Validates that prompts are non-empty after interpolation
#'
#' Templates are loaded using `ellmer::interpolate_file()`, which allows
#' for dynamic content insertion and template variable rendering.
#'
#' @param role Role for which to prepare prompts. One of:
#'   - `"linguist"`: Linguistic analysis
#'   - `"domain"`: Domain expertise
#'   - `"interpreter"`: Statement interpretation
#'   - `"debater"`: Argument presentation
#'   - `"judger"`: Final judgement
#'
#' @param templates A list containing template file paths. Expected keys:
#'   - `system-{role}`: Path to system prompt template
#'   - `user-{role}`: Path to user prompt template
#'   - `reference_resolution`: Path to reference resolution instructions (for judger)
#'   - `statement_resolution`: Path to statement resolution instructions (for judger)
#'   - `scale_guide`: Path to scale guide (for judger)
#'
#' @param language Language code for localisation (e.g., "en", "uk", "ru").
#'   Defaults to the first available language. Must be one of the available
#'   languages in the stancer translation dictionary.
#'
#' @param add_reference_resolution Logical. For the `judger` role only.
#'   If `TRUE`, includes instructions for resolving references in statements.
#'   Defaults to `FALSE`.
#'
#' @param add_statement_resolution Logical. For the `judger` role only.
#'   If `TRUE`, includes instructions for resolving statements.
#'   Defaults to `FALSE`.
#'
#' @param ... Additional named arguments passed to `ellmer::interpolate_file()`.
#'   These allow for template variable substitution (e.g., `target = "climate change"`).
#'
#' @return
#' A list with two elements:
#' - `system`: Character string containing the system prompt
#' - `task`: Character string containing the user prompt
#'
#' Both strings are non-empty after interpolation.
#'
#' @seealso
#' [ellmer::interpolate_file()] for template interpolation details.
#'
#' @keywords internal
#'
#' @noRd
#' @examples
#' # Prepare prompts for linguistic analysis
#' # templates <- list(
#' #   `system-linguist` = "prompts/en/system-linguist.md",
#' #   `user-linguist` = "prompts/en/user-linguist.md"
#' # )
#' # 
#' # prompts <- stancer:::prompts_prepare(
#' #   role = "linguist",
#' #   templates = templates,
#' #   language = "en",
#' #   target = "climate change",
#' #   text = c("some text", "and more"),
#' #   target_type = "the object"
#' # )
#' # 
#' # # Prepare prompts for domain expert
#' # templates <- list(
#' #   `system-domain` = "prompts/en/system-domain.md",
#' #   `user-domain` = "prompts/en/user-domain.md"
#' # )
#' # 
#' # prompts <- stancer:::prompts_prepare(
#' #   role = "domain",
#' #   templates = templates,
#' #   language = "en",
#' #   target = "artificial intelligence",
#' #   text = "AI will replace all human jobs",
#' #   target_type = "the object",
#' #   domain = "technology and employment expert"
#' # )
#' # 
#' # # Prepare prompts for judger with additional options
#' # templates <- list(
#' #   `system-judger` = "prompts/en/system-judger.md",
#' #   `user-judger` = "prompts/en/user-judger.md",
#' #   reference_resolution = "prompts/en/reference-resolution.md",
#' #   statement_resolution = "prompts/en/statement-resolution.md",
#' #   scale_guide = "prompts/en/guide-likert.md"
#' # )
#' # 
#' # prompts <- stancer:::prompts_prepare(
#' #   role = "judger",
#' #   templates = templates,
#' #   language = "en",
#' #   add_reference_resolution = TRUE,
#' #   add_statement_resolution = TRUE,
#' #   target = "Climate change is a real concern",
#' #   text = "Global warming is a serious threat",
#' #   target_type = "the statement",
#' #   FavourResponse = "This text is almost a paraphrase of the target statement",
#' #   AgainstResponse = "This is most probably a parody of climate speeches.",
#' #   NeutralResponse = "Context is missing and we should be sceptical"
#' # )
prompts_prepare <- function(
    role,
    templates,
    language = stancer_available_languages(),
    add_reference_resolution = FALSE,
    add_statement_resolution = FALSE,
    ...
) {
  role <- rlang::arg_match(
    role,
    values = c(
      'linguist', 'domain', 'interpreter', 'debater', 'judger'
    ),
    multiple = FALSE
  )
  language <- rlang::arg_match(
    language,
    stancer_available_languages(),
    multiple = FALSE
  )

  # A lot of work for a judger
  if (role == 'judger') {
    if (add_reference_resolution) {
      reference_instruction <- ellmer::interpolate_file(
        templates$reference_resolution
      )
    } else {
      reference_instruction <- ''
    }

    if (add_statement_resolution) {
      statement_instruction <- ellmer::interpolate_file(
        templates$statement_resolution
      )
    } else {
      # Default settings
      statement_instruction <- ''
    }

    scale_guide <- ellmer::interpolate_file(templates$scale_guide)
  }

  template_system <- templates[[glue::glue('system-{role}')]]
  template_user <- templates[[glue::glue('user-{role}')]]

  # Check for file existence
  if (!file.exists(template_system)) {
    abort(
      c(
        "System template not found: {.file {template_system}}",
        "i" = "Available roles: {.val linguist}, {.val domain}, {.val interpreter}, {.val debater}, {.val judger}"
      )
    )
  }
  if (!file.exists(template_user)) {
    abort(
      c(
        "User template not found: {.file {template_user}}",
        "i" = "Available roles: {.val linguist}, {.val domain}, {.val interpreter}, {.val debater}, {.val judger}"
      )
    )
  }

  prompts <- list(
    system = ellmer::interpolate_file(template_system, ...),
    task = ellmer::interpolate_file(template_user, ...)
  )

  # Check for user prompt existence
  if (is.null(prompts$task)) {
    abort("User prompt is NULL for role {.val {role}}")
  }

  # Check for empty strings
  if (any(nchar(prompts$system) == 0)) {
    abort("System prompt is empty after interpolation for role {.val {role}}")
  }
  if (any(nchar(prompts$task) == 0)) {
    abort("User prompt is empty after interpolation for role {.val {role}}")
  }

  prompts
}

#' Prepare chat objects and tasks for execution
#'
#' @description
#' Organises the final structure for parallel execution by cloning the base
#' chat object and pairing it with the corresponding system and user prompts.
#'
#' @details
#' This function handles two main scenarios for system prompts:
#' 1. A single system prompt applied to all tasks.
#' 2. A vector of system prompts matching the number of texts (e.g., when
#'    different domain experts are assigned to different texts).
#'
#' The function clones the `chat_base` for each system prompt to ensure
#' environment isolation during parallel processing. It also performs
#' validation on the user tasks using [tasks_validate()].
#'
#' @param chat_base An `ellmer::Chat` object used as a template.
#' @param prompts A list containing `system` (character vector) and
#'   `task` (character vector) prompts, typically from [prompts_prepare()].
#' @param n_texts Integer. The expected number of texts/tasks to process.
#'
#' @return A list with two elements:
#' - `chats`: A list of cloned and configured `ellmer::Chat` objects.
#' - `tasks`: A character vector of user prompts (tasks).
#'
#' @keywords internal
#'
#' @noRd

tasks_prepare <- function(chat_base, prompts, n_texts) {
  # General case when there may be > 1 system prompts
  ## (e.g. multiple domain roles)
  chats <- lapply(
    prompts$system,
    function(system_prompt) {
      # Each time clone the base chat
      chat <- chat_base$clone(deep = TRUE)
      # Set a system prompt
      chat$set_system_prompt(system_prompt)
      return(chat)
    }
  )

  if (length(chats) != 1 & length(chats) != n_texts) {
    abort(
      "Length of system and user prompts must match {.val {n_texts}}, \\
            got {.val {length(chats)}}"
    )
  }

  tasks_validate(prompts$task, n_texts)

  list(
    chats = chats,
    tasks = prompts$task
  )
}

#' Validate task configuration
#'
#' @description
#' Internal helper to ensure that the generated tasks (user prompts) meet
#' the expected criteria after interpolation. It checks for correct length,
#' data type, and ensures no empty strings were produced.
#'
#' @param tasks A character vector of interpolated tasks.
#' @param expected_length The number of tasks expected (usually matching the number of input texts).
#'
#' @return Invisibly TRUE if validation passes or throws an error if tasks are not a character vector, have incorrect length, or contain empty strings.
#'
#' @keywords internal
#'
#' @noRd

tasks_validate <- function(tasks, expected_length) {
  rlang::try_fetch(
    ellmer:::check_number_whole(expected_length, min = 1),
    error = function(e) abort("Wrong {.arg expected_length} argument.")
  )

  if (any(is.na(tasks))) {
    abort("User prompt list contains missing values")
  }

  if (length(tasks) != expected_length || !is.character(tasks)) {
    abort(
      c(
        "User prompt interpolation returned unexpected results",
        "i" = "Consider checking variable placeholders in user templates"
      )
    )
  }

  if (any(nchar(tasks) == 0)) {
    abort(
      c(
        "User prompt is empty after interpolation",
        "i" = "Check that all required variables are provided"
      )
    )
  }

  invisible(TRUE)
}

#' Collect prompt template file paths
#'
#' @description
#' Scans specified and default directories to locate Markdown template files
#' for a given language and scale type. It follows a priority order: user-defined
#' directory first, followed by the package's internal prompt directories.
#'
#' @param prompts_dir Character string. Path to a custom directory containing
#'   prompt templates. Can be `NULL`.
#' @param language Character string. Language code (e.g., "en", "uk").
#' @param scale Character string. The rating scale type: "categorical",
#'   "numeric", or "likert".
#'
#' @return A named list where keys represent template roles (e.g.,
#'   `system-linguist`, `scale_description`) and values are absolute file paths.
#'
#' @keywords internal
#'
#' @noRd
templates_collect <- function(prompts_dir, language, scale) {
  # 1. Determine default package directories
  DEFAULT_PROMPTS_DIR <- system.file(
    file.path('prompts', language),
    package = 'stancer'
  )
  # Fall-back for development environment
  # if (!dir.exists(DEFAULT_PROMPTS_DIR)) {
  #   DEFAULT_PROMPTS_DIR <- file.path('inst', 'prompts', language)
  # }

  # 2. Filter existing directories
  search_dirs <- c(prompts_dir, DEFAULT_PROMPTS_DIR) |>
    Filter(f = \(x) !is.null(x) && dir.exists(x))

  if (length(search_dirs) == 0) {
    cli::cli_abort(
      "No prompt directories found for language {.val {language}}"
    )
  }

  # 3. Define the set of required role templates
  role_templates <- expand.grid(
    call = c('system', 'user'),
    role = c('linguist', 'domain', 'interpreter', 'debater', 'judger'),
    stringsAsFactors = FALSE
  ) |>
    glue::glue_data('{call}-{role}.md') |>
    as.character() |>
    as.list()

  # Clean names (e.g., "system-linguist.md" -> "system-linguist")
  names(role_templates) <- gsub('\\.md', '', role_templates)

  # 4. Combine with scale-specific and helper files
  # Note: scale is now 'categorical', 'numeric', or 'likert'
  prompt_files <- list(
    scale_description = glue::glue('description-{scale}.md'),
    scale_guide = glue::glue('guide-{scale}.md'),
    reference_resolution = 'reference-resolution.md',
    statement_resolution = 'statement-resolution.md'
  ) |>
    c(role_templates)

  prompt_templates <- list()

  # 5. Resolve paths with priority
  for (name in names(prompt_files)) {
    filename <- prompt_files[[name]]

    found <- FALSE
    for (dir in search_dirs) {
      filepath <- file.path(dir, filename)
      if (file.exists(filepath)) {
        prompt_templates[[name]] <- filepath
        found <- TRUE
        break
      }
    }

    if (!found) {
      cli::cli_abort(
        "Prompt {.file {filename}} not found for language {.val {language}}"
      )
    }
  }

  prompt_templates
}
