# WARNING - Generated by {fusen} from dev/flat_stancer.Rmd: do not edit by hand # nolint: line_length_linter.

#' Recycle argument to specified length
#'
#' @param arg Values to recycle
#' @param n Target length
#'
#' @return Recycled argument values
#' @keywords internal
#' @noRd

recycle_arg <- function(arg, n) {
  arg_name <- deparse(substitute(arg))

  if (length(arg) == 1) {
    return(rep(arg, n))
  } else if (length(arg) == n) {
    return(arg)
  } else {
    abort(
      "{.arg {arg_name}} must have length 1 or {n} (same as {.arg text}). \\
            Got {length(arg)}."
    )
  }
}
