# WARNING - Generated by {fusen} from dev/flat_stancer.Rmd: do not edit by hand # nolint: line_length_linter.

#' Execute Stage 2: Parallel agent debates
#'
#' @param inputs Input texts
#' @param chat_base Chat configuration
#' @param verbose Show progress
#' @param rpm Requests per minute limit
#'
#' @return Debate results
#' @keywords internal
#' @noRd

stage_2_parallel_debates <- function(
    inputs,
    chat_base,
    verbose = TRUE,
    rpm = 500
) {
  # Validate input structure
  required_fields <- c(
    'prompt_templates',
    'language',
    'texts',
    'targets',
    'target_types',
    'analysis_results',
    'scale'
  )
  validate_fields(inputs, required_fields, 'stance debates')

  n <- length(inputs$texts)

  # Ensure Stage 1 results are present and valid
  validate_inputs(inputs$analysis_results$linguistic, n, 'Linguistic analysis')
  validate_inputs(inputs$analysis_results$domain, n, 'Domain expert analysis')
  validate_inputs(inputs$analysis_results$social_media, n, 'Social media analysis')

  tictoc::tic('Stage 2')
  if (verbose) {
    cat(
      glue::glue(
        "\U23F3 Stage 2: Parallel debates ({n} items \U00D7 3 stances)..."),
      "\n"
    )
  }

  stance_labels <- c('positive', 'negative', 'neutral')

  # 1. Prepare tasks for each stance
  debater_tasks <- lapply(
    stance_labels,
    function(stance_label) {
      prepare_debater_chats(
        stance = l(
          inputs$language,
          glue::glue('stance_{stance_label}'),
          inputs$scale
        ),
        inputs = inputs,
        chat_base = chat_base
      )
    }
  )
  names(debater_tasks) <- stance_labels

  # 2. Execute parallel debates for each stance group
  inputs[['debate_results']] <- lapply(
    debater_tasks,
    function(debater_task) {
      ellmer::parallel_chat_text(
        chat = debater_task$chats[[1]],
        prompts = debater_task$tasks,
        rpm = rpm
      ) |> catch('stance debates')
    }
  )

  tictoc::toc(func.toc = stage_complete, quiet = !verbose)

  inputs
}
