# WARNING - Generated by {fusen} from dev/flat_stancer.Rmd: do not edit by hand # nolint: line_length_linter.

#' Execute Stage 3: Judge synthesis
#'
#' @description
#' Orchestrates the final stage of the analysis. It takes the results from all
#' three debate branches and uses a 'judge' agent to produce a structured
#' final stance judgement. This stage uses structured output to ensure the
#' results follow a predefined schema.
#'
#' @param inputs A list containing:
#'   - `texts`, `targets`, `types`, `target_types`, `language`, `prompt_templates`, `scale`.
#'   - `debate_results`: Results from Stage 2.
#' @param chat_base An `ellmer::Chat` object.
#' @param verbose Logical. Whether to print progress and timing.
#' @param rpm Integer. Requests per minute limit for API calls.
#' @param ... Additional arguments passed to `ellmer::parallel_chat_structured`.
#'
#' @return The `inputs` list with an additional element `judgement_results`,
#'   containing the structured stance analysis.
#'
#' @keywords internal
#' @importFrom tictoc tic toc
#' @importFrom glue glue
#' @importFrom ellmer parallel_chat_structured
#' @importFrom cli cli_warn
#' @noRd

stage_3_parallel_judgement <- function(
    inputs,
    chat_base,
    verbose = TRUE,
    rpm = 500,
    ...
) {
  n <- length(inputs$texts)

  # Validate input structure
  required_fields <- c(
    'prompt_templates',
    'language',
    'texts',
    'targets',
    'types',
    'target_types',
    'debate_results',
    'scale'
  )
  validate_fields(inputs, required_fields, 'stance decision')

  # Ensure Stage 2 results are present and valid
  validate_inputs(inputs$debate_results$positive, n, 'Positive stance debates')
  validate_inputs(inputs$debate_results$negative, n, 'Negative stance debates')
  validate_inputs(inputs$debate_results$neutral, n, 'Neutral stance debates')

  tictoc::tic('Stage 3')
  if (verbose) {
    cat(glue::glue("\U23F3 Stage 3: Parallel judgement ({n} items)..."), "\n")
  }

  # 1. Prepare tasks for the judge
  judger_tasks <- prepare_judger_chats(
    inputs,
    chat_base = chat_base
  )

  if (verbose) cat("    \u2696\UFE0F Running parallel judgements...\n")

  # 2. Execute structured parallel judgements
  inputs[['judgement_results']] <- ellmer::parallel_chat_structured(
    chat = judger_tasks$chats[[1]],
    prompts = judger_tasks$tasks,
    type = type_stance_analysis(
      inputs$language,
      inputs$prompt_templates$scale_description,
      inputs$scale
    ),
    rpm = rpm,
    convert = TRUE,
    ...
  ) |> catch('making final judgement')

  # 3. Check for failed judgements (NA values)
  if (any(is.na(inputs$judgement_results$stance))) {
    n_na <- sum(is.na(inputs$judgement_results$stance))
    cli::cli_warn(
      "{n_na} item{?s} returned NA stance",
      call = rlang::expr(llm_stance())
    )
  }

  tictoc::toc(func.toc = stage_complete, quiet = !verbose)

  inputs
}
