# WARNING - Generated by {fusen} from dev/flat_stancer.Rmd: do not edit by hand # nolint: line_length_linter.

#' Execute Stage 1: Parallel expert analysis
#'
#' @description
#' Orchestrates the first stage of the analysis pipeline. It validates the
#' input data, then sequentially triggers three distinct expert analyses:
#' linguistic, domain-specific, and social media interpretation.
#'
#' @details
#' Although the function name contains "parallel", it refers to the
#' independent nature of the expert roles (they don't depend on each
#' other's output). Each role is executed via [execute_role()], which
#' may itself use parallel API requests.
#'
#' @param inputs A list containing all necessary data:
#'   - `texts`: Character vector to analyse.
#'   - `targets`: Character vector of targets.
#'   - `target_types`: Character vector of target types.
#'   - `prompt_templates`: List of template paths.
#'   - `language`: Character string.
#'   - `domain_roles`: Character vector for the domain expert.
#' @param chat_base An `ellmer::Chat` object used as a template.
#' @param verbose Logical. Whether to print stage progress and timing.
#' @param rpm Integer. Requests per minute limit for API calls.
#'
#' @return The `inputs` list with an additional element `analysis_results`,
#'   which is a named list containing character vectors:
#'   - `linguistic`: Results from the linguist role.
#'   - `domain`: Results from the domain expert role.
#'   - `social_media`: Results from the interpreter role.
#'
#' @keywords internal
#' @importFrom tictoc tic toc
#' @importFrom glue glue
#' @noRd

stage_1_parallel_analysis <- function(
    inputs,
    chat_base,
    verbose = TRUE,
    rpm = 500
) {
  # Validate input structure
  required_fields <- c(
    'prompt_templates',
    'language',
    'texts',
    'targets',
    'target_types',
    'domain_roles'
  )
  validate_fields(inputs, required_fields, 'expert analysis')

  n <- length(inputs$texts)

  tictoc::tic('Stage 1')
  if (verbose) {
    cat(
      glue::glue("\U23F3 Stage 1: Expert analysis ({n} items)..."),
      "\n"
    )
  }

  expert_roles <- c('linguist', 'domain', 'interpreter')
  expert_info <- c(
    linguist = 'Linguistic analysis',
    domain = 'Domain expert analysis',
    interpreter = 'Social media interpretation'
  )
  analysis_results <- lapply(
    expert_roles,
    function(role) {
      execute_role(
        role,
        inputs = inputs,
        chat_base = chat_base,
        info = expert_info[[role]],
        rpm = rpm,
        verbose = verbose
      )
    }
  )
  names(analysis_results) <- c('linguistic', 'domain', 'social_media')

  # The result is a list of character vectors of length length(texts)
  ## One vector for each role
  inputs[['analysis_results']] <- analysis_results

  tictoc::toc(func.toc = stage_complete, quiet = !verbose)

  inputs
}
