# WARNING - Generated by {fusen} from dev/flat_stancer.Rmd: do not edit by hand # nolint: line_length_linter.

#' Format timing message
#'
#' @param tic Start time
#' @param toc End time
#' @param msg Message prefix
#'
#' @return Formatted timing message
#' @keywords internal
#' @importFrom glue glue
#' @noRd

stage_complete <- function(tic, toc, msg) {
  tocmsg <- paste0(round(toc - tic, 3), " seconds elapsed")

  if (is.null(msg) || is.na(msg) || length(msg) == 0) {
    outmsg <- tocmsg
  } else {
    outmsg <- glue::glue('\u2705 {msg} complete – {tocmsg}\n\n')
  }
  outmsg
}
