# WARNING - Generated by {fusen} from dev/flat_stancer.Rmd: do not edit by hand # nolint: line_length_linter.

#' Execute Stage 1: Parallel expert analysis
#'
#' @description
#' Orchestrates the first stage of the analysis pipeline. It validates the
#' input data, then sequentially triggers three distinct expert analyses:
#' linguistic, domain-specific, and social media interpretation.
#'
#' @details
#' Although the function name contains "parallel", it refers to the
#' independent nature of the expert roles (they don't depend on each
#' other's output). Each role is executed via [execute_role()], which
#' may itself use parallel API requests.
#'
#' @param inputs A list containing all necessary data:
#'   - `texts`: Character vector to analyse.
#'   - `targets`: Character vector of targets.
#'   - `target_types`: Character vector of target types.
#'   - `prompt_templates`: List of template paths.
#'   - `language`: Character string.
#'   - `domain_roles`: Character vector for the domain expert.
#' @param chat_base An `ellmer::Chat` object used as a template.
#' @param verbose Logical. Whether to print stage progress and timing.
#' @param rpm Integer. Requests per minute limit for API calls.
#'
#' @return The `inputs` list with an additional element `analysis_results`,
#'   which is a named list containing character vectors:
#'   - `linguistic`: Results from the linguist role.
#'   - `domain`: Results from the domain expert role.
#'   - `social_media`: Results from the interpreter role.
#'
#' @keywords internal
#' @importFrom tictoc tic toc
#' @importFrom glue glue
#'
#' @noRd

stage_1_parallel_analysis <- function(
    inputs,
    chat_base,
    verbose = TRUE,
    rpm = 500
) {
  # Validate input structure
  required_fields <- c(
    'prompt_templates',
    'language',
    'texts',
    'targets',
    'target_types',
    'domain_roles'
  )
  validate_fields(inputs, required_fields, 'expert analysis')

  n <- length(inputs$texts)

  tictoc::tic('Stage 1')
  if (verbose) {
    cat(
      glue::glue("\U23F3 Stage 1: Expert analysis ({n} items)..."),
      "\n"
    )
  }

  expert_roles <- c('linguist', 'domain', 'interpreter')
  expert_info <- c(
    linguist = 'Linguistic analysis',
    domain = 'Domain expert analysis',
    interpreter = 'Social media interpretation'
  )
  analysis_results <- lapply(
    expert_roles,
    function(role) {
      execute_role(
        role,
        inputs = inputs,
        chat_base = chat_base,
        info = expert_info[[role]],
        rpm = rpm,
        verbose = verbose
      )
    }
  )
  names(analysis_results) <- c('linguistic', 'domain', 'social_media')

  # The result is a list of character vectors of length length(texts)
  ## One vector for each role
  inputs[['analysis_results']] <- analysis_results

  tictoc::toc(func.toc = stage_complete, quiet = !verbose)

  inputs
}

#' Execute Stage 2: Parallel agent debates
#'
#' @param inputs Input texts
#' @param chat_base Chat configuration
#' @param verbose Show progress
#' @param rpm Requests per minute limit
#'
#' @return Debate results
#' @keywords internal
#'
#' @noRd

stage_2_parallel_debates <- function(
    inputs,
    chat_base,
    verbose = TRUE,
    rpm = 500
) {
  # Validate input structure
  required_fields <- c(
    'prompt_templates',
    'language',
    'texts',
    'targets',
    'target_types',
    'analysis_results',
    'scale'
  )
  validate_fields(inputs, required_fields, 'stance debates')

  n <- length(inputs$texts)

  # Ensure Stage 1 results are present and valid
  validate_inputs(inputs$analysis_results$linguistic, n, 'Linguistic analysis')
  validate_inputs(inputs$analysis_results$domain, n, 'Domain expert analysis')
  validate_inputs(inputs$analysis_results$social_media, n, 'Social media analysis')

  tictoc::tic('Stage 2')
  if (verbose) {
    cat(
      glue::glue(
        "\U23F3 Stage 2: Parallel debates ({n} items \U00D7 3 stances)..."),
      "\n"
    )
  }

  stance_labels <- c('positive', 'negative', 'neutral')

  # 1. Prepare tasks for each stance
  debater_tasks <- lapply(
    stance_labels,
    function(stance_label) {
      prepare_debater_chats(
        stance = l(
          inputs$language,
          glue::glue('stance_{stance_label}'),
          inputs$scale
        ),
        inputs = inputs,
        chat_base = chat_base
      )
    }
  )
  names(debater_tasks) <- stance_labels

  # 2. Execute parallel debates for each stance group
  inputs[['debate_results']] <- lapply(
    debater_tasks,
    function(debater_task) {
      ellmer::parallel_chat_text(
        chat = debater_task$chats[[1]],
        prompts = debater_task$tasks,
        rpm = rpm
      ) |> catch('stance debates')
    }
  )

  tictoc::toc(func.toc = stage_complete, quiet = !verbose)

  inputs
}

#' Execute Stage 3: Judge synthesis
#'
#' @description
#' Orchestrates the final stage of the analysis. It takes the results from all
#' three debate branches and uses a 'judge' agent to produce a structured
#' final stance judgement. This stage uses structured output to ensure the
#' results follow a predefined schema.
#'
#' @param inputs A list containing:
#'   - `texts`, `targets`, `types`, `target_types`, `language`, `prompt_templates`, `scale`.
#'   - `debate_results`: Results from Stage 2.
#' @param chat_base An `ellmer::Chat` object.
#' @param verbose Logical. Whether to print progress and timing.
#' @param rpm Integer. Requests per minute limit for API calls.
#' @param ... Additional arguments passed to `ellmer::parallel_chat_structured`.
#'
#' @return The `inputs` list with an additional element `judgement_results`,
#'   containing the structured stance analysis.
#'
#' @keywords internal
#' @importFrom tictoc tic toc
#' @importFrom glue glue
#' @importFrom ellmer parallel_chat_structured
#' @importFrom cli cli_warn
#'
#' @noRd

stage_3_parallel_judgement <- function(
    inputs,
    chat_base,
    verbose = TRUE,
    rpm = 500,
    ...
) {
  n <- length(inputs$texts)

  # Validate input structure
  required_fields <- c(
    'prompt_templates',
    'language',
    'texts',
    'targets',
    'types',
    'target_types',
    'debate_results',
    'scale'
  )
  validate_fields(inputs, required_fields, 'stance decision')

  # Ensure Stage 2 results are present and valid
  validate_inputs(inputs$debate_results$positive, n, 'Positive stance debates')
  validate_inputs(inputs$debate_results$negative, n, 'Negative stance debates')
  validate_inputs(inputs$debate_results$neutral, n, 'Neutral stance debates')

  tictoc::tic('Stage 3')
  if (verbose) {
    cat(glue::glue("\U23F3 Stage 3: Parallel judgement ({n} items)..."), "\n")
  }

  # 1. Prepare tasks for the judge
  judger_tasks <- prepare_judger_chats(
    inputs,
    chat_base = chat_base
  )

  if (verbose) cat("    \u2696\UFE0F Running parallel judgements...\n")

  # 2. Execute structured parallel judgements
  inputs[['judgement_results']] <- ellmer::parallel_chat_structured(
    chat = judger_tasks$chats[[1]],
    prompts = judger_tasks$tasks,
    type = type_stance_analysis(
      inputs$language,
      inputs$prompt_templates$scale_description,
      inputs$scale
    ),
    rpm = rpm,
    convert = TRUE,
    ...
  ) |> catch('making final judgement')

  # 3. Check for failed judgements (NA values)
  if (any(is.na(inputs$judgement_results$stance))) {
    n_na <- sum(is.na(inputs$judgement_results$stance))
    cli::cli_warn(
      "{n_na} item{?s} returned NA stance",
      call = rlang::expr(llm_stance())
    )
  }

  tictoc::toc(func.toc = stage_complete, quiet = !verbose)

  inputs
}
