# WARNING - Generated by {fusen} from dev/flat_stancer.Rmd: do not edit by hand # nolint: line_length_linter.

#' Check translation dictionary structure
#'
#' @description
#' Validates and displays information about the translation dictionary,
#' including available languages, number of keys, and keys with case variants.
#' Useful for verifying translation completeness and structure.
#'
#' @details
#' This function performs the following checks:
#' - Lists all available languages in the dictionary
#' - Counts total translation keys per language
#' - Identifies keys with case variants (e.g., 'gen', 'dat', 'likert')
#'
#' The function prints a formatted report to the console and returns
#' invisibly TRUE.
#'
#' @return
#' Invisibly `TRUE`. Called for side effects (printing to console).
#'
#' @keywords internal
#' @export
#' @examples
#' stancer_check_translations()

stancer_check_translations <- function() {
  dict <- load_translations()

  cat("Available languages:", paste(names(dict), collapse = ", "), "\n\n")

  for (language in names(dict)) {
    cat("Language:", language, "\n")
    cat("  Keys:", length(dict[[language]]), "\n")

    # Проверка структуры
    cases_keys <- sapply(dict[[language]], function(x) is.list(x))
    if (any(cases_keys)) {
      cat("  Keys with cases:", sum(cases_keys), "\n")
    }
    cat("\n")
  }

  invisible(TRUE)
}
