# WARNING - Generated by {fusen} from dev/flat_stancer.Rmd: do not edit by hand # nolint: line_length_linter.

#' Get available languages for stancer
#'
#' @return Character vector of supported language codes
#' @export
#' @examples
#' stancer_available_languages()

stancer_available_languages <- function() {
  names(load_translations())
}
