# WARNING - Generated by {fusen} from dev/flat_stancer.Rmd: do not edit by hand # nolint: line_length_linter.

#' Truncate numeric values to a range
#'
#' Constrains numeric values to fall within the range [a, b].
#' Values below a are set to a, values above b are set to b.
#'
#' @param x Numeric vector to truncate
#' @param a Numeric. Lower bound (minimum value)
#' @param b Numeric. Upper bound (maximum value)
#'
#' @return Numeric vector with values constrained to [a, b]
#' @keywords internal
#'
#' @examples
#' truncate(c(-1, 0, 5, 10), a = 0, b = 5)
#' # Returns: 0, 0, 5, 5
#' @noRd

truncate <- function(x, a, b) {
  if (!is.numeric(x)) {
    cli::cli_abort("{.arg x} must be numeric")
  }
  if (!is.numeric(a)) {
    cli::cli_abort("{.arg a} must be numeric")
  }
  if (!is.numeric(b)) {
    cli::cli_abort("{.arg b} must be numeric")
  }

  pmin(pmax(x, a), b)
}
