# WARNING - Generated by {fusen} from dev/flat_stancer.Rmd: do not edit by hand # nolint: line_length_linter.

#' Define stance scales for structured data extraction
#'
#' @description
#' These functions define scale types for extracting stance information
#' using `ellmer::parallel_chat_structured()`. They serve as scale definitions
#' for the ellmer structured data extraction tool.
#'
#' @details
#' These functions create type definitions compatible with ellmer's
#' structured extraction framework:
#'
#' - `type_stance_categorical()`: Defines a three-point categorical scale
#'   (Positive, Negative, Neutral)
#' - `type_stance_numeric()`: Defines a continuous numeric scale
#'   (typically -1 to 1)
#' - `type_stance_likert()`: Defines a five-point Likert scale
#'   (Strongly Disagree to Strongly Agree)
#'
#' Each function reads a description from a file using
#' `ellmer::interpolate_file()`, allowing for dynamic content insertion
#' and template rendering.
#'
#' @param description_file Path to a file containing the scale description.
#'   The file may include template variables that will be interpolated
#'   using `ellmer::interpolate_file()`.
#'
#' @return
#' A type definition object compatible with `ellmer::parallel_chat_structured()`.
#' - `type_stance_categorical()` returns an enum type with three values
#' - `type_stance_numeric()` returns a numeric type
#' - `type_stance_likert()` returns an enum type with five values
#'
#' @seealso
#' [ellmer::parallel_chat_structured()] for using these type definitions
#' in structured data extraction tasks.
#'
#'
#' @keywords internal
#' @name type_stance

#' @rdname type_stance
#' @noRd
type_stance_categorical <- function(description_file) {
  ellmer::type_enum(
    values = c('Positive', 'Negative', 'Neutral'),
    description = ellmer::interpolate_file(description_file)
  )
}

#' @rdname type_stance
type_stance_numeric <- function(description_file) {
  ellmer::type_number(
    description = ellmer::interpolate_file(description_file)
  )
}

#' @rdname type_stance
type_stance_likert <- function(description_file) {
  ellmer::type_enum(
    values = c(
      'Strongly Disagree',
      'Disagree',
      'Neutral',
      'Agree',
      'Strongly Agree'
    ),
    description = ellmer::interpolate_file(description_file)
  )
}
