# WARNING - Generated by {fusen} from dev/flat_stancer.Rmd: do not edit by hand # nolint: line_length_linter.

#' Convert analysis type to human-readable term
#'
#' @param type Analysis type: "object" or "statement"
#' @param language Language code
#'
#' @return Character string with localised term
#' @keywords internal
#' @noRd

type_to_term <- function(
    type = c('object', 'statement'),
    language = stancer_available_languages()
) {
  type <- rlang::arg_match(type, c('object', 'statement'), multiple = FALSE)
  language <- rlang::arg_match(language, stancer_available_languages(), multiple = FALSE)

  switch(
    type,
    object = l(language, 'object', 'dat'),
    statement = l(language, 'statement', 'dat')
  )
}
