# WARNING - Generated by {fusen} from dev/flat_stancer.Rmd: do not edit by hand # nolint: line_length_linter.

#' Define stance analysis schema for structured extraction
#'
#' @description
#' Creates a complete schema for stance analysis that combines a stance scale
#' with an explanation field. This schema is designed for use with
#' `ellmer::parallel_chat_structured()` to extract structured stance analysis results.
#'
#' @details
#' This function creates a composite type object containing:
#' - **stance:** A scale type (categorical, numeric, or Likert) for the stance value
#' - **explanation:** A string field for the stance classification explanation
#'
#' The function supports three scale types:
#' - `"numeric"`: Continuous scale (typically -1 to 1)
#' - `"likert"`: Five-point Likert scale (Strongly Disagree to Strongly Agree)
#' - `"categorical"`: Three-point categorical scale (Positive, Negative, Neutral)
#'
#' The explanation field description is automatically localised based on the
#' provided language code using the `'explanation_description'` translation key.
#'
#' @param language Language code for localisation (e.g., "en", "uk", "ru").
#'   Must be one of the available languages in the stancer translation dictionary.
#'
#' @param description_file Path to a file containing the stance scale description.
#'   The file may include template variables that will be interpolated
#'   using `ellmer::interpolate_file()`.
#'
#' @param scale Type of stance scale to use. One of:
#'   - `"numeric"`: Continuous numeric scale
#'   - `"likert"`: Five-point Likert scale
#'   - `"categorical"`: Three-point categorical scale (default)
#'
#' @return
#' A type object compatible with `ellmer::parallel_chat_structured()`.
#' The returned object is a composite type containing:
#' - `stance`: A scale type definition
#' - `explanation`: A string type definition with localised description
#'
#' @seealso
#' [type_stance_categorical()], [type_stance_numeric()], [type_stance_likert()]
#' for individual scale definitions.
#'
#' [ellmer::parallel_chat_structured()] for using this schema in
#' structured data extraction tasks.
#'
#' [l()] for translation lookup.
#'
#'
#' @keywords internal
#' @noRd
type_stance_analysis <- function(language, description_file, scale = "categorical") {
  # Validate scale parameter
  scale <- rlang::arg_match(scale, c("numeric", "likert", "categorical"))

  # A schema for the structured output
  type_stance <- switch(
    scale,
    numeric = type_stance_numeric(description_file),
    likert = type_stance_likert(description_file),
    type_stance_categorical(description_file)
  )

  ellmer::type_object(
    stance = type_stance,
    explanation = ellmer::type_string(
      description = l(language, 'explanation_description')
    )
  )
}
