# WARNING - Generated by {fusen} from dev/flat_stancer.Rmd: do not edit by hand # nolint: line_length_linter.

#' Abort with formatted error message
#'
#' @param ... Arguments passed to cli::cli_abort()
#'
#' @return Throws error
#' @keywords internal
#' @importFrom cli cli_abort
#'
#' @noRd

abort <- function(msg) {
  cli::cli_abort(
    msg,
    call = rlang::expr(llm_stance()),
    .envir = rlang::caller_env()
  )
}

#' Safely evaluate expression and catch errors
#'
#' @param expr Expression to evaluate
#' @param expr_name Name of expression for error messages
#'
#' @return Result of expression or throws an error
#' @keywords internal
#' @importFrom rlang is_scalar_character try_fetch
#' @importFrom cli cli_abort
#'
#' @noRd

catch <- function(
    expr,
    expr_name = paste(deparse(substitute(expr)), collapse = '')
) {
  if (!rlang::is_scalar_character(expr_name)) {
    cli::cli_abort(
      "{.arg expr_name} must be a character scalar.
            Got {.cls {class(expr_name)}}"
    )
  }

  rlang::try_fetch(
    expr,
    error = function(e) {
      abort("Error in {expr_name}: {e$message}")
    }
  )
}

#' Safely evaluate quosures (throws an error)
#'
#' @param quo A quosure to evaluate
#' @param data A data frame, or named list or vector.
#'
#' @return Result of evaluation or throws an error
#' @keywords internal
#' @importFrom rlang is_quosure try_fetch as_name
#' @importFrom cli cli_abort
#' @noRd

catch_eval <- function(
    quo,
    data
) {
  if (!rlang::is_quosure(quo)) {
    cli::cli_abort(
      "{.arg quo} must be a quosure.
            Got {.cls {class(quo)}}"
    )
  }

  rlang::try_fetch(
    rlang::eval_tidy(quo, data),
    error = function(e) {
      abort(
        c(
          "Cannot find {.val {rlang::as_name(quo)}} in data or environment",
          "i" = "Use a column name or provide a vector"
        )
      )
    }
  )
}

#' Recycle argument to specified length
#'
#' @param arg Values to recycle
#' @param n Target length
#'
#' @return Recycled argument values
#' @keywords internal
#'
#' @noRd

recycle_arg <- function(arg, n) {
  arg_name <- deparse(substitute(arg))

  if (length(arg) == 1) {
    return(rep(arg, n))
  } else if (length(arg) == n) {
    return(arg)
  } else {
    abort(
      "{.arg {arg_name}} must have length 1 or {n} (same as {.arg text}). \\
            Got {length(arg)}."
    )
  }
}

#' Safely evaluate quosures (returns NULL)
#'
#' @param quo A quosure to evaluate
#' @param data A data frame, or named list or vector.
#'
#' @return Result of evaluation or `NULL`
#' @keywords internal
#' @importFrom rlang try_fetch
#'
#' @noRd

safe_eval <- function(
    quo,
    data
) {
  rlang::try_fetch(
    catch_eval(quo, data),
    error = function(e) NULL
  )
}

#' Truncate numeric values to a range
#'
#' Constrains numeric values to fall within the range [a, b].
#' Values below a are set to a, values above b are set to b.
#'
#' @param x Numeric vector to truncate
#' @param a Numeric. Lower bound (minimum value)
#' @param b Numeric. Upper bound (maximum value)
#'
#' @return Numeric vector with values constrained to [a, b]
#' @keywords internal
#'
#' @examples
#' truncate(c(-1, 0, 5, 10), a = 0, b = 5)
#' # Returns: 0, 0, 5, 5
#'
#' @noRd

truncate <- function(x, a, b) {
  if (!is.numeric(x)) {
    cli::cli_abort("{.arg x} must be numeric")
  }
  if (!is.numeric(a)) {
    cli::cli_abort("{.arg a} must be numeric")
  }
  if (!is.numeric(b)) {
    cli::cli_abort("{.arg b} must be numeric")
  }

  pmin(pmax(x, a), b)
}
