# WARNING - Generated by {fusen} from dev/flat_stancer.Rmd: do not edit by hand # nolint: line_length_linter.

#' Validate a character argument
#'
#' @param x Input to validate
#'
#' @return Invisibly TRUE or throws error
#' @keywords internal
#' @importFrom rlang is_character
#'
#' @noRd

validate_character <- function(x) {
  arg_name <- deparse(substitute(x))

  if (!rlang::is_character(x)) {
    abort(
      "{.arg {arg_name}} must be a character vector, got {.cls {class(x)}}"
    )
  }
  if (length(x) == 0) {
    abort("{.arg {arg_name}} cannot be empty")
  }
  if (any(is.na(x)) || any(ellmer:::trim(x) == '')) {
    abort(
      c(
        "{.arg {arg_name}} contains empty strings.",
        "i" = "consider removing them before analysis."
      )
    )
  }

  invisible(TRUE)
}

#' Validate input structure and required fields
#'
#' @description
#' An internal helper to ensure that a list (typically an input or result
#' object) contains all the necessary fields required for a specific
#' analysis stage.
#'
#' @param inputs The list or named vector to validate.
#' @param required_fields Character vector of the field names that must
#'   be present in `inputs`.
#' @param input_name Character scalar. A descriptive name for the
#'   object being validated, used in error messages.
#'
#' @return Invisibly TRUE if all required fields are present or throws an error if `inputs` is NULL, if any required fields are missing, or if `input_name` is not a character scalar.
#'
#' @keywords internal
#' @importFrom rlang is_scalar_character
#' @importFrom cli cli_abort
#'
#' @noRd

validate_fields <- function(inputs, required_fields, input_name = 'analysis') {
  if (!rlang::is_scalar_character(input_name)) {
    cli::cli_abort("{.arg input_name} must be a character scalar.")
  }

  if (is.null(inputs)) {
    abort("Input for {input_name} is empty")
  }

  missing_fields <- setdiff(required_fields, names(inputs))
  if (length(missing_fields) > 0) {
    abort(
      "Input for {input_name} misses required fields: {.var {missing_fields}}"
    )
  }

  invisible(TRUE)
}

#' Validate input length
#'
#' @param inputs Input vector
#' @param expected_length Expected length
#' @param input_name Informative name for error messages
#'
#' @return Invisibly TRUE or throws error
#' @keywords internal
#' @importFrom rlang is_scalar_character
#' @importFrom cli cli_abort
#'
#' @noRd

validate_inputs <- function(inputs, expected_length, input_name = 'Inputs') {
  if (!rlang::is_scalar_character(input_name)) {
    cli::cli_abort("{.arg input_name} must be a character scalar.")
  }

  if (is.null(inputs) || length(inputs) != expected_length) {
    abort("{input_name} returned unexpected results")
  }

  invisible(TRUE)
}

#' Validate stage configuration
#'
#' @param x Stage configuration
#' @param stage_name Name of stage for error messages
#'
#' @return Unmodified `x` or throws an error
#' @keywords internal
#'
#' @noRd

validate_stage <- function(x, stage_name) {
  if (is.null(x)) {
    abort("{stage_name} returned NULL")
  }
  x
}
